// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.MustBeInit]
    partial struct Shape
    {
        public enum Kind : byte
        {
            Circle,
            Rectangle,
            Square,
        }

        public readonly Kind kind;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly object? _f0;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly object? _f1;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly object? _f2;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly object? _f3;

        Shape(Kind kind, object? f0, object? f1, object? f2, object? f3)
        {
            this.kind = kind;
            this._f0 = f0;
            this._f1 = f1;
            this._f2 = f2;
            this._f3 = f3;
        }

        public static partial Shape Circle(double radius)
            => new Shape(Kind.Circle, null, radius, null, null);
        public static partial Shape Rectangle(float width, float height)
            => new Shape(Kind.Rectangle, height, null, null, width);
        public static partial Shape Square(int sideLength)
            => new Shape(Kind.Square, null, null, sideLength, null);

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.kind;
            switch (this.kind)
            {
                case Kind.Circle:
                    f0 = this._f1;
                    break;
                case Kind.Square:
                    f0 = this._f2;
                    break;
                default:
                    f0 = null;
                    break;
            }
        }

        public void Deconstruct(out Kind kind, out float width, out float height)
        {
            kind = this.kind;
            width = (float)this._f3!;
            height = (float)this._f0!;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public double radius => (double)this._f1!;
        [EditorBrowsable(EditorBrowsableState.Never)]
        public float width => (float)this._f3!;
        [EditorBrowsable(EditorBrowsableState.Never)]
        public float height => (float)this._f0!;
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int sideLength => (int)this._f2!;
    }
}
