// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.MustBeInit]
    partial struct Shape : global::Spire.IDiscriminatedUnion<Shape.Kind>
    {
        public enum Kind : byte
        {
            Circle,
            Rectangle,
            Square,
        }

        readonly Kind _kind;
        public Kind kind => this._kind;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal object? _f0 { get; init; }
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal object? _f1 { get; init; }
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal object? _f2 { get; init; }
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal object? _f3 { get; init; }

        Shape(Kind kind, object? f0, object? f1, object? f2, object? f3)
        {
            this._kind = kind;
            this._f0 = f0;
            this._f1 = f1;
            this._f2 = f2;
            this._f3 = f3;
        }

        public static partial Shape Circle(double radius)
            => new Shape(Kind.Circle, null, radius, null, null);
        public static partial Shape Rectangle(float width, float height)
            => new Shape(Kind.Rectangle, height, null, null, width);
        public static partial Shape Square(int sideLength)
            => new Shape(Kind.Square, null, null, sideLength, null);

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.kind;
            switch (this.kind)
            {
                case Kind.Circle:
                    f0 = this._f1;
                    break;
                case Kind.Square:
                    f0 = this._f2;
                    break;
                default:
                    f0 = null;
                    break;
            }
        }

        public void Deconstruct(out Kind kind, out float width, out float height)
        {
            kind = this.kind;
            width = (float)this._f3!;
            height = (float)this._f0!;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public double radius
        {
            get => (double)this._f1!;
            init => this._f1 = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public float width
        {
            get => (float)this._f3!;
            init => this._f3 = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public float height
        {
            get => (float)this._f0!;
            init => this._f0 = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int sideLength
        {
            get => (int)this._f2!;
            init => this._f2 = value;
        }
        public bool IsCircle => this.kind == Kind.Circle;
        public bool IsRectangle => this.kind == Kind.Rectangle;
        public bool IsSquare => this.kind == Kind.Square;
        public override string ToString()
        {
            return this.kind switch
            {
                Kind.Circle => $"Circle({this.radius})",
                Kind.Rectangle => $"Rectangle({this.width}, {this.height})",
                Kind.Square => $"Square({this.sideLength})",
                _ => "Shape(?)",
            };
        }
    }
}
