// <auto-generated/>
#nullable enable

namespace TestNs
{
    public partial class Box<T>
    {
        public readonly struct GetInliner : global::Houtamelo.Spire.IFuncInliner<global::TestNs.Box<T>, T>
        {
            public T Invoke(global::TestNs.Box<T> instance) => instance.Get();
        }
    }
}
