// <auto-generated/>
#nullable enable

using System;
using Houtamelo.Spire;

namespace TestNs
{
    public static partial class Aliases
    {
        public static void Run<TActionInliner>(bool cond, int x, TActionInliner action)
            where TActionInliner : struct, global::Houtamelo.Spire.IActionInliner<int>
        {
            var a = action;
            var b = action;
            var c = cond ? a : b;
            c.Invoke(x);
        }
    }
}
