// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;

namespace TestNs
{
    [global::Houtamelo.Spire.Core.EnforceInitialization]
    [StructLayout(LayoutKind.Explicit)]
    partial struct Shape : global::Houtamelo.Spire.Core.IDiscriminatedUnion<Shape.Kind>
    {
        public enum Kind : byte
        {
            Circle,
            Rectangle,
            Square,
        }

        [FieldOffset(0)]
        readonly Kind _kind;
        public Kind kind => this._kind;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [FieldOffset(1)]
        internal readonly float _height;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [FieldOffset(5)]
        internal readonly double _radius;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [FieldOffset(13)]
        internal readonly int _sideLength;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [FieldOffset(17)]
        internal readonly float _width;

        Shape(Kind kind) : this()
        {
            this._kind = kind;
        }

        public static partial Shape Circle(double radius)
        {
            var s = new Shape(Kind.Circle);
            Unsafe.AsRef(in s._radius) = radius;
            return s;
        }
        public static partial Shape Rectangle(float width, float height)
        {
            var s = new Shape(Kind.Rectangle);
            Unsafe.AsRef(in s._width) = width;
            Unsafe.AsRef(in s._height) = height;
            return s;
        }
        public static partial Shape Square(int sideLength)
        {
            var s = new Shape(Kind.Square);
            Unsafe.AsRef(in s._sideLength) = sideLength;
            return s;
        }

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.kind;
            switch (this.kind)
            {
                case Kind.Circle:
                    f0 = this._radius;
                    break;
                case Kind.Square:
                    f0 = this._sideLength;
                    break;
                default:
                    f0 = null;
                    break;
            }
        }

        public void Deconstruct(out Kind kind, out float width, out float height)
        {
            kind = this.kind;
            width = this._width;
            height = this._height;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public float height
        {
            get => this._height;
            init => this._height = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public double radius
        {
            get => this._radius;
            init => this._radius = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int sideLength
        {
            get => this._sideLength;
            init => this._sideLength = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public float width
        {
            get => this._width;
            init => this._width = value;
        }
        public bool IsCircle => this.kind == Kind.Circle;
        public bool IsRectangle => this.kind == Kind.Rectangle;
        public bool IsSquare => this.kind == Kind.Square;
        public override string ToString()
        {
            return this.kind switch
            {
                Kind.Circle => $"Circle({this.radius})",
                Kind.Rectangle => $"Rectangle({this.width}, {this.height})",
                Kind.Square => $"Square({this.sideLength})",
                _ => "Shape(?)",
            };
        }
    }
}
