// <auto-generated/>
#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TestNs
{
    internal sealed class ResultStjConverterFactory : JsonConverterFactory
    {
        public override bool CanConvert(Type typeToConvert)
            => typeToConvert.IsGenericType && typeToConvert.GetGenericTypeDefinition() == typeof(Result<,>);

        public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)
        {
            var converterType = typeof(ResultStjConverter<,>).MakeGenericType(typeToConvert.GetGenericArguments());
            return (JsonConverter)Activator.CreateInstance(converterType)!;
        }
    }

    internal sealed class ResultStjConverter<T, E> : JsonConverter<Result<T, E>>
    {
        public override Result<T, E> Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            using var doc = JsonDocument.ParseValue(ref reader);
            var root = doc.RootElement;
            if (!root.TryGetProperty("kind", out var kindProp))
                throw new JsonException("Missing discriminator property 'kind'");
            var kindStr = kindProp.GetString();
            return kindStr switch
            {
                "Ok" => new Result<T, E>.Ok(root.GetProperty("Value").Deserialize<T>(options)!),
                "Err" => new Result<T, E>.Err(root.GetProperty("Error").Deserialize<E>(options)!),
                _ => throw new JsonException($"Unknown Result variant: {kindStr}")
            };
        }

        public override void Write(Utf8JsonWriter writer, Result<T, E> value, JsonSerializerOptions options)
        {
            writer.WriteStartObject();
            switch (value)
            {
                case Result<T, E>.Ok _v:
                    writer.WriteString("kind", "Ok");
                    writer.WritePropertyName("Value");
                    JsonSerializer.Serialize(writer, _v.Value, options);
                    break;
                case Result<T, E>.Err _v:
                    writer.WriteString("kind", "Err");
                    writer.WritePropertyName("Error");
                    JsonSerializer.Serialize(writer, _v.Error, options);
                    break;
                default:
                    throw new JsonException($"Unknown Result variant: {value}");
            }
            writer.WriteEndObject();
        }
    }

    [global::System.Text.Json.Serialization.JsonConverter(typeof(ResultStjConverterFactory))]
    public abstract partial class Result<T, E> { }
}
