// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;

namespace My.Deep.Namespace
{
    [global::Houtamelo.Spire.Core.EnforceInitializationAttribute]
    [StructLayout(LayoutKind.Explicit)]
    partial struct Result : global::Houtamelo.Spire.Core.IDiscriminatedUnion<Result.Kind>
    {
        public enum Kind : byte
        {
            Ok,
            Err,
        }

        [FieldOffset(0)]
        readonly Kind _kind;
        public Kind kind => this._kind;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [FieldOffset(1)]
        internal readonly int _value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [FieldOffset(8)]
        internal readonly string? _message;

        Result(Kind kind) : this()
        {
            this._kind = kind;
        }

        public static partial Result Ok(int value)
        {
            var s = new Result(Kind.Ok);
            Unsafe.AsRef(in s._value) = value;
            return s;
        }
        public static partial Result Err(string message)
        {
            var s = new Result(Kind.Err);
            Unsafe.AsRef(in s._message) = message;
            return s;
        }

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.kind;
            switch (this.kind)
            {
                case Kind.Ok:
                    f0 = this._value;
                    break;
                case Kind.Err:
                    f0 = this._message;
                    break;
                default:
                    f0 = null;
                    break;
            }
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int value
        {
            get => this._value;
            init => this._value = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string message
        {
            get => this._message!;
            init => this._message = value;
        }
        public bool IsOk => this.kind == Kind.Ok;
        public bool IsErr => this.kind == Kind.Err;
        public override string ToString()
        {
            return this.kind switch
            {
                Kind.Ok => $"Ok({this.value})",
                Kind.Err => $"Err({this.message})",
                _ => "Result(?)",
            };
        }
    }
}
