// <auto-generated/>
#nullable enable

namespace Shapes
{
    public abstract partial record Shape
    {
        public sealed partial record Circle
        {
            public override string ToString() => $"Circle({this.Radius})";
        }
        public sealed partial record Square
        {
            public override string ToString() => $"Square({this.Side})";
        }
        public sealed partial record Point
        {
            public override string ToString() => "Point()";
        }
    }
}
