using System;

namespace Houtamelo.Spire;

/// <summary>
/// Interface implemented by all struct discriminated unions generated by the Spire source generator.
/// Provides access to the variant discriminator (<see cref="kind"/>).
/// </summary>
/// <typeparam name="TEnum">The generated <c>Kind</c> enum type for this union.</typeparam>
public interface IDiscriminatedUnion<out TEnum> where TEnum : Enum
{
    /// <summary>The active variant of this union instance.</summary>
    TEnum kind { get; }
}
