// <auto-generated/>
#nullable enable

using System;
using Houtamelo.Spire;

namespace TestNs
{
    public static partial class Runner
    {
        public static void Run<TCbInliner>(TCbInliner cb, int a, int b, int c)
            where TCbInliner : struct, global::Houtamelo.Spire.IActionInliner<int, int, int>
        {
            cb.Invoke(a, b, c);
        }
    }
}
