// <auto-generated/>
#nullable enable

using System;
using Houtamelo.Spire;

namespace TestNs
{
    public static partial class Notifier
    {
        public static void Fire<TCbInliner>(int x, TCbInliner? cb)
            where TCbInliner : struct, global::Houtamelo.Spire.IActionInliner<int>
        {
            cb?.Invoke(x);
        }
    }
}
