// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    [global::Houtamelo.Spire.Core.EnforceInitializationAttribute]
    readonly partial struct Immutable : global::Houtamelo.Spire.Core.IDiscriminatedUnion<Immutable.Kind>
    {
        public enum Kind : byte
        {
            A,
            B,
        }

        readonly Kind _kind;
        public Kind kind => this._kind;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal object? _f0 { get; init; }
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal object? _f1 { get; init; }

        Immutable(Kind kind, object? f0, object? f1)
        {
            this._kind = kind;
            this._f0 = f0;
            this._f1 = f1;
        }

        public static partial Immutable A(int x)
            => new Immutable(Kind.A, x, null);
        public static partial Immutable B(string y)
            => new Immutable(Kind.B, null, y);

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.kind;
            switch (this.kind)
            {
                case Kind.A:
                    f0 = this._f0;
                    break;
                case Kind.B:
                    f0 = this._f1;
                    break;
                default:
                    f0 = null;
                    break;
            }
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int x
        {
            get => (int)this._f0!;
            init => this._f0 = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string y
        {
            get => (string)this._f1!;
            init => this._f1 = value;
        }
        public bool IsA => this.kind == Kind.A;
        public bool IsB => this.kind == Kind.B;
        public override string ToString()
        {
            return this.kind switch
            {
                Kind.A => $"A({this.x})",
                Kind.B => $"B({this.y})",
                _ => "Immutable(?)",
            };
        }
    }
}
