// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;

namespace My.Deep.Namespace
{
    [global::Spire.Analyzers.MustBeInit]
    [StructLayout(LayoutKind.Explicit)]
    partial struct Result
    {
        public enum Kind : byte
        {
            Ok,
            Err,
        }

        [FieldOffset(0)]
        public readonly Kind tag;

        [FieldOffset(1)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public readonly int ok_value;

        [FieldOffset(8)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public readonly string? err_message;

        Result(Kind tag) : this()
        {
            this.tag = tag;
        }

        public static partial Result Ok(int value)
        {
            var s = new Result(Kind.Ok);
            Unsafe.AsRef(in s.ok_value) = value;
            return s;
        }
        public static partial Result Err(string message)
        {
            var s = new Result(Kind.Err);
            Unsafe.AsRef(in s.err_message) = message;
            return s;
        }

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.tag;
            switch (this.tag)
            {
                case Kind.Ok:
                    f0 = this.ok_value;
                    break;
                case Kind.Err:
                    f0 = this.err_message;
                    break;
                default:
                    f0 = null;
                    break;
            }
        }
    }
}
