// <auto-generated/>
#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

internal sealed class TokenStjConverter : JsonConverter<Token>
{
    public override Token Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var doc = JsonDocument.ParseValue(ref reader);
        var root = doc.RootElement;
        if (!root.TryGetProperty("kind", out var kindProp))
            throw new JsonException("Missing discriminator property 'kind'");
        var kindStr = kindProp.GetString();
        return kindStr switch
        {
            "Ident" => Token.Ident(),
            "Number" => Token.Number(),
            "Eof" => Token.Eof(),
            _ => throw new JsonException($"Unknown Token variant: {kindStr}")
        };
    }

    public override void Write(Utf8JsonWriter writer, Token value, JsonSerializerOptions options)
    {
        writer.WriteStartObject();
        switch (value)
        {
            case { kind: Token.Kind.Ident }:
            {
                writer.WriteString("kind", "Ident");
                break;
            }
            case { kind: Token.Kind.Number }:
            {
                writer.WriteString("kind", "Number");
                break;
            }
            case { kind: Token.Kind.Eof }:
            {
                writer.WriteString("kind", "Eof");
                break;
            }
            default:
                throw new JsonException($"Unknown Token variant: {value.kind}");
        }
        writer.WriteEndObject();
    }
}

[global::System.Text.Json.Serialization.JsonConverter(typeof(TokenStjConverter))]
partial struct Token { }
