// <auto-generated/>
#nullable enable

namespace My.Deep.Namespace
{
    public abstract partial record Result
    {
        private Result() { }

        public sealed partial record Ok;
        public sealed partial record Error;

        public bool IsOk => this is Ok;
        public bool IsError => this is Error;
    }
}
