// <auto-generated/>
#nullable enable
using System.ComponentModel;

[global::Spire.Analyzers.MustBeInit]
partial struct Shape
{
    public enum Kind : byte
    {
        Circle,
        Square,
        Point,
    }

    public readonly Kind tag;
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal readonly double _s0;
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal readonly int _s1;

    Shape(Kind tag, double s0, int s1)
    {
        this.tag = tag;
        this._s0 = s0;
        this._s1 = s1;
    }

    public static partial Shape Circle(double radius)
        => new Shape(Kind.Circle, radius, default);
    public static partial Shape Square(int sideLength)
        => new Shape(Kind.Square, default, sideLength);
    public static partial Shape Point()
        => new Shape(Kind.Point, default, default);

    public void Deconstruct(out Kind kind, out object? f0)
    {
        kind = this.tag;
        f0 = null;
    }
}
