// <auto-generated/>
#nullable enable

namespace Access
{
    internal abstract partial record Outcome
    {
        private Outcome() { }

        public sealed partial record Success;
        public sealed partial record Failure;
    }
}
