// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    [global::Houtamelo.Spire.Core.EnforceInitializationAttribute]
    partial struct Light : global::Houtamelo.Spire.Core.IDiscriminatedUnion<Light.Kind>
    {
        public enum Kind : byte
        {
            Red,
            Yellow,
            Green,
        }

        readonly Kind _kind;
        public Kind kind => this._kind;

        Light(Kind kind)
        {
            this._kind = kind;
        }

        public static partial Light Red()
            => new Light(Kind.Red);
        public static partial Light Yellow()
            => new Light(Kind.Yellow);
        public static partial Light Green()
            => new Light(Kind.Green);

        public void Deconstruct(out Kind kind, out object? _f0)
        {
            kind = this.kind;
            _f0 = null;
        }
        public bool IsRed => this.kind == Kind.Red;
        public bool IsYellow => this.kind == Kind.Yellow;
        public bool IsGreen => this.kind == Kind.Green;
        public override string ToString()
        {
            return this.kind switch
            {
                Kind.Red => "Red()",
                Kind.Yellow => "Yellow()",
                Kind.Green => "Green()",
                _ => "Light(?)",
            };
        }
    }
}
