// <auto-generated/>
#nullable enable

namespace Shapes
{
    public abstract partial record Shape
    {
        public static global::System.Lazy<string> JsonSchema { get; } = new(BuildJsonSchema);

        private static string BuildJsonSchema()
        {
            return @"{""oneOf"":[{""type"":""object"",""properties"":{""kind"":{""const"":""Circle""},""Radius"":{""type"":""number""}},""required"":[""kind"",""Radius""]},{""type"":""object"",""properties"":{""kind"":{""const"":""Square""},""Side"":{""type"":""integer""}},""required"":[""kind"",""Side""]}],""discriminator"":{""propertyName"":""kind""}}";
        }
    }
}
