// <auto-generated/>
#nullable enable

namespace TestNs
{
    [global::Spire.Analyzers.MustBeInit]
    internal partial struct Internal
    {
        public enum Kind
        {
            X,
        }

        public readonly Kind tag;
        readonly object? _f0;

        Internal(Kind tag, object? f0)
        {
            this.tag = tag;
            this._f0 = f0;
        }

        public static Internal NewX(int v)
            => new Internal(Kind.X, v);

        public void Deconstruct(out Kind kind, out int v)
        {
            kind = this.tag;
            v = (int)this._f0!;
        }
    }
}
