// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.Analyzers.MustBeInit]
    internal partial struct Internal
    {
        public enum Kind : byte
        {
            X,
        }

        public readonly Kind kind;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly object? _f0;

        Internal(Kind kind, object? f0)
        {
            this.kind = kind;
            this._f0 = f0;
        }

        public static partial Internal X(int v)
            => new Internal(Kind.X, v);

        public void Deconstruct(out Kind kind, out int v)
        {
            kind = this.kind;
            v = (int)this._f0!;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int v => (int)this._f0!;
    }
}
