// <auto-generated/>
#nullable enable
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[global::Houtamelo.Spire.Core.EnforceInitialization]
partial struct Result<T> : global::Houtamelo.Spire.Core.IDiscriminatedUnion<Result<T>.Kind>
{
    public enum Kind : byte
    {
        Ok,
        Err,
    }

    readonly Kind _kind;
    public Kind kind => this._kind;

    [InlineArray(4)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal struct _Buffer { internal byte _element; }

    [EditorBrowsable(EditorBrowsableState.Never)]
    internal _Buffer _data;

    [EditorBrowsable(EditorBrowsableState.Never)]
    internal T _s0;

    Result(Kind kind)
    {
        this._kind = kind;
        this._data = default;
        this._s0 = default!;
    }

    public static partial Result<T> Ok(T value, int code)
    {
        var s = new Result<T>(Kind.Ok);
        s._s0 = value;
        Unsafe.WriteUnaligned(ref s._data[0], code);
        return s;
    }
    public static partial Result<T> Err(int code)
    {
        var s = new Result<T>(Kind.Err);
        Unsafe.WriteUnaligned(ref s._data[0], code);
        return s;
    }

    public void Deconstruct(out Kind kind, out int code)
    {
        kind = this.kind;
        code = Unsafe.ReadUnaligned<int>(ref _data[0]);
    }

    public void Deconstruct(out Kind kind, out T value, out int code)
    {
        kind = this.kind;
        value = this._s0;
        code = Unsafe.ReadUnaligned<int>(ref _data[0]);
    }
    [EditorBrowsable(EditorBrowsableState.Never)]
    public T value
    {
        get => this._s0;
        init => this._s0 = value;
    }
    [EditorBrowsable(EditorBrowsableState.Never)]
    public int code
    {
        get => Unsafe.ReadUnaligned<int>(ref _data[0]);
        init => Unsafe.WriteUnaligned(ref _data[0], value);
    }
    public bool IsOk => this.kind == Kind.Ok;
    public bool IsErr => this.kind == Kind.Err;
    public override string ToString()
    {
        return this.kind switch
        {
            Kind.Ok => $"Ok({this.value}, {this.code})",
            Kind.Err => $"Err({this.code})",
            _ => "Result(?)",
        };
    }
}
