// <auto-generated/>
#nullable enable

namespace MyApp
{
    public abstract partial class Command
    {
        private Command() { }

        public sealed partial class Start;
        public sealed partial class Stop;

        public bool IsStart => this is Start;
        public bool IsStop => this is Stop;
    }
}
