// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;

namespace TestNs
{
    public partial class Outer
    {
        [global::Spire.Analyzers.MustBeInit]
        [StructLayout(LayoutKind.Explicit)]
        internal partial struct Shape
        {
            public enum Kind : byte
            {
                Circle,
                Square,
            }

            [FieldOffset(0)]
            public readonly Kind tag;

            [FieldOffset(1)]
            [EditorBrowsable(EditorBrowsableState.Never)]
            internal readonly double _radius;

            [FieldOffset(9)]
            [EditorBrowsable(EditorBrowsableState.Never)]
            internal readonly int _sideLength;

            Shape(Kind tag) : this()
            {
                this.tag = tag;
            }

            public static partial Shape Circle(double radius)
            {
                var s = new Shape(Kind.Circle);
                Unsafe.AsRef(in s._radius) = radius;
                return s;
            }
            public static partial Shape Square(int sideLength)
            {
                var s = new Shape(Kind.Square);
                Unsafe.AsRef(in s._sideLength) = sideLength;
                return s;
            }

            public void Deconstruct(out Kind kind, out object? f0)
            {
                kind = this.tag;
                switch (this.tag)
                {
                    case Kind.Circle:
                        f0 = this._radius;
                        break;
                    case Kind.Square:
                        f0 = this._sideLength;
                        break;
                    default:
                        f0 = null;
                        break;
                }
            }
            [EditorBrowsable(EditorBrowsableState.Never)]
            public double radius => this._radius;
            [EditorBrowsable(EditorBrowsableState.Never)]
            public int sideLength => this._sideLength;
        }
    }
}
