// <auto-generated/>
#nullable enable

namespace MyApp
{
    abstract partial class Result<T, E>
    {
        private Result() { }

        sealed partial class Ok;
        sealed partial class Err;
    }
}
