// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.MustBeInit]
    partial struct Token
    {
        public enum Kind : byte
        {
            Ident,
            Number,
            Eof,
        }

        public readonly Kind kind;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly object? _f0;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly object? _f1;

        Token(Kind kind, object? f0, object? f1)
        {
            this.kind = kind;
            this._f0 = f0;
            this._f1 = f1;
        }

        public static partial Token Ident(string name)
            => new Token(Kind.Ident, name, null);
        public static partial Token Number(int value)
            => new Token(Kind.Number, null, value);
        public static partial Token Eof()
            => new Token(Kind.Eof, null, null);

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.kind;
            switch (this.kind)
            {
                case Kind.Ident:
                    f0 = this._f0;
                    break;
                case Kind.Number:
                    f0 = this._f1;
                    break;
                default:
                    f0 = null;
                    break;
            }
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string name => (string)this._f0!;
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int value => (int)this._f1!;
    }
}
