// <auto-generated/>
#nullable enable

namespace TestNs
{
    [global::Spire.Analyzers.MustBeInit]
    internal partial struct Token
    {
        public enum Kind
        {
            Ident,
            Number,
            Eof,
        }

        public readonly Kind tag;
        readonly object? _f0;

        Token(Kind tag, object? f0)
        {
            this.tag = tag;
            this._f0 = f0;
        }

        public static partial Token Ident(string name)
            => new Token(Kind.Ident, name);
        public static partial Token Number(int value)
            => new Token(Kind.Number, value);
        public static partial Token Eof()
            => new Token(Kind.Eof, null);

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.tag;
            f0 = this._f0;
        }
    }
}
