// <auto-generated/>
#nullable enable

using System;
using Houtamelo.Spire;

namespace TestNs
{
    public static partial class Runner
    {
        public static void Run<TCbInliner>(TCbInliner cb, int a, int b, int c, int d, int e, int f, int g, int h)
            where TCbInliner : struct, global::Houtamelo.Spire.IActionInliner<int, int, int, int, int, int, int, int>
        {
            cb.Invoke(a, b, c, d, e, f, g, h);
        }
    }
}
