// <auto-generated/>
#nullable enable

namespace TestNs
{
    public static partial class Samples
    {
        public readonly struct BigInliner : global::Houtamelo.Spire.IActionInliner<int, int, int, int, int, int, int, int>
        {
            public void Invoke(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8)
                => Samples.Big(a1, a2, a3, a4, a5, a6, a7, a8);
        }
    }
}
