// <auto-generated/>
#nullable enable

namespace Commands
{
    public abstract partial class Command
    {
        public sealed partial class Start
        {
            public override string ToString() => "Start()";
        }
        public sealed partial class Stop
        {
            public override string ToString() => "Stop()";
        }
    }
}
