// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.Analyzers.MustBeInit]
    [StructLayout(LayoutKind.Explicit)]
    partial struct Drawing
    {
        public enum Kind : byte
        {
            Dot,
            Line,
        }

        [FieldOffset(0)]
        public readonly Kind tag;

        [FieldOffset(8)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly object? _obj_end;

        [FieldOffset(16)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly object? _obj_location;

        [FieldOffset(24)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly object? _obj_start;

        Drawing(Kind tag) : this()
        {
            this.tag = tag;
        }

        public static partial Drawing Dot(global::TestNs.Point location)
        {
            var s = new Drawing(Kind.Dot);
            Unsafe.AsRef(in s._obj_location) = location;
            return s;
        }
        public static partial Drawing Line(global::TestNs.Point start, global::TestNs.Point end)
        {
            var s = new Drawing(Kind.Line);
            Unsafe.AsRef(in s._obj_start) = start;
            Unsafe.AsRef(in s._obj_end) = end;
            return s;
        }

        public void Deconstruct(out Kind kind, out global::TestNs.Point location)
        {
            kind = this.tag;
            location = (global::TestNs.Point)this._obj_location!;
        }

        public void Deconstruct(out Kind kind, out global::TestNs.Point start, out global::TestNs.Point end)
        {
            kind = this.tag;
            start = (global::TestNs.Point)this._obj_start!;
            end = (global::TestNs.Point)this._obj_end!;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public global::TestNs.Point end => (global::TestNs.Point)this._obj_end!;
        [EditorBrowsable(EditorBrowsableState.Never)]
        public global::TestNs.Point location => (global::TestNs.Point)this._obj_location!;
        [EditorBrowsable(EditorBrowsableState.Never)]
        public global::TestNs.Point start => (global::TestNs.Point)this._obj_start!;
    }
}
