// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.MustBeInit]
    [StructLayout(LayoutKind.Explicit)]
    partial struct Drawing : global::Spire.IDiscriminatedUnion<Drawing.Kind>
    {
        public enum Kind : byte
        {
            Dot,
            Line,
        }

        [FieldOffset(0)]
        readonly Kind _kind;
        public Kind kind => this._kind;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [FieldOffset(8)]
        internal readonly object? _obj_end;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [FieldOffset(16)]
        internal readonly object? _obj_location;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [FieldOffset(24)]
        internal readonly object? _obj_start;

        Drawing(Kind kind) : this()
        {
            this._kind = kind;
        }

        public static partial Drawing Dot(global::TestNs.Point location)
        {
            var s = new Drawing(Kind.Dot);
            Unsafe.AsRef(in s._obj_location) = location;
            return s;
        }
        public static partial Drawing Line(global::TestNs.Point start, global::TestNs.Point end)
        {
            var s = new Drawing(Kind.Line);
            Unsafe.AsRef(in s._obj_start) = start;
            Unsafe.AsRef(in s._obj_end) = end;
            return s;
        }

        public void Deconstruct(out Kind kind, out global::TestNs.Point location)
        {
            kind = this.kind;
            location = (global::TestNs.Point)this._obj_location!;
        }

        public void Deconstruct(out Kind kind, out global::TestNs.Point start, out global::TestNs.Point end)
        {
            kind = this.kind;
            start = (global::TestNs.Point)this._obj_start!;
            end = (global::TestNs.Point)this._obj_end!;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public global::TestNs.Point end
        {
            get => (global::TestNs.Point)this._obj_end!;
            init => this._obj_end = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public global::TestNs.Point location
        {
            get => (global::TestNs.Point)this._obj_location!;
            init => this._obj_location = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public global::TestNs.Point start
        {
            get => (global::TestNs.Point)this._obj_start!;
            init => this._obj_start = value;
        }
        public bool IsDot => this.kind == Kind.Dot;
        public bool IsLine => this.kind == Kind.Line;
        public override string ToString()
        {
            return this.kind switch
            {
                Kind.Dot => $"Dot({this.location})",
                Kind.Line => $"Line({this.start}, {this.end})",
                _ => "Drawing(?)",
            };
        }
    }
}
