// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.Analyzers.MustBeInit]
    [StructLayout(LayoutKind.Explicit)]
    internal partial struct Drawing
    {
        public enum Kind
        {
            Dot,
            Line,
        }

        [FieldOffset(0)]
        public readonly Kind tag;

        [FieldOffset(8)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        readonly object? _obj_0;

        [FieldOffset(16)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        readonly object? _obj_1;

        Drawing(Kind tag) : this()
        {
            this.tag = tag;
        }

        public static partial Drawing Dot(global::TestNs.Point location)
        {
            var s = new Drawing(Kind.Dot);
            Unsafe.AsRef(in s._obj_0) = location;
            return s;
        }
        public static partial Drawing Line(global::TestNs.Point start, global::TestNs.Point end)
        {
            var s = new Drawing(Kind.Line);
            Unsafe.AsRef(in s._obj_0) = start;
            Unsafe.AsRef(in s._obj_1) = end;
            return s;
        }

        public void Deconstruct(out Kind kind, out global::TestNs.Point location)
        {
            kind = this.tag;
            location = (global::TestNs.Point)this._obj_0!;
        }

        public void Deconstruct(out Kind kind, out global::TestNs.Point start, out global::TestNs.Point end)
        {
            kind = this.tag;
            start = (global::TestNs.Point)this._obj_0!;
            end = (global::TestNs.Point)this._obj_1!;
        }
    }
}
