// <auto-generated/>
#nullable enable

namespace Shapes
{
    public abstract partial record Shape
    {
        private Shape() { }

        public sealed partial record Circle;
        public sealed partial record Square;

        public bool IsCircle => this is Circle;
        public bool IsSquare => this is Square;
    }
}
