// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using Houtamelo.Spire;

namespace TestNs
{
    public static partial class ListExt
    {
        public static global::System.Collections.Generic.List<R> Map<T, R, TSelectorInliner>(this global::System.Collections.Generic.List<T> list, TSelectorInliner selector)
            where TSelectorInliner : struct, global::Houtamelo.Spire.IFuncInliner<T, R>
        {
            var result = new List<R>(list.Count);
            foreach (var item in list)
                result.Add(selector.Invoke(item));
            return result;
        }
    }
}
