// <auto-generated/>
#nullable enable

namespace TestNs
{
    public partial class Outer
    {
        public partial class Inner
        {
            public readonly struct DoubleInliner : global::Houtamelo.Spire.IFuncInliner<int, int>
            {
                public int Invoke(int a1) => Inner.Double(a1);
            }
        }
    }
}
