// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.Analyzers.MustBeInit]
    [StructLayout(LayoutKind.Explicit)]
    partial struct Message
    {
        public enum Kind : byte
        {
            Text,
            Error,
        }

        [FieldOffset(0)]
        public readonly Kind kind;

        [FieldOffset(8)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly string? _content;

        [FieldOffset(16)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly object? _detail;

        Message(Kind kind) : this()
        {
            this.kind = kind;
        }

        public static partial Message Text(string content)
        {
            var s = new Message(Kind.Text);
            Unsafe.AsRef(in s._content) = content;
            return s;
        }
        public static partial Message Error(object detail)
        {
            var s = new Message(Kind.Error);
            Unsafe.AsRef(in s._detail) = detail;
            return s;
        }

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.kind;
            switch (this.kind)
            {
                case Kind.Text:
                    f0 = this._content;
                    break;
                case Kind.Error:
                    f0 = this._detail;
                    break;
                default:
                    f0 = null;
                    break;
            }
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string content => this._content!;
        [EditorBrowsable(EditorBrowsableState.Never)]
        public object detail => this._detail!;
    }
}
