// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.Analyzers.MustBeInit]
    [StructLayout(LayoutKind.Explicit)]
    internal partial struct Message
    {
        public enum Kind
        {
            Text,
            Error,
        }

        [FieldOffset(0)]
        public readonly Kind tag;

        [FieldOffset(8)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public readonly string? text_content;

        [FieldOffset(8)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public readonly object? error_detail;

        Message(Kind tag) : this()
        {
            this.tag = tag;
        }

        public static partial Message Text(string content)
        {
            var s = new Message(Kind.Text);
            Unsafe.AsRef(in s.text_content) = content;
            return s;
        }
        public static partial Message Error(object detail)
        {
            var s = new Message(Kind.Error);
            Unsafe.AsRef(in s.error_detail) = detail;
            return s;
        }

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.tag;
            switch (this.tag)
            {
                case Kind.Text:
                    f0 = this.text_content;
                    break;
                case Kind.Error:
                    f0 = this.error_detail;
                    break;
                default:
                    f0 = null;
                    break;
            }
        }
    }
}
