// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.EnforceInitialization]
    [StructLayout(LayoutKind.Explicit)]
    partial struct Message : global::Spire.IDiscriminatedUnion<Message.Kind>
    {
        public enum Kind : byte
        {
            Text,
            Error,
        }

        [FieldOffset(0)]
        readonly Kind _kind;
        public Kind kind => this._kind;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [FieldOffset(8)]
        internal readonly string? _content;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [FieldOffset(16)]
        internal readonly object? _detail;

        Message(Kind kind) : this()
        {
            this._kind = kind;
        }

        public static partial Message Text(string content)
        {
            var s = new Message(Kind.Text);
            Unsafe.AsRef(in s._content) = content;
            return s;
        }
        public static partial Message Error(object detail)
        {
            var s = new Message(Kind.Error);
            Unsafe.AsRef(in s._detail) = detail;
            return s;
        }

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.kind;
            switch (this.kind)
            {
                case Kind.Text:
                    f0 = this._content;
                    break;
                case Kind.Error:
                    f0 = this._detail;
                    break;
                default:
                    f0 = null;
                    break;
            }
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string content
        {
            get => this._content!;
            init => this._content = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public object detail
        {
            get => this._detail!;
            init => this._detail = value;
        }
        public bool IsText => this.kind == Kind.Text;
        public bool IsError => this.kind == Kind.Error;
        public override string ToString()
        {
            return this.kind switch
            {
                Kind.Text => $"Text({this.content})",
                Kind.Error => $"Error({this.detail})",
                _ => "Message(?)",
            };
        }
    }
}
