// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    [global::Houtamelo.Spire.EnforceInitialization]
    internal partial struct Internal : global::Houtamelo.Spire.IDiscriminatedUnion<Internal.Kind>
    {
        public enum Kind : byte
        {
            X,
        }

        readonly Kind _kind;
        public Kind kind => this._kind;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal object? _f0 { get; init; }

        Internal(Kind kind, object? f0)
        {
            this._kind = kind;
            this._f0 = f0;
        }

        public static partial Internal X(int v)
            => new Internal(Kind.X, v);

        public void Deconstruct(out Kind kind, out int v)
        {
            kind = this.kind;
            v = (int)this._f0!;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int v
        {
            get => (int)this._f0!;
            init => this._f0 = value;
        }
        public bool IsX => this.kind == Kind.X;
        public override string ToString()
        {
            return this.kind switch
            {
                Kind.X => $"X({this.v})",
                _ => "Internal(?)",
            };
        }
    }
}
