// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;

namespace TestNs
{
    public partial class Outer
    {
        [global::Houtamelo.Spire.EnforceInitialization]
        [StructLayout(LayoutKind.Explicit)]
        internal partial struct Shape : global::Houtamelo.Spire.IDiscriminatedUnion<Shape.Kind>
        {
            public enum Kind : byte
            {
                Circle,
                Square,
            }

            [FieldOffset(0)]
            readonly Kind _kind;
            public Kind kind => this._kind;

            [EditorBrowsable(EditorBrowsableState.Never)]
            [FieldOffset(1)]
            internal readonly double _radius;

            [EditorBrowsable(EditorBrowsableState.Never)]
            [FieldOffset(9)]
            internal readonly int _sideLength;

            Shape(Kind kind) : this()
            {
                this._kind = kind;
            }

            public static partial Shape Circle(double radius)
            {
                var s = new Shape(Kind.Circle);
                Unsafe.AsRef(in s._radius) = radius;
                return s;
            }
            public static partial Shape Square(int sideLength)
            {
                var s = new Shape(Kind.Square);
                Unsafe.AsRef(in s._sideLength) = sideLength;
                return s;
            }

            public void Deconstruct(out Kind kind, out object? f0)
            {
                kind = this.kind;
                switch (this.kind)
                {
                    case Kind.Circle:
                        f0 = this._radius;
                        break;
                    case Kind.Square:
                        f0 = this._sideLength;
                        break;
                    default:
                        f0 = null;
                        break;
                }
            }
            [EditorBrowsable(EditorBrowsableState.Never)]
            public double radius
            {
                get => this._radius;
                init => this._radius = value;
            }
            [EditorBrowsable(EditorBrowsableState.Never)]
            public int sideLength
            {
                get => this._sideLength;
                init => this._sideLength = value;
            }
            public bool IsCircle => this.kind == Kind.Circle;
            public bool IsSquare => this.kind == Kind.Square;
            public override string ToString()
            {
                return this.kind switch
                {
                    Kind.Circle => $"Circle({this.radius})",
                    Kind.Square => $"Square({this.sideLength})",
                    _ => "Shape(?)",
                };
            }
        }
    }
}
