// <auto-generated/>
#nullable enable
using System.ComponentModel;

[global::Spire.Analyzers.MustBeInit]
partial struct Shape
{
    public enum Kind : byte
    {
        Circle,
        Rect,
        Square,
        Point,
    }

    public readonly Kind tag;
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal readonly double _s0;
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal readonly double _s1;

    Shape(Kind tag, double s0, double s1)
    {
        this.tag = tag;
        this._s0 = s0;
        this._s1 = s1;
    }

    public static partial Shape Circle(double radius)
        => new Shape(Kind.Circle, radius, default);
    public static partial Shape Rect(double width, double height)
        => new Shape(Kind.Rect, width, height);
    public static partial Shape Square(double side)
        => new Shape(Kind.Square, side, default);
    public static partial Shape Point()
        => new Shape(Kind.Point, default, default);

    public void Deconstruct(out Kind kind, out object? f0)
    {
        kind = this.tag;
        f0 = null;
    }

    public void Deconstruct(out Kind kind, out double width, out double height)
    {
        kind = this.tag;
        width = this._s0;
        height = this._s1;
    }
}
