// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    public static partial class Unions
    {
        [global::Houtamelo.Spire.Core.EnforceInitialization]
        internal partial struct Token : global::Houtamelo.Spire.Core.IDiscriminatedUnion<Token.Kind>
        {
            public enum Kind : byte
            {
                Ident,
                Number,
            }

            readonly Kind _kind;
            public Kind kind => this._kind;
            [EditorBrowsable(EditorBrowsableState.Never)]
            internal object? _f0 { get; init; }
            [EditorBrowsable(EditorBrowsableState.Never)]
            internal object? _f1 { get; init; }

            Token(Kind kind, object? f0, object? f1)
            {
                this._kind = kind;
                this._f0 = f0;
                this._f1 = f1;
            }

            public static partial Token Ident(string name)
                => new Token(Kind.Ident, name, null);
            public static partial Token Number(int value)
                => new Token(Kind.Number, null, value);

            public void Deconstruct(out Kind kind, out object? f0)
            {
                kind = this.kind;
                switch (this.kind)
                {
                    case Kind.Ident:
                        f0 = this._f0;
                        break;
                    case Kind.Number:
                        f0 = this._f1;
                        break;
                    default:
                        f0 = null;
                        break;
                }
            }
            [EditorBrowsable(EditorBrowsableState.Never)]
            public string name
            {
                get => (string)this._f0!;
                init => this._f0 = value;
            }
            [EditorBrowsable(EditorBrowsableState.Never)]
            public int value
            {
                get => (int)this._f1!;
                init => this._f1 = value;
            }
            public bool IsIdent => this.kind == Kind.Ident;
            public bool IsNumber => this.kind == Kind.Number;
            public override string ToString()
            {
                return this.kind switch
                {
                    Kind.Ident => $"Ident({this.name})",
                    Kind.Number => $"Number({this.value})",
                    _ => "Token(?)",
                };
            }
        }
    }
}
