// <auto-generated/>
#nullable enable

namespace TestNs
{
    [global::Spire.Analyzers.MustBeInit]
    internal partial struct Shape
    {
        public enum Kind
        {
            Circle,
            Rectangle,
            Square,
        }

        public readonly Kind tag;
        readonly object? _payload;

        Shape(Kind tag, object? payload)
        {
            this.tag = tag;
            this._payload = payload;
        }

        public static partial Shape Circle(double radius)
            => new Shape(Kind.Circle, radius);
        public static partial Shape Rectangle(float width, float height)
            => new Shape(Kind.Rectangle, (width, height));
        public static partial Shape Square(int sideLength)
            => new Shape(Kind.Square, sideLength);

        public void Deconstruct(out Kind kind, out object? payload)
        {
            kind = this.tag;
            payload = this._payload;
        }
    }
}
