// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.MustBeInit]
    partial struct Shape
    {
        public enum Kind : byte
        {
            Circle,
            Rectangle,
            Square,
        }

        public readonly Kind kind;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly object? _payload;

        Shape(Kind kind, object? payload)
        {
            this.kind = kind;
            this._payload = payload;
        }

        public static partial Shape Circle(double radius)
            => new Shape(Kind.Circle, radius);
        public static partial Shape Rectangle(float width, float height)
            => new Shape(Kind.Rectangle, (width, height));
        public static partial Shape Square(int sideLength)
            => new Shape(Kind.Square, sideLength);

        public void Deconstruct(out Kind kind, out object? payload)
        {
            kind = this.kind;
            payload = this._payload;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public double radius => (double)this._payload!;
        [EditorBrowsable(EditorBrowsableState.Never)]
        public float width => (((float, float))this._payload!).Item1;
        [EditorBrowsable(EditorBrowsableState.Never)]
        public float height => (((float, float))this._payload!).Item2;
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int sideLength => (int)this._payload!;
    }
}
