// <auto-generated/>
#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TestNs
{
    internal sealed class EventStjConverter : JsonConverter<Event>
    {
        public override Event Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            using var doc = JsonDocument.ParseValue(ref reader);
            var root = doc.RootElement;
            if (!root.TryGetProperty("kind", out var kindProp))
                throw new JsonException("Missing discriminator property 'kind'");
            var kindStr = kindProp.GetString();
            return kindStr switch
            {
                "Click" => Event.Click(root.GetProperty("x").Deserialize<int>(options)!, root.GetProperty("y").Deserialize<int>(options)!, root.GetProperty("target").Deserialize<string>(options)!),
                "Hover" => Event.Hover(root.GetProperty("posX").Deserialize<float>(options)!, root.GetProperty("posY").Deserialize<float>(options)!),
                _ => throw new JsonException($"Unknown Event variant: {kindStr}")
            };
        }

        public override void Write(Utf8JsonWriter writer, Event value, JsonSerializerOptions options)
        {
            writer.WriteStartObject();
            switch (value.tag)
            {
                case Event.Kind.Click:
                    writer.WriteString("kind", "Click");
                    writer.WritePropertyName("x");
                    JsonSerializer.Serialize(writer, value.x, options);
                    writer.WritePropertyName("y");
                    JsonSerializer.Serialize(writer, value.y, options);
                    writer.WritePropertyName("target");
                    JsonSerializer.Serialize(writer, value.target, options);
                    break;
                case Event.Kind.Hover:
                    writer.WriteString("kind", "Hover");
                    writer.WritePropertyName("posX");
                    JsonSerializer.Serialize(writer, value.posX, options);
                    writer.WritePropertyName("posY");
                    JsonSerializer.Serialize(writer, value.posY, options);
                    break;
                default:
                    throw new JsonException($"Unknown Event variant: {value.tag}");
            }
            writer.WriteEndObject();
        }
    }

    [global::System.Text.Json.Serialization.JsonConverter(typeof(EventStjConverter))]
    partial struct Event { }
}
