// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.EnforceInitialization]
    partial struct Shape : global::Spire.IDiscriminatedUnion<Shape.Kind>
    {
        public enum Kind : byte
        {
            Circle,
            Rectangle,
            Square,
        }

        readonly Kind _kind;
        public Kind kind => this._kind;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal object? _payload { get; init; }

        Shape(Kind kind, object? payload)
        {
            this._kind = kind;
            this._payload = payload;
        }

        public static partial Shape Circle(double radius)
            => new Shape(Kind.Circle, radius);
        public static partial Shape Rectangle(float width, float height)
            => new Shape(Kind.Rectangle, (width, height));
        public static partial Shape Square(int sideLength)
            => new Shape(Kind.Square, sideLength);

        public void Deconstruct(out Kind kind, out object? payload)
        {
            kind = this.kind;
            payload = this._payload;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public double radius
        {
            get => (double)this._payload!;
            init => this._payload = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public float width
        {
            get => (((float, float))this._payload!).Item1;
            init
            {
                var t = ((float, float))this._payload!;
                t.Item1 = value;
                this._payload = t;
            }
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public float height
        {
            get => (((float, float))this._payload!).Item2;
            init
            {
                var t = ((float, float))this._payload!;
                t.Item2 = value;
                this._payload = t;
            }
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int sideLength
        {
            get => (int)this._payload!;
            init => this._payload = value;
        }
        public bool IsCircle => this.kind == Kind.Circle;
        public bool IsRectangle => this.kind == Kind.Rectangle;
        public bool IsSquare => this.kind == Kind.Square;
        public override string ToString()
        {
            return this.kind switch
            {
                Kind.Circle => $"Circle({this.radius})",
                Kind.Rectangle => $"Rectangle({this.width}, {this.height})",
                Kind.Square => $"Square({this.sideLength})",
                _ => "Shape(?)",
            };
        }
    }
}
