// <auto-generated/>
#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TestNs
{
    internal sealed class OptionStjConverterFactory : JsonConverterFactory
    {
        public override bool CanConvert(Type typeToConvert)
            => typeToConvert.IsGenericType && typeToConvert.GetGenericTypeDefinition() == typeof(Option<>);

        public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)
        {
            var converterType = typeof(OptionStjConverter<>).MakeGenericType(typeToConvert.GetGenericArguments());
            return (JsonConverter)Activator.CreateInstance(converterType)!;
        }
    }

    internal sealed class OptionStjConverter<T> : JsonConverter<Option<T>>
    {
        public override Option<T> Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            using var doc = JsonDocument.ParseValue(ref reader);
            var root = doc.RootElement;
            if (!root.TryGetProperty("kind", out var kindProp))
                throw new JsonException("Missing discriminator property 'kind'");
            var kindStr = kindProp.GetString();
            return kindStr switch
            {
                "Some" => Option<T>.Some(root.GetProperty("value").Deserialize<T>(options)!),
                "None" => Option<T>.None(),
                _ => throw new JsonException($"Unknown Option variant: {kindStr}")
            };
        }

        public override void Write(Utf8JsonWriter writer, Option<T> value, JsonSerializerOptions options)
        {
            writer.WriteStartObject();
            switch (value)
            {
                case { kind: Option<T>.Kind.Some, value: var __value }:
                {
                    writer.WriteString("kind", "Some");
                    writer.WritePropertyName("value");
                    JsonSerializer.Serialize(writer, __value, options);
                    break;
                }
                case { kind: Option<T>.Kind.None }:
                {
                    writer.WriteString("kind", "None");
                    break;
                }
                default:
                    throw new JsonException($"Unknown Option variant: {value.kind}");
            }
            writer.WriteEndObject();
        }
    }

    [global::System.Text.Json.Serialization.JsonConverter(typeof(OptionStjConverterFactory))]
    partial struct Option<T> { }
}
