using System.Collections.Generic;
using System.Linq;
using Houtamelo.Spire.Analyzers.SourceGenerators.Emit;
using Houtamelo.Spire.Analyzers.SourceGenerators.Model;
using Houtamelo.Spire.Analyzers.SourceGenerators.Performance.Model;

namespace Houtamelo.Spire.Analyzers.SourceGenerators.Performance.Emit;

internal static class InlinerStructEmitter
{
    public static string Emit(InlinerStructDecl decl)
    {
        var sb = new SourceBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(decl.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {decl.Namespace}");
            sb.OpenBrace();
        }

        // Outer containing types (outermost-first, already ordered in decl).
        foreach (var ct in decl.ContainingTypes)
        {
            sb.AppendLine(OpenTypeDeclaration(ct.AccessibilityKeyword, ct.Keyword, ct.Name, ct.TypeParameters));
            sb.OpenBrace();
        }

        // Declaring type.
        sb.AppendLine(OpenTypeDeclaration(
            decl.DeclaringTypeAccessibility,
            decl.DeclaringTypeKeyword,
            decl.DeclaringTypeName,
            decl.DeclaringTypeParameters));
        sb.OpenBrace();

        // Inliner struct.
        var methodGenerics = FormatGenerics(decl.TypeParameters);
        var structName = $"{decl.MethodName}Inliner{methodGenerics}";
        var iface = BuildInterface(decl);
        sb.AppendLine($"{decl.Accessibility} readonly struct {structName} : {iface}");
        sb.OpenBrace();

        // Invoke method.
        var (invokeSignature, invokeBody) = BuildInvoke(decl);
        var returnKeyword = decl.IsVoid ? "void" : decl.ReturnType!;
        sb.AppendLine($"public {returnKeyword} Invoke({invokeSignature}) => {invokeBody};");

        sb.CloseBrace(); // inliner struct
        sb.CloseBrace(); // declaring type

        for (int i = 0; i < decl.ContainingTypes.Length; i++)
            sb.CloseBrace();

        if (hasNamespace)
            sb.CloseBrace();

        return sb.ToString();
    }

    private static string OpenTypeDeclaration(
        string accessibility,
        string keyword,
        string name,
        EquatableArray<string> typeParams)
    {
        var generics = FormatGenerics(typeParams);
        var prefix = string.IsNullOrEmpty(accessibility) ? "" : accessibility + " ";

        // "static class" requires "static partial class" ordering; everything else is "partial <keyword>".
        if (keyword == "static class")
            return $"{prefix}static partial class {name}{generics}";

        return $"{prefix}partial {keyword} {name}{generics}";
    }

    private static string FormatGenerics(EquatableArray<string> typeParams)
    {
        if (typeParams.Length == 0) return "";
        return "<" + string.Join(", ", (IEnumerable<string>)typeParams) + ">";
    }

    private static string BuildInterface(InlinerStructDecl decl)
    {
        // Determine the effective arity and the ordered list of type args.
        var paramTypes = ((IEnumerable<InlinerParamInfo>)decl.Parameters)
            .Select(p => p.Type)
            .ToList();

        // Instance methods include the declaring type as the first type arg / first Invoke parameter.
        if (!decl.IsStatic)
        {
            var declaringTypeRef = BuildDeclaringTypeFullyQualified(decl);
            paramTypes.Insert(0, declaringTypeRef);
        }

        if (decl.IsVoid)
        {
            if (paramTypes.Count == 0)
                return "global::Houtamelo.Spire.IActionInliner";
            return $"global::Houtamelo.Spire.IActionInliner<{string.Join(", ", paramTypes)}>";
        }

        // Non-void: append return type.
        var returnType = decl.ReturnType!;
        if (paramTypes.Count == 0)
            return $"global::Houtamelo.Spire.IFuncInliner<{returnType}>";

        return $"global::Houtamelo.Spire.IFuncInliner<{string.Join(", ", paramTypes)}, {returnType}>";
    }

    private static (string Signature, string Body) BuildInvoke(InlinerStructDecl decl)
    {
        var methodGenerics = FormatGenerics(decl.TypeParameters);
        var parameters = ((IEnumerable<InlinerParamInfo>)decl.Parameters).ToList();

        if (decl.IsStatic)
        {
            var paramList = string.Join(", ",
                parameters.Select((p, idx) => $"{p.Type} a{idx + 1}"));

            var argList = string.Join(", ",
                Enumerable.Range(1, parameters.Count).Select(i => $"a{i}"));

            var call = string.IsNullOrEmpty(argList)
                ? $"{decl.DeclaringTypeName}.{decl.MethodName}{methodGenerics}()"
                : $"{decl.DeclaringTypeName}.{decl.MethodName}{methodGenerics}({argList})";

            return (paramList, call);
        }
        else
        {
            var declaringTypeRef = BuildDeclaringTypeFullyQualified(decl);
            var userParams = parameters.Select((p, idx) => $"{p.Type} a{idx + 1}");
            var paramList = string.Join(", ",
                new[] { $"{declaringTypeRef} instance" }.Concat(userParams));

            var argList = string.Join(", ",
                Enumerable.Range(1, parameters.Count).Select(i => $"a{i}"));

            var call = string.IsNullOrEmpty(argList)
                ? $"instance.{decl.MethodName}{methodGenerics}()"
                : $"instance.{decl.MethodName}{methodGenerics}({argList})";

            return (paramList, call);
        }
    }

    private static string BuildDeclaringTypeFullyQualified(InlinerStructDecl decl)
    {
        var parts = new List<string>();
        if (!string.IsNullOrEmpty(decl.Namespace))
            parts.Add(decl.Namespace);

        foreach (var ct in decl.ContainingTypes)
            parts.Add(ct.Name + FormatGenerics(ct.TypeParameters));

        parts.Add(decl.DeclaringTypeName + FormatGenerics(decl.DeclaringTypeParameters));

        return "global::" + string.Join(".", parts);
    }
}
