using System.Collections.Generic;
using System.Linq;
using Houtamelo.Spire.Analyzers.SourceGenerators.Emit;
using Houtamelo.Spire.Analyzers.SourceGenerators.Model;
using Houtamelo.Spire.Analyzers.SourceGenerators.Performance.Model;

namespace Houtamelo.Spire.Analyzers.SourceGenerators.Performance.Emit;

internal static class InlinableTwinEmitter
{
    public static string Emit(InlinableHostDecl decl)
    {
        var sb = new SourceBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        foreach (var u in decl.UsingDirectives)
            sb.AppendLine(u);
        if (decl.UsingDirectives.Length > 0)
            sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(decl.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {decl.Namespace}");
            sb.OpenBrace();
        }

        // Outer containing types (outermost-first).
        foreach (var ct in decl.ContainingTypes)
        {
            sb.AppendLine(OpenTypeDeclaration(ct.AccessibilityKeyword, ct.Keyword, ct.Name, ct.TypeParameters));
            sb.OpenBrace();
        }

        // Declaring type.
        sb.AppendLine(OpenTypeDeclaration(
            decl.DeclaringTypeAccessibility,
            decl.DeclaringTypeKeyword,
            decl.DeclaringTypeName,
            decl.DeclaringTypeParameters));
        sb.OpenBrace();

        EmitTwinMethod(sb, decl);

        sb.CloseBrace(); // declaring type

        for (int i = 0; i < decl.ContainingTypes.Length; i++)
            sb.CloseBrace();

        if (hasNamespace)
            sb.CloseBrace();

        return sb.ToString();
    }

    private static void EmitTwinMethod(SourceBuilder sb, InlinableHostDecl decl)
    {
        // Assemble generics: host generics + one per inlinable param.
        var allGenerics = new List<string>();
        foreach (var g in decl.HostTypeParameters) allGenerics.Add(g);
        foreach (var p in decl.InlinableParams) allGenerics.Add(p.GenericName);

        var genericsStr = allGenerics.Count == 0 ? "" : "<" + string.Join(", ", allGenerics) + ">";

        // Build the parameter list in original positional order.
        var paramStrings = BuildParameterList(decl);
        var paramList = string.Join(", ", paramStrings);

        var staticKeyword = decl.IsStatic ? "static " : "";
        var signature = $"{decl.Accessibility} {staticKeyword}{decl.ReturnType} {decl.MethodName}{genericsStr}({paramList})";

        sb.AppendLine(signature);

        // Constraints: host constraints first, then one per inlinable param.
        foreach (var constraint in decl.HostTypeParameterConstraints)
        {
            sb.AppendLine("    " + constraint);
        }
        foreach (var p in decl.InlinableParams)
        {
            var iface = BuildInterface(p);
            sb.AppendLine($"    where {p.GenericName} : struct, {iface}");
        }

        // Body: rewritten.
        var rewritten = InlinableBodyRewriter.Rewrite(decl);
        var trimmed = rewritten.TrimStart();
        if (trimmed.StartsWith("{"))
        {
            // Block body — emit verbatim (already has braces). Normalize indentation: rely on NormalizeWhitespace at compare-time.
            EmitBlockBody(sb, rewritten);
        }
        else if (trimmed.StartsWith("=>"))
        {
            // Expression body — append directly after signature. Ensure ends with ';'.
            var line = trimmed.TrimEnd();
            if (!line.EndsWith(";")) line += ";";
            sb.AppendLine("    " + line);
        }
        else
        {
            // No body — emit empty block.
            sb.AppendLine("{ }");
        }
    }

    private static void EmitBlockBody(SourceBuilder sb, string body)
    {
        // Split into lines and emit with current indent level. SourceBuilder has
        // its own indent accumulator, so we add one extra indent for body lines.
        sb.OpenBrace();
        var lines = body.Split('\n');
        // Find the first line that is the opening brace, skip it.
        int startIndex = 0;
        for (int i = 0; i < lines.Length; i++)
        {
            if (lines[i].TrimStart().StartsWith("{"))
            {
                startIndex = i + 1;
                break;
            }
        }
        int endIndex = lines.Length;
        for (int i = lines.Length - 1; i >= 0; i--)
        {
            var t = lines[i].Trim();
            if (t == "}")
            {
                endIndex = i;
                break;
            }
        }

        for (int i = startIndex; i < endIndex; i++)
        {
            var line = lines[i].TrimEnd('\r');
            // Strip one level of common leading indentation so output has consistent indent.
            sb.AppendLine(line.TrimStart());
        }
        sb.CloseBrace();
    }

    private static List<string> BuildParameterList(InlinableHostDecl decl)
    {
        var slots = new string[decl.InlinableParams.Length + decl.OtherParams.Length];
        foreach (var ip in decl.InlinableParams)
        {
            var nullable = ip.IsNullable ? "?" : "";
            slots[ip.Position] = $"{ip.GenericName}{nullable} {ip.Name}";
        }
        foreach (var op in decl.OtherParams)
        {
            var prefix = "";
            if (op.IsThis) prefix += "this ";
            if (!string.IsNullOrEmpty(op.RefKind)) prefix += op.RefKind + " ";
            slots[op.Position] = $"{prefix}{op.Type} {op.Name}";
        }
        return slots.ToList();
    }

    private static string BuildInterface(InlinableParam p)
    {
        var typeArgs = ((IEnumerable<string>)p.DelegateTypeArguments).ToList();
        if (p.IsFunc)
        {
            // Func<TR> -> IFuncInliner<TR>; Func<T1..Tn, TR> -> IFuncInliner<T1..Tn, TR>.
            var parts = new List<string>(typeArgs) { p.ReturnType };
            return $"global::Houtamelo.Spire.IFuncInliner<{string.Join(", ", parts)}>";
        }
        // Action / Action<T1..Tn>.
        if (typeArgs.Count == 0)
            return "global::Houtamelo.Spire.IActionInliner";
        return $"global::Houtamelo.Spire.IActionInliner<{string.Join(", ", typeArgs)}>";
    }

    private static string OpenTypeDeclaration(
        string accessibility,
        string keyword,
        string name,
        EquatableArray<string> typeParams)
    {
        var generics = FormatGenerics(typeParams);
        var prefix = string.IsNullOrEmpty(accessibility) ? "" : accessibility + " ";

        if (keyword == "static class")
            return $"{prefix}static partial class {name}{generics}";
        return $"{prefix}partial {keyword} {name}{generics}";
    }

    private static string FormatGenerics(EquatableArray<string> typeParams)
    {
        if (typeParams.Length == 0) return "";
        return "<" + string.Join(", ", (IEnumerable<string>)typeParams) + ">";
    }
}
