// <auto-generated/>
#nullable enable

namespace TestNs
{
    public static partial class Samples
    {
        public readonly struct ZeroInliner : global::Houtamelo.Spire.IFuncInliner<int>
        {
            public int Invoke() => Samples.Zero();
        }
    }
}
