using System.Linq;
using Spire.SourceGenerators.Model;

namespace Spire.SourceGenerators.Emit;

internal static class BoxedFieldsEmitter
{
    public static string Emit(UnionDeclaration union)
    {
        var sb = new SourceBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(union.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {union.Namespace}");
            sb.OpenBrace();
        }

        sb.OpenContainingTypes(union.ContainingTypes);

        var typeParams = FormatTypeParams(union.TypeParameters);
        var unionType = union.TypeName + typeParams;
        var accessMod = string.IsNullOrEmpty(union.AccessibilityKeyword) ? "" : union.AccessibilityKeyword + " ";
        var readonlyMod = union.IsReadonly ? "readonly " : "";
        var refMod = union.IsRefStruct ? "ref " : "";

        sb.AppendLine("[global::Spire.Analyzers.MustBeInit]");
        sb.AppendLine($"{accessMod}{readonlyMod}{refMod}partial {union.DeclarationKeyword} {unionType}");
        sb.OpenBrace();

        // Kind enum
        EmitKindEnum(sb, union);
        sb.AppendLine();

        // Fields: tag + boxed slots
        int maxFields = MaxFieldCount(union);
        sb.AppendLine("public readonly Kind tag;");
        for (int i = 0; i < maxFields; i++)
        {
            sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
            sb.AppendLine($"internal readonly object? _f{i};");
        }
        sb.AppendLine();

        // Private constructor
        EmitConstructor(sb, union.TypeName, maxFields);
        sb.AppendLine();

        // Factory methods
        EmitFactories(sb, union, unionType, maxFields);

        // Deconstruct overloads
        if (union.GenerateDeconstruct)
            DeconstructEmitter.EmitBoxedFieldsDeconstructs(sb, union.Variants);

        sb.CloseBrace(); // type

        sb.CloseContainingTypes(union.ContainingTypes);

        if (hasNamespace)
            sb.CloseBrace(); // namespace

        return sb.ToString();
    }

    private static void EmitKindEnum(SourceBuilder sb, UnionDeclaration union)
    {
        var kindType = OverlapLayoutComputer.KindTypeName(union.Variants.Length);
        sb.AppendLine($"public enum Kind : {kindType}");
        sb.OpenBrace();
        foreach (var variant in union.Variants)
        {
            sb.AppendLine($"{variant.Name},");
        }
        sb.CloseBrace();
    }

    private static void EmitConstructor(SourceBuilder sb, string typeName, int maxFields)
    {
        var paramList = "Kind tag";
        for (int i = 0; i < maxFields; i++)
        {
            paramList += $", object? f{i}";
        }

        sb.AppendLine($"{typeName}({paramList})");
        sb.OpenBrace();
        sb.AppendLine("this.tag = tag;");
        for (int i = 0; i < maxFields; i++)
        {
            sb.AppendLine($"this._f{i} = f{i};");
        }
        sb.CloseBrace();
    }

    private static void EmitFactories(SourceBuilder sb, UnionDeclaration union, string unionType, int maxFields)
    {
        foreach (var variant in union.Variants)
        {
            var typedParams = string.Join(", ",
                variant.Fields.Select(f => $"{f.TypeFullName} {f.Name}"));

            // Build args: field values for used slots, null for unused
            var args = new string[maxFields];
            for (int i = 0; i < maxFields; i++)
            {
                args[i] = i < variant.Fields.Length ? variant.Fields[i].Name : "null";
            }

            var ctorArgs = "Kind." + variant.Name;
            if (maxFields > 0)
            {
                ctorArgs += ", " + string.Join(", ", args);
            }

            sb.AppendLine($"public static partial {unionType} {variant.Name}({typedParams})");
            sb.AppendLine($"    => new {unionType}({ctorArgs});");
        }
    }

    private static int MaxFieldCount(UnionDeclaration union)
    {
        int max = 0;
        foreach (var v in union.Variants)
        {
            if (v.Fields.Length > max)
                max = v.Fields.Length;
        }
        return max;
    }

    private static string FormatTypeParams(EquatableArray<string> typeParameters)
    {
        if (typeParameters.Length == 0) return "";
        return "<" + string.Join(", ", typeParameters) + ">";
    }
}
