using System.Linq;
using Spire.SourceGenerators.Model;

namespace Spire.SourceGenerators.Emit;

internal static class BoxedTupleEmitter
{
    public static string Emit(UnionDeclaration union)
    {
        var sb = new SourceBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(union.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {union.Namespace}");
            sb.OpenBrace();
        }

        sb.OpenContainingTypes(union.ContainingTypes);

        var typeParams = FormatTypeParams(union.TypeParameters);
        var unionType = union.TypeName + typeParams;
        var accessMod = string.IsNullOrEmpty(union.AccessibilityKeyword) ? "" : union.AccessibilityKeyword + " ";
        var readonlyMod = union.IsReadonly ? "readonly " : "";
        var refMod = union.IsRefStruct ? "ref " : "";

        sb.AppendLine("[global::Spire.Analyzers.MustBeInit]");
        sb.AppendLine($"{accessMod}{readonlyMod}{refMod}partial {union.DeclarationKeyword} {unionType}");
        sb.OpenBrace();

        // Kind enum
        EmitKindEnum(sb, union);
        sb.AppendLine();

        // Fields: tag + single payload
        sb.AppendLine("public readonly Kind tag;");
        sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
        sb.AppendLine("internal readonly object? _payload;");
        sb.AppendLine();

        // Private constructor
        EmitConstructor(sb, union.TypeName);
        sb.AppendLine();

        // Factory methods
        EmitFactories(sb, union, unionType);

        // Single Deconstruct overload
        if (union.GenerateDeconstruct)
            EmitDeconstruct(sb);

        sb.CloseBrace(); // type

        sb.CloseContainingTypes(union.ContainingTypes);

        if (hasNamespace)
            sb.CloseBrace(); // namespace

        return sb.ToString();
    }

    private static void EmitKindEnum(SourceBuilder sb, UnionDeclaration union)
    {
        var kindType = OverlapLayoutComputer.KindTypeName(union.Variants.Length);
        sb.AppendLine($"public enum Kind : {kindType}");
        sb.OpenBrace();
        foreach (var variant in union.Variants)
        {
            sb.AppendLine($"{variant.Name},");
        }
        sb.CloseBrace();
    }

    private static void EmitConstructor(SourceBuilder sb, string typeName)
    {
        sb.AppendLine($"{typeName}(Kind tag, object? payload)");
        sb.OpenBrace();
        sb.AppendLine("this.tag = tag;");
        sb.AppendLine("this._payload = payload;");
        sb.CloseBrace();
    }

    private static void EmitFactories(SourceBuilder sb, UnionDeclaration union, string unionType)
    {
        foreach (var variant in union.Variants)
        {
            var typedParams = string.Join(", ",
                variant.Fields.Select(f => $"{f.TypeFullName} {f.Name}"));

            string payloadArg;
            if (variant.Fields.Length == 0)
            {
                payloadArg = "null";
            }
            else if (variant.Fields.Length == 1)
            {
                payloadArg = variant.Fields[0].Name;
            }
            else
            {
                // Multi-field: box a ValueTuple
                var tupleElements = string.Join(", ",
                    variant.Fields.Select(f => f.Name));
                payloadArg = $"({tupleElements})";
            }

            sb.AppendLine($"public static partial {unionType} {variant.Name}({typedParams})");
            sb.AppendLine($"    => new {unionType}(Kind.{variant.Name}, {payloadArg});");
        }
    }

    private static void EmitDeconstruct(SourceBuilder sb)
    {
        sb.AppendLine();
        sb.AppendLine("public void Deconstruct(out Kind kind, out object? payload)");
        sb.OpenBrace();
        sb.AppendLine("kind = this.tag;");
        sb.AppendLine("payload = this._payload;");
        sb.CloseBrace();
    }

    private static string FormatTypeParams(EquatableArray<string> typeParameters)
    {
        if (typeParameters.Length == 0) return "";
        return "<" + string.Join(", ", typeParameters) + ">";
    }
}
