using Spire.SourceGenerators.Model;

namespace Spire.SourceGenerators.Emit;

internal static class ClassEmitter
{
    public static string Emit(UnionDeclaration union)
    {
        var sb = new SourceBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(union.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {union.Namespace}");
            sb.OpenBrace();
        }

        sb.OpenContainingTypes(union.ContainingTypes);

        var typeParams = FormatTypeParams(union.TypeParameters);
        var unionType = union.TypeName + typeParams;

        var accessMod = string.IsNullOrEmpty(union.AccessibilityKeyword) ? "" : union.AccessibilityKeyword + " ";
        sb.AppendLine($"{accessMod}abstract partial class {unionType}");
        sb.OpenBrace();

        // Private ctor prevents external subclassing
        sb.AppendLine($"private {union.TypeName}() {{ }}");
        sb.AppendLine();

        // Variant classes — just re-declare as sealed partial
        foreach (var variant in union.Variants)
        {
            var variantAccess = string.IsNullOrEmpty(variant.AccessibilityKeyword) ? "" : variant.AccessibilityKeyword + " ";
            sb.AppendLine($"{variantAccess}sealed partial class {variant.Name};");
        }

        sb.AppendLine();
        foreach (var variant in union.Variants)
            sb.AppendLine($"public bool Is{variant.Name} => this is {variant.Name};");

        sb.CloseBrace(); // type

        sb.CloseContainingTypes(union.ContainingTypes);

        if (hasNamespace)
            sb.CloseBrace(); // namespace

        return sb.ToString();
    }

    private static string FormatTypeParams(EquatableArray<string> typeParameters)
    {
        if (typeParameters.Length == 0) return "";
        return "<" + string.Join(", ", typeParameters) + ">";
    }
}
