using System.Linq;
using Spire.SourceGenerators.Model;

namespace Spire.SourceGenerators.Emit;

internal static class ClassEmitter
{
    public static string Emit(UnionDeclaration union)
    {
        var sb = new SourceBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(union.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {union.Namespace}");
            sb.OpenBrace();
        }

        var typeParams = FormatTypeParams(union.TypeParameters);
        var unionType = union.TypeName + typeParams;

        sb.AppendLine($"{union.AccessibilityKeyword} abstract partial class {unionType}");
        sb.OpenBrace();

        // Private parameterless ctor prevents external subclassing
        sb.AppendLine($"private {union.TypeName}() {{ }}");
        sb.AppendLine();

        // Variant classes — re-declare as sealed partial
        foreach (var variant in union.Variants)
        {
            sb.AppendLine($"public sealed partial class {variant.Name}");
            sb.OpenBrace();

            // Deconstruct method for variants with fields
            if (!variant.Fields.IsEmpty)
            {
                var deconstructParams = string.Join(", ", variant.Fields
                    .Select(f => $"out {f.TypeFullName} {f.Name}"));
                var deconstructBody = string.Join(" ", variant.Fields
                    .Select(f => $"{f.Name} = {ToPascalCase(f.Name)};"));
                sb.AppendLine($"public void Deconstruct({deconstructParams}) {{ {deconstructBody} }}");
            }

            sb.CloseBrace();
            sb.AppendLine();
        }

        // Factory methods
        foreach (var variant in union.Variants)
        {
            EmitFactoryMethod(sb, variant, unionType);
        }

        sb.CloseBrace(); // type

        if (hasNamespace)
            sb.CloseBrace(); // namespace

        return sb.ToString();
    }

    private static void EmitFactoryMethod(
        SourceBuilder sb, VariantInfo variant, string unionType)
    {
        if (variant.Fields.IsEmpty)
        {
            sb.AppendLine($"public static {unionType} New{variant.Name}() => new {variant.Name}();");
            return;
        }

        var paramList = string.Join(", ", variant.Fields
            .Select(f => $"{f.TypeFullName} {f.Name}"));
        var argList = string.Join(", ", variant.Fields
            .Select(f => f.Name));
        sb.AppendLine($"public static {unionType} New{variant.Name}({paramList}) => new {variant.Name}({argList});");
    }

    private static string FormatTypeParams(EquatableArray<string> typeParameters)
    {
        if (typeParameters.Length == 0) return "";
        return "<" + string.Join(", ", typeParameters) + ">";
    }

    private static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        if (char.IsUpper(name[0])) return name;
        return char.ToUpperInvariant(name[0]) + name.Substring(1);
    }
}
