using System.Text;
using Spire.SourceGenerators.Model;

namespace Spire.SourceGenerators.Emit;

/// Generates a Lazy<string> JsonSchema property for JSON-enabled discriminated unions.
/// Produces a separate .Schema.g.cs file with two tiers:
///   - Tier 1 (NET9_0_OR_GREATER + STJ): runtime schema via JsonSchemaExporter
///   - Tier 2 (fallback): compile-time string literal built from C# type → JSON Schema mapping
internal static class JsonSchemaEmitter
{
    public static string Emit(UnionDeclaration union, bool hasStj)
    {
        var sb = new SourceBuilder();
        var typeParams = FormatTypeParams(union.TypeParameters);
        var unionType = union.TypeName + typeParams;

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(union.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {union.Namespace}");
            sb.OpenBrace();
        }

        sb.OpenContainingTypes(union.ContainingTypes);

        // Partial type declaration matching the union's modifiers
        var accessMod = string.IsNullOrEmpty(union.AccessibilityKeyword) ? "" : union.AccessibilityKeyword + " ";
        var readonlyMod = union.IsReadonly ? "readonly " : "";
        var refMod = union.IsRefStruct ? "ref " : "";
        var abstractMod = IsRecordOrClass(union) ? "abstract " : "";
        sb.AppendLine($"{accessMod}{abstractMod}{readonlyMod}{refMod}partial {union.DeclarationKeyword} {unionType}");
        sb.OpenBrace();

        // Property
        sb.AppendLine("public static global::System.Lazy<string> JsonSchema { get; } = new(BuildJsonSchema);");
        sb.AppendLine();

        // Method
        sb.AppendLine("private static string BuildJsonSchema()");
        sb.OpenBrace();

        if (hasStj)
        {
            EmitRuntimeTier(sb, union);
            sb.AppendLine("#else");
            EmitCompileTimeTier(sb, union);
            sb.AppendLine("#endif");
        }
        else
        {
            EmitCompileTimeTier(sb, union);
        }

        sb.CloseBrace(); // BuildJsonSchema

        sb.CloseBrace(); // partial type

        sb.CloseContainingTypes(union.ContainingTypes);

        if (hasNamespace)
            sb.CloseBrace();

        return sb.ToString();
    }

    #region Runtime tier (STJ .NET 9+)

    private static void EmitRuntimeTier(SourceBuilder sb, UnionDeclaration union)
    {
        sb.AppendLine("#if NET9_0_OR_GREATER");
        sb.AppendLine("var options = global::System.Text.Json.JsonSerializerOptions.Default;");
        sb.AppendLine("var sb = new global::System.Text.StringBuilder();");
        sb.AppendLine("sb.Append(\"{\\\"oneOf\\\":[\");");

        bool firstVariant = true;
        foreach (var variant in union.Variants)
        {
            var jsonVariantName = variant.JsonName ?? variant.Name;

            if (!firstVariant)
                sb.AppendLine("sb.Append(\",\");");
            firstVariant = false;

            // Open variant object + properties object
            sb.AppendLine($"sb.Append(\"{{\\\"type\\\":\\\"object\\\",\\\"properties\\\":{{\\\"{ EscapeForStringLiteral(union.JsonDiscriminator) }\\\":{{\\\"const\\\":\\\"{EscapeForStringLiteral(jsonVariantName)}\\\"}}\");");

            foreach (var field in variant.Fields)
            {
                var jsonFieldName = field.JsonName ?? field.Name;
                // Emit the field schema using JsonSchemaExporter
                sb.AppendLine($"sb.Append(\",\\\"{EscapeForStringLiteral(jsonFieldName)}\\\":\");");
                sb.AppendLine($"sb.Append(global::System.Text.Json.Schema.JsonSchemaExporter.GetJsonSchemaAsNode(options, typeof({field.TypeFullName})).ToJsonString());");
            }

            // Close properties, add required array
            sb.AppendLine("sb.Append(\"},\\\"required\\\":[\\\"" + EscapeForStringLiteral(union.JsonDiscriminator) + "\\\"\");");

            foreach (var field in variant.Fields)
            {
                var jsonFieldName = field.JsonName ?? field.Name;
                sb.AppendLine($"sb.Append(\",\\\"{EscapeForStringLiteral(jsonFieldName)}\\\"\");");
            }

            sb.AppendLine("sb.Append(\"]}\");");
        }

        sb.AppendLine($"sb.Append(\"],\\\"discriminator\\\":{{\\\"propertyName\\\":\\\"{EscapeForStringLiteral(union.JsonDiscriminator)}\\\"}}}}\");");
        sb.AppendLine("return sb.ToString();");
    }

    #endregion

    #region Compile-time tier

    private static void EmitCompileTimeTier(SourceBuilder sb, UnionDeclaration union)
    {
        var schema = BuildCompileTimeSchema(union);
        // Emit as a verbatim string literal, escaping internal double-quotes as ""
        var escaped = schema.Replace("\"", "\"\"");
        sb.AppendLine($"return @\"{escaped}\";");
    }

    private static string BuildCompileTimeSchema(UnionDeclaration union)
    {
        var sb = new StringBuilder();
        sb.Append("{\"oneOf\":[");

        bool firstVariant = true;
        foreach (var variant in union.Variants)
        {
            if (!firstVariant) sb.Append(',');
            firstVariant = false;

            var jsonVariantName = variant.JsonName ?? variant.Name;

            sb.Append("{\"type\":\"object\",\"properties\":{");
            sb.Append($"\"{EscapeJsonString(union.JsonDiscriminator)}\":{{\"const\":\"{EscapeJsonString(jsonVariantName)}\"}}");

            foreach (var field in variant.Fields)
            {
                var jsonFieldName = field.JsonName ?? field.Name;
                var fieldSchema = MapTypeToJsonSchema(field.TypeFullName);
                sb.Append($",\"{EscapeJsonString(jsonFieldName)}\":{fieldSchema}");
            }

            sb.Append("},\"required\":[");
            sb.Append($"\"{EscapeJsonString(union.JsonDiscriminator)}\"");

            foreach (var field in variant.Fields)
            {
                var jsonFieldName = field.JsonName ?? field.Name;
                sb.Append($",\"{EscapeJsonString(jsonFieldName)}\"");
            }

            sb.Append("]}");
        }

        sb.Append($"],\"discriminator\":{{\"propertyName\":\"{EscapeJsonString(union.JsonDiscriminator)}\"}}}}");
        return sb.ToString();
    }

    /// Maps a C# type name (keyword alias or full name) to a JSON Schema type fragment.
    private static string MapTypeToJsonSchema(string typeName)
    {
        // Normalize — strip nullable suffix and generic wrapping for collection detection
        var normalized = typeName.TrimEnd('?');

        switch (normalized)
        {
            // Integer types
            case "int":
            case "System.Int32":
            case "long":
            case "System.Int64":
            case "short":
            case "System.Int16":
            case "byte":
            case "System.Byte":
            case "sbyte":
            case "System.SByte":
            case "ushort":
            case "System.UInt16":
            case "uint":
            case "System.UInt32":
            case "ulong":
            case "System.UInt64":
                return "{\"type\":\"integer\"}";

            // Number types
            case "float":
            case "System.Single":
            case "double":
            case "System.Double":
            case "decimal":
            case "System.Decimal":
                return "{\"type\":\"number\"}";

            // String types
            case "string":
            case "System.String":
            case "char":
            case "System.Char":
                return "{\"type\":\"string\"}";

            // Boolean
            case "bool":
            case "System.Boolean":
                return "{\"type\":\"boolean\"}";
        }

        // Array types: T[] or T?[]
        if (normalized.EndsWith("[]"))
            return "{\"type\":\"array\"}";

        // Generic collections: List<T>, IList<T>, IEnumerable<T>, etc.
        if (normalized.StartsWith("System.Collections.Generic.List<")
            || normalized.StartsWith("System.Collections.Generic.IList<")
            || normalized.StartsWith("System.Collections.Generic.IEnumerable<")
            || normalized.StartsWith("System.Collections.Generic.ICollection<")
            || normalized.StartsWith("System.Collections.Generic.IReadOnlyList<")
            || normalized.StartsWith("System.Collections.Generic.IReadOnlyCollection<")
            || normalized.StartsWith("System.Collections.Generic.HashSet<")
            || normalized.StartsWith("System.Collections.Generic.ISet<")
            || normalized.StartsWith("List<")
            || normalized.StartsWith("IList<")
            || normalized.StartsWith("IEnumerable<")
            || normalized.StartsWith("ICollection<")
            || normalized.StartsWith("IReadOnlyList<")
            || normalized.StartsWith("IReadOnlyCollection<")
            || normalized.StartsWith("HashSet<")
            || normalized.StartsWith("ISet<"))
        {
            return "{\"type\":\"array\"}";
        }

        // Nullable<T>: unwrap and map inner type
        if (normalized.StartsWith("System.Nullable<") && normalized.EndsWith(">"))
        {
            var inner = normalized.Substring("System.Nullable<".Length, normalized.Length - "System.Nullable<".Length - 1);
            return MapTypeToJsonSchema(inner);
        }
        if (normalized.StartsWith("Nullable<") && normalized.EndsWith(">"))
        {
            var inner = normalized.Substring("Nullable<".Length, normalized.Length - "Nullable<".Length - 1);
            return MapTypeToJsonSchema(inner);
        }

        // Unknown type — emit empty schema (accepts anything)
        return "{}";
    }

    #endregion

    #region Utilities

    private static bool IsRecordOrClass(UnionDeclaration union)
        => union.Strategy == EmitStrategy.Record || union.Strategy == EmitStrategy.Class;

    private static string FormatTypeParams(EquatableArray<string> typeParameters)
    {
        if (typeParameters.Length == 0) return "";
        return "<" + string.Join(", ", typeParameters) + ">";
    }

    /// Escapes a string for use inside a C# verbatim string literal's JSON content.
    /// Only JSON-level escaping needed — the verbatim string handles backslashes literally.
    private static string EscapeJsonString(string value)
    {
        // JSON strings in the compile-time schema only need quote escaping within the JSON
        // (the verbatim string's "" doubling is handled at emit time, not here)
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    /// Escapes a string for use inside a regular C# string literal (non-verbatim).
    /// Used in the runtime tier where we emit regular string literals with escaped characters.
    private static string EscapeForStringLiteral(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    #endregion
}
