using System.Linq;
using Spire.SourceGenerators.Model;

namespace Spire.SourceGenerators.Emit;

/// Generates Newtonsoft.Json JsonConverter for discriminated unions.
/// Produces a non-nested converter (and factory for generic types) as a sibling type.
internal static class NewtonsoftJsonEmitter
{
    public static string Emit(UnionDeclaration union)
    {
        var sb = new SourceBuilder();
        var isGeneric = union.TypeParameters.Length > 0;
        var typeParams = FormatTypeParams(union.TypeParameters);
        var unionType = union.TypeName + typeParams;
        var converterName = union.TypeName + "NsjConverter";
        var factoryName = union.TypeName + "NsjConverterFactory";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        if (isGeneric)
            sb.AppendLine("using System.Collections.Concurrent;");
        sb.AppendLine("using Newtonsoft.Json;");
        sb.AppendLine("using Newtonsoft.Json.Linq;");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(union.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {union.Namespace}");
            sb.OpenBrace();
        }

        sb.OpenContainingTypes(union.ContainingTypes);

        // Factory (generic types only)
        if (isGeneric)
        {
            EmitFactory(sb, union, factoryName, converterName);
            sb.AppendLine();
        }

        // Converter class
        EmitConverter(sb, union, converterName, unionType, typeParams);
        sb.AppendLine();

        // Partial type declaration with [JsonConverter] attribute
        var attrTarget = isGeneric ? factoryName : converterName;
        var accessMod = string.IsNullOrEmpty(union.AccessibilityKeyword) ? "" : union.AccessibilityKeyword + " ";
        var readonlyMod = union.IsReadonly ? "readonly " : "";
        var refMod = union.IsRefStruct ? "ref " : "";
        var abstractMod = IsRecordOrClass(union) ? "abstract " : "";
        sb.AppendLine($"[Newtonsoft.Json.JsonConverter(typeof({attrTarget}))]");
        sb.AppendLine($"{accessMod}{abstractMod}{readonlyMod}{refMod}partial {union.DeclarationKeyword} {unionType} {{ }}");

        sb.CloseContainingTypes(union.ContainingTypes);

        if (hasNamespace)
            sb.CloseBrace();

        return sb.ToString();
    }

    private static void EmitFactory(
        SourceBuilder sb, UnionDeclaration union,
        string factoryName, string converterName)
    {
        var openUnion = OpenGenericType(union.TypeName, union.TypeParameters.Length);
        var openConverter = OpenGenericType(converterName, union.TypeParameters.Length);

        sb.AppendLine($"internal sealed class {factoryName} : JsonConverter");
        sb.OpenBrace();

        sb.AppendLine("private static readonly ConcurrentDictionary<Type, JsonConverter> _cache = new();");
        sb.AppendLine();

        // CanConvert
        sb.AppendLine("public override bool CanConvert(Type objectType)");
        sb.AppendLine($"    => objectType.IsGenericType && objectType.GetGenericTypeDefinition() == typeof({openUnion});");
        sb.AppendLine();

        // ReadJson (non-generic override)
        sb.AppendLine("public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)");
        sb.OpenBrace();
        sb.AppendLine("return GetOrCreate(objectType).ReadJson(reader, objectType, existingValue, serializer);");
        sb.CloseBrace();
        sb.AppendLine();

        // WriteJson (non-generic override)
        sb.AppendLine("public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)");
        sb.OpenBrace();
        sb.AppendLine("if (value is null) { writer.WriteNull(); return; }");
        sb.AppendLine("GetOrCreate(value.GetType()).WriteJson(writer, value, serializer);");
        sb.CloseBrace();
        sb.AppendLine();

        // GetOrCreate
        sb.AppendLine("private JsonConverter GetOrCreate(Type objectType)");
        sb.OpenBrace();
        sb.AppendLine("return _cache.GetOrAdd(objectType, t =>");
        sb.OpenBrace();
        sb.AppendLine($"var converterType = typeof({openConverter}).MakeGenericType(t.GetGenericArguments());");
        sb.AppendLine("return (JsonConverter)Activator.CreateInstance(converterType)!;");
        sb.CloseBrace(");"); // lambda + GetOrAdd close
        sb.CloseBrace(); // method

        sb.CloseBrace(); // class
    }

    private static void EmitConverter(
        SourceBuilder sb, UnionDeclaration union,
        string converterName, string unionType, string typeParams)
    {
        var isRefType = IsRecordOrClass(union);
        var nullableUnion = isRefType ? $"{unionType}?" : unionType;

        sb.AppendLine($"internal sealed class {converterName}{typeParams} : JsonConverter<{unionType}>");
        sb.OpenBrace();

        // ReadJson
        EmitReadMethod(sb, union, unionType, nullableUnion);
        sb.AppendLine();

        // WriteJson
        EmitWriteMethod(sb, union, unionType, nullableUnion);

        sb.CloseBrace(); // class
    }

    #region Read

    private static void EmitReadMethod(
        SourceBuilder sb, UnionDeclaration union, string unionType, string nullableUnion)
    {
        sb.AppendLine($"public override {unionType} ReadJson(JsonReader reader, Type objectType, {nullableUnion} existingValue, bool hasExistingValue, JsonSerializer serializer)");
        sb.OpenBrace();

        sb.AppendLine("var obj = JObject.Load(reader);");
        sb.AppendLine($"var kindStr = obj[\"{union.JsonDiscriminator}\"]?.Value<string>()");
        sb.AppendLine($"    ?? throw new JsonSerializationException(\"Missing discriminator property '{union.JsonDiscriminator}'\");");
        sb.AppendLine("return kindStr switch");
        sb.OpenBrace();

        foreach (var variant in union.Variants)
        {
            var jsonName = variant.JsonName ?? variant.Name;

            if (variant.Fields.Length == 0)
            {
                var ctor = IsRecordOrClass(union)
                    ? $"new {unionType}.{variant.Name}()"
                    : $"{unionType}.{variant.Name}()";
                sb.AppendLine($"\"{jsonName}\" => {ctor},");
            }
            else
            {
                var args = string.Join(", ",
                    variant.Fields.Select(f =>
                    {
                        var propName = f.JsonName ?? f.Name;
                        return $"obj[\"{propName}\"]!.ToObject<{f.TypeFullName}>(serializer)!";
                    }));

                var ctor = IsRecordOrClass(union)
                    ? $"new {unionType}.{variant.Name}({args})"
                    : $"{unionType}.{variant.Name}({args})";
                sb.AppendLine($"\"{jsonName}\" => {ctor},");
            }
        }

        sb.AppendLine($"_ => throw new JsonSerializationException($\"Unknown {union.TypeName} variant: {{kindStr}}\")");
        sb.CloseBrace(";"); // switch expression

        sb.CloseBrace(); // method
    }

    #endregion

    #region Write

    private static void EmitWriteMethod(
        SourceBuilder sb, UnionDeclaration union, string unionType, string nullableUnion)
    {
        sb.AppendLine($"public override void WriteJson(JsonWriter writer, {nullableUnion} value, JsonSerializer serializer)");
        sb.OpenBrace();

        if (IsRecordOrClass(union))
        {
            sb.AppendLine("if (value is null) { writer.WriteNull(); return; }");
        }

        sb.AppendLine("writer.WriteStartObject();");

        if (IsRecordOrClass(union))
            EmitWriteRecordOrClass(sb, union, unionType);
        else
            EmitWriteStruct(sb, union, unionType);

        sb.AppendLine("writer.WriteEndObject();");
        sb.CloseBrace(); // method
    }

    private static void EmitWriteStruct(SourceBuilder sb, UnionDeclaration union, string unionType)
    {
        sb.AppendLine("switch (value.tag)");
        sb.OpenBrace();

        foreach (var variant in union.Variants)
        {
            var jsonVariantName = variant.JsonName ?? variant.Name;
            sb.AppendLine($"case {unionType}.Kind.{variant.Name}:");
            sb.Indent();
            sb.AppendLine($"writer.WritePropertyName(\"{union.JsonDiscriminator}\");");
            sb.AppendLine($"writer.WriteValue(\"{jsonVariantName}\");");

            EmitWriteFieldsForStructVariant(sb, union, variant);

            sb.AppendLine("break;");
            sb.Dedent();
        }

        sb.AppendLine("default:");
        sb.Indent();
        sb.AppendLine($"throw new JsonSerializationException($\"Unknown {union.TypeName} variant: {{value.tag}}\");");
        sb.Dedent();

        sb.CloseBrace(); // switch
    }

    private static void EmitWriteFieldsForStructVariant(
        SourceBuilder sb, UnionDeclaration union, VariantInfo variant)
    {
        switch (union.Strategy)
        {
            case EmitStrategy.Overlap:
                EmitWriteOverlapFields(sb, union, variant);
                break;
            case EmitStrategy.BoxedFields:
                EmitWriteBoxedFieldsFields(sb, variant);
                break;
            case EmitStrategy.BoxedTuple:
                EmitWriteBoxedTupleFields(sb, variant);
                break;
        }
    }

    private static void EmitWriteOverlapFields(
        SourceBuilder sb, UnionDeclaration union, VariantInfo variant)
    {
        var kindSize = OverlapLayoutComputer.KindSize(union.Variants.Length);
        var layout = OverlapLayoutComputer.ComputeLayout(union.Variants, kindSize);
        var vl = layout.Variants[variant.Name];

        int r3Idx = 0;
        foreach (var field in variant.Fields)
        {
            var jsonFieldName = field.JsonName ?? field.Name;
            var region = FieldClassifier.Classify(field);
            string accessExpr;

            switch (region)
            {
                case FieldRegion.Unmanaged:
                    if (vl.R1IsTuple)
                        accessExpr = $"value.{vl.R1FieldName}.{field.Name}";
                    else
                        accessExpr = $"value.{vl.R1FieldName}";
                    break;
                case FieldRegion.Reference:
                    var refFieldName = OverlapLayoutComputer.ToCamelCase(variant.Name) + "_" + field.Name;
                    accessExpr = $"value.{refFieldName}!";
                    break;
                case FieldRegion.Boxed:
                    var fp = vl.R3Fields[r3Idx];
                    accessExpr = $"({field.TypeFullName})value._obj_{fp.SlotIndex}!";
                    r3Idx++;
                    break;
                default:
                    continue;
            }

            sb.AppendLine($"writer.WritePropertyName(\"{jsonFieldName}\");");
            sb.AppendLine($"serializer.Serialize(writer, {accessExpr});");
        }
    }

    private static void EmitWriteBoxedFieldsFields(SourceBuilder sb, VariantInfo variant)
    {
        for (int i = 0; i < variant.Fields.Length; i++)
        {
            var field = variant.Fields[i];
            var jsonFieldName = field.JsonName ?? field.Name;
            sb.AppendLine($"writer.WritePropertyName(\"{jsonFieldName}\");");
            sb.AppendLine($"serializer.Serialize(writer, ({field.TypeFullName})value._f{i}!);");
        }
    }

    private static void EmitWriteBoxedTupleFields(SourceBuilder sb, VariantInfo variant)
    {
        if (variant.Fields.Length == 0)
            return;

        if (variant.Fields.Length == 1)
        {
            var field = variant.Fields[0];
            var jsonFieldName = field.JsonName ?? field.Name;
            sb.AppendLine($"writer.WritePropertyName(\"{jsonFieldName}\");");
            sb.AppendLine($"serializer.Serialize(writer, ({field.TypeFullName})value._payload!);");
            return;
        }

        var tupleType = "(" + string.Join(", ",
            variant.Fields.Select(f => f.TypeFullName)) + ")";
        sb.AppendLine($"var _tuple = ({tupleType})value._payload!;");
        for (int i = 0; i < variant.Fields.Length; i++)
        {
            var field = variant.Fields[i];
            var jsonFieldName = field.JsonName ?? field.Name;
            sb.AppendLine($"writer.WritePropertyName(\"{jsonFieldName}\");");
            sb.AppendLine($"serializer.Serialize(writer, _tuple.Item{i + 1});");
        }
    }

    private static void EmitWriteRecordOrClass(
        SourceBuilder sb, UnionDeclaration union, string unionType)
    {
        sb.AppendLine("switch (value)");
        sb.OpenBrace();

        foreach (var variant in union.Variants)
        {
            var jsonVariantName = variant.JsonName ?? variant.Name;

            if (variant.Fields.Length == 0)
            {
                sb.AppendLine($"case {unionType}.{variant.Name}:");
                sb.Indent();
                sb.AppendLine($"writer.WritePropertyName(\"{union.JsonDiscriminator}\");");
                sb.AppendLine($"writer.WriteValue(\"{jsonVariantName}\");");
                sb.AppendLine("break;");
                sb.Dedent();
            }
            else
            {
                sb.AppendLine($"case {unionType}.{variant.Name} _v:");
                sb.Indent();
                sb.AppendLine($"writer.WritePropertyName(\"{union.JsonDiscriminator}\");");
                sb.AppendLine($"writer.WriteValue(\"{jsonVariantName}\");");

                foreach (var field in variant.Fields)
                {
                    var jsonFieldName = field.JsonName ?? field.Name;
                    sb.AppendLine($"writer.WritePropertyName(\"{jsonFieldName}\");");
                    sb.AppendLine($"serializer.Serialize(writer, _v.{field.Name});");
                }

                sb.AppendLine("break;");
                sb.Dedent();
            }
        }

        sb.AppendLine("default:");
        sb.Indent();
        sb.AppendLine($"throw new JsonSerializationException($\"Unknown {union.TypeName} variant: {{value}}\");");
        sb.Dedent();

        sb.CloseBrace(); // switch
    }

    #endregion

    #region Utilities

    private static bool IsRecordOrClass(UnionDeclaration union)
        => union.Strategy == EmitStrategy.Record || union.Strategy == EmitStrategy.Class;

    private static string FormatTypeParams(EquatableArray<string> typeParameters)
    {
        if (typeParameters.Length == 0) return "";
        return "<" + string.Join(", ", typeParameters) + ">";
    }

    private static string OpenGenericType(string typeName, int arity)
    {
        if (arity == 0) return typeName;
        return typeName + "<" + new string(',', arity - 1) + ">";
    }

    #endregion
}
