using System.Collections.Generic;
using System.Linq;
using Spire.SourceGenerators.Model;

namespace Spire.SourceGenerators.Emit;

internal static class OverlapEmitter
{
    public static string Emit(UnionDeclaration union)
    {
        var sb = new SourceBuilder();
        var kindSize = OverlapLayoutComputer.KindSize(union.Variants.Length);
        var layout = OverlapLayoutComputer.ComputeLayout(
            union.Variants, kindSize);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(union.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {union.Namespace}");
            sb.OpenBrace();
        }

        sb.OpenContainingTypes(union.ContainingTypes);

        var accessMod = string.IsNullOrEmpty(union.AccessibilityKeyword) ? "" : union.AccessibilityKeyword + " ";
        var readonlyMod = union.IsReadonly ? "readonly " : "";
        var refMod = union.IsRefStruct ? "ref " : "";

        sb.AppendLine("[global::Spire.MustBeInit]");
        sb.AppendLine($"[StructLayout(LayoutKind.Explicit)]");
        sb.AppendLine($"{accessMod}{readonlyMod}{refMod}partial {union.DeclarationKeyword} {union.TypeName}");
        sb.OpenBrace();

        EmitKindEnum(sb, union);
        sb.AppendLine();

        // Kind field at offset 0
        sb.AppendLine("[FieldOffset(0)]");
        sb.AppendLine("public readonly Kind kind;");
        sb.AppendLine();

        EmitGlobalFields(sb, layout);
        EmitGlobalConstructor(sb, union.TypeName);
        sb.AppendLine();
        EmitGlobalFactories(sb, union, layout);
        if (union.GenerateDeconstruct)
            EmitGlobalDeconstructs(sb, union.Variants, layout);
        EmitProperties(sb, layout);

        sb.CloseBrace(); // type

        sb.CloseContainingTypes(union.ContainingTypes);

        if (hasNamespace)
            sb.CloseBrace(); // namespace

        return sb.ToString();
    }

    private static void EmitKindEnum(SourceBuilder sb, UnionDeclaration union)
    {
        var kindType = OverlapLayoutComputer.KindTypeName(union.Variants.Length);
        sb.AppendLine($"public enum Kind : {kindType}");
        sb.OpenBrace();
        foreach (var variant in union.Variants)
            sb.AppendLine($"{variant.Name},");
        sb.CloseBrace();
    }

    private static void EmitGlobalFields(SourceBuilder sb, OverlapLayoutInfo layout)
    {
        foreach (var gf in layout.GlobalR1)
        {
            sb.AppendLine($"[FieldOffset({gf.Offset})]");
            sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
            sb.AppendLine($"internal readonly {gf.TypeFullName} _{gf.Name};");
            sb.AppendLine();
        }

        foreach (var gf in layout.GlobalR2)
        {
            int offset = layout.R2Offset + gf.Offset * 8;
            sb.AppendLine($"[FieldOffset({offset})]");
            sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
            sb.AppendLine($"internal readonly {gf.TypeFullName}? _{gf.Name};");
            sb.AppendLine();
        }

        foreach (var gf in layout.GlobalR3)
        {
            int offset = layout.R3Offset + gf.Offset * 8;
            sb.AppendLine($"[FieldOffset({offset})]");
            sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
            sb.AppendLine($"internal readonly object? _obj_{gf.Name};");
            sb.AppendLine();
        }
    }

    private static void EmitGlobalConstructor(SourceBuilder sb, string typeName)
    {
        sb.AppendLine($"{typeName}(Kind kind) : this()");
        sb.OpenBrace();
        sb.AppendLine("this.kind = kind;");
        sb.CloseBrace();
    }

    private static void EmitGlobalFactories(
        SourceBuilder sb, UnionDeclaration union, OverlapLayoutInfo layout)
    {
        foreach (var variant in union.Variants)
        {
            var vl = layout.Variants[variant.Name];
            var typedParams = string.Join(", ",
                variant.Fields.Select(f => $"{f.TypeFullName} {f.Name}"));

            bool hasFields = variant.Fields.Length > 0;

            if (!hasFields)
            {
                sb.AppendLine($"public static partial {union.TypeName} {variant.Name}()");
                sb.AppendLine($"    => new {union.TypeName}(Kind.{variant.Name});");
                continue;
            }

            sb.AppendLine($"public static partial {union.TypeName} {variant.Name}({typedParams})");
            sb.OpenBrace();
            sb.AppendLine($"var s = new {union.TypeName}(Kind.{variant.Name});");

            foreach (var fp in vl.R1Fields)
                sb.AppendLine($"Unsafe.AsRef(in s._{fp.Field.Name}) = {fp.Field.Name};");

            foreach (var fp in vl.R2Fields)
                sb.AppendLine($"Unsafe.AsRef(in s._{fp.Field.Name}) = {fp.Field.Name};");

            foreach (var fp in vl.R3Fields)
                sb.AppendLine($"Unsafe.AsRef(in s._obj_{fp.Field.Name}) = {fp.Field.Name};");

            sb.AppendLine("return s;");
            sb.CloseBrace();
        }
    }

    private static void EmitProperties(SourceBuilder sb, OverlapLayoutInfo layout)
    {
        foreach (var gf in layout.GlobalR1)
        {
            sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
            sb.AppendLine($"public {gf.TypeFullName} {gf.Name} => this._{gf.Name};");
        }
        foreach (var gf in layout.GlobalR2)
        {
            sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
            sb.AppendLine($"public {gf.TypeFullName} {gf.Name} => this._{gf.Name}!;");
        }
        foreach (var gf in layout.GlobalR3)
        {
            sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
            sb.AppendLine($"public {gf.TypeFullName} {gf.Name} => ({gf.TypeFullName})this._obj_{gf.Name}!;");
        }
    }

    private static void EmitGlobalDeconstructs(
        SourceBuilder sb, IEnumerable<VariantInfo> variants, OverlapLayoutInfo layout)
    {
        var variantList = variants.ToList();
        if (variantList.Count == 0) return;

        var groups = GroupByFieldCount(variantList);
        var hasFieldlessVariants = groups.ContainsKey(0);

        if (groups.Count == 1 && hasFieldlessVariants)
        {
            sb.AppendLine();
            sb.AppendLine("public void Deconstruct(out Kind kind, out object? _f0)");
            sb.OpenBrace();
            sb.AppendLine("kind = this.kind;");
            sb.AppendLine("_f0 = null;");
            sb.CloseBrace();
            return;
        }

        var nonZeroGroups = groups
            .Where(g => g.Key > 0)
            .OrderBy(g => g.Key)
            .ToList();

        if (hasFieldlessVariants && nonZeroGroups.Count > 0)
        {
            var smallest = nonZeroGroups[0];
            if (smallest.Value.Count == 1)
                smallest.Value.AddRange(groups[0]);
        }

        foreach (var group in nonZeroGroups)
        {
            var groupVariants = group.Value;
            sb.AppendLine();

            if (groupVariants.Count == 1)
                EmitGlobalTypedDeconstruct(sb, groupVariants[0], layout);
            else
                EmitGlobalObjectDeconstruct(sb, group.Key, groupVariants, layout);
        }
    }

    private static void EmitGlobalTypedDeconstruct(
        SourceBuilder sb, VariantInfo variant, OverlapLayoutInfo layout)
    {
        var vl = layout.Variants[variant.Name];
        var paramList = "out Kind kind";
        foreach (var field in variant.Fields)
            paramList += $", out {field.TypeFullName} {field.Name}";

        sb.AppendLine($"public void Deconstruct({paramList})");
        sb.OpenBrace();
        sb.AppendLine("kind = this.kind;");

        foreach (var field in variant.Fields)
        {
            var region = FieldClassifier.Classify(field);
            switch (region)
            {
                case FieldRegion.Unmanaged:
                    sb.AppendLine($"{field.Name} = this._{field.Name};");
                    break;
                case FieldRegion.Reference:
                    sb.AppendLine($"{field.Name} = this._{field.Name}!;");
                    break;
                case FieldRegion.Boxed:
                    sb.AppendLine($"{field.Name} = ({field.TypeFullName})this._obj_{field.Name}!;");
                    break;
            }
        }

        sb.CloseBrace();
    }

    private static void EmitGlobalObjectDeconstruct(
        SourceBuilder sb, int fieldCount, List<VariantInfo> groupVariants, OverlapLayoutInfo layout)
    {
        var paramList = "out Kind kind";
        for (int i = 0; i < fieldCount; i++)
            paramList += $", out object? f{i}";

        sb.AppendLine($"public void Deconstruct({paramList})");
        sb.OpenBrace();
        sb.AppendLine("kind = this.kind;");

        sb.AppendLine("switch (this.kind)");
        sb.OpenBrace();

        foreach (var variant in groupVariants)
        {
            if (variant.Fields.Length == 0) continue;

            sb.AppendLine($"case Kind.{variant.Name}:");
            sb.Indent();

            int fieldIdx = 0;
            foreach (var field in variant.Fields)
            {
                var region = FieldClassifier.Classify(field);
                switch (region)
                {
                    case FieldRegion.Unmanaged:
                        sb.AppendLine($"f{fieldIdx} = this._{field.Name};");
                        break;
                    case FieldRegion.Reference:
                        sb.AppendLine($"f{fieldIdx} = this._{field.Name};");
                        break;
                    case FieldRegion.Boxed:
                        sb.AppendLine($"f{fieldIdx} = this._obj_{field.Name};");
                        break;
                }
                fieldIdx++;
            }

            sb.AppendLine("break;");
            sb.Dedent();
        }

        sb.AppendLine("default:");
        sb.Indent();
        for (int i = 0; i < fieldCount; i++)
            sb.AppendLine($"f{i} = null;");
        sb.AppendLine("break;");
        sb.Dedent();

        sb.CloseBrace(); // switch
        sb.CloseBrace(); // method
    }

    private static Dictionary<int, List<VariantInfo>> GroupByFieldCount(List<VariantInfo> variants)
    {
        var groups = new Dictionary<int, List<VariantInfo>>();
        foreach (var v in variants)
        {
            int count = v.Fields.Length;
            if (!groups.TryGetValue(count, out var list))
            {
                list = new List<VariantInfo>();
                groups[count] = list;
            }
            list.Add(v);
        }
        return groups;
    }
}
