using System;
using System.Collections.Generic;
using System.Linq;
using Spire.SourceGenerators.Model;

namespace Spire.SourceGenerators.Emit;

internal static class OverlapEmitter
{
    private const int KindSize = 4; // int-backed enum

    public static string Emit(UnionDeclaration union)
    {
        var sb = new SourceBuilder();
        var layout = ComputeLayout(union.Variants);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(union.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {union.Namespace}");
            sb.OpenBrace();
        }

        sb.OpenContainingTypes(union.ContainingTypes);

        var readonlyMod = union.IsReadonly ? "readonly " : "";

        sb.AppendLine("[global::Spire.Analyzers.MustBeInit]");
        sb.AppendLine($"[StructLayout(LayoutKind.Explicit)]");
        sb.AppendLine($"{union.AccessibilityKeyword} {readonlyMod}partial {union.DeclarationKeyword} {union.TypeName}");
        sb.OpenBrace();

        EmitKindEnum(sb, union);
        sb.AppendLine();

        // Tag field at offset 0
        sb.AppendLine("[FieldOffset(0)]");
        sb.AppendLine("public readonly Kind tag;");
        sb.AppendLine();

        // Region 1: overlapping unmanaged fields
        EmitRegion1Fields(sb, union.Variants, layout);

        // Region 2: overlapping reference fields
        EmitRegion2Fields(sb, union.Variants, layout);

        // Region 3: boxed object? slots
        EmitRegion3Fields(sb, layout);

        // Private constructor
        sb.AppendLine($"{union.TypeName}(Kind tag) : this()");
        sb.OpenBrace();
        sb.AppendLine("this.tag = tag;");
        sb.CloseBrace();
        sb.AppendLine();

        // Factory methods
        EmitFactories(sb, union, layout);

        // Deconstruct overloads
        EmitDeconstructs(sb, union.Variants, layout);

        sb.CloseBrace(); // type

        sb.CloseContainingTypes(union.ContainingTypes);

        if (hasNamespace)
            sb.CloseBrace(); // namespace

        return sb.ToString();
    }

    private static void EmitKindEnum(SourceBuilder sb, UnionDeclaration union)
    {
        sb.AppendLine("public enum Kind");
        sb.OpenBrace();
        foreach (var variant in union.Variants)
        {
            sb.AppendLine($"{variant.Name},");
        }
        sb.CloseBrace();
    }

    #region Layout computation

    private sealed class OverlapLayout
    {
        public int R1Size;
        public int R2Offset;
        public int R2Slots;
        public int R3Offset;
        public int R3Slots;

        /// Per-variant field placements
        public Dictionary<string, VariantLayout> Variants = new Dictionary<string, VariantLayout>();
    }

    private sealed class VariantLayout
    {
        public List<FieldPlacement> R1Fields = new List<FieldPlacement>();
        public List<FieldPlacement> R2Fields = new List<FieldPlacement>();
        public List<FieldPlacement> R3Fields = new List<FieldPlacement>();

        /// If there are multiple R1 fields, they are stored as a single ValueTuple
        public bool R1IsTuple;
        /// The name of the R1 tuple field (variantCamelCase), or the single field name
        public string R1FieldName = "";
    }

    private sealed class FieldPlacement
    {
        public FieldInfo Field = null!;
        public int SlotIndex; // For R2/R3: which slot index this field uses
    }

    private static OverlapLayout ComputeLayout(IEnumerable<VariantInfo> variants)
    {
        var layout = new OverlapLayout();
        var variantList = variants.ToList();

        int maxR1Size = 0;
        int maxR2Slots = 0;
        int maxR3Slots = 0;

        foreach (var variant in variantList)
        {
            var vl = new VariantLayout();
            int r2Count = 0;
            int r3Count = 0;

            foreach (var field in variant.Fields)
            {
                var region = FieldClassifier.Classify(field);
                switch (region)
                {
                    case FieldRegion.Unmanaged:
                        vl.R1Fields.Add(new FieldPlacement { Field = field, SlotIndex = 0 });
                        break;
                    case FieldRegion.Reference:
                        vl.R2Fields.Add(new FieldPlacement { Field = field, SlotIndex = r2Count++ });
                        break;
                    case FieldRegion.Boxed:
                        vl.R3Fields.Add(new FieldPlacement { Field = field, SlotIndex = r3Count++ });
                        break;
                }
            }

            // Compute R1 size for this variant
            int r1Size;
            if (vl.R1Fields.Count == 0)
            {
                r1Size = 0;
                vl.R1IsTuple = false;
                vl.R1FieldName = "";
            }
            else if (vl.R1Fields.Count == 1)
            {
                r1Size = vl.R1Fields[0].Field.KnownSize!.Value;
                vl.R1IsTuple = false;
                vl.R1FieldName = ToCamelCase(variant.Name) + "_" + vl.R1Fields[0].Field.Name;
            }
            else
            {
                r1Size = 0;
                foreach (var fp in vl.R1Fields)
                    r1Size += fp.Field.KnownSize!.Value;
                vl.R1IsTuple = true;
                vl.R1FieldName = ToCamelCase(variant.Name);
            }

            if (r1Size > maxR1Size) maxR1Size = r1Size;
            if (r2Count > maxR2Slots) maxR2Slots = r2Count;
            if (r3Count > maxR3Slots) maxR3Slots = r3Count;

            layout.Variants[variant.Name] = vl;
        }

        layout.R1Size = maxR1Size;
        layout.R2Offset = AlignUp(KindSize + maxR1Size, 8);
        layout.R2Slots = maxR2Slots;
        layout.R3Offset = layout.R2Offset + maxR2Slots * 8;
        layout.R3Slots = maxR3Slots;

        return layout;
    }

    private static int AlignUp(int value, int alignment)
    {
        return (value + alignment - 1) / alignment * alignment;
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    #endregion

    #region Field emission

    private static void EmitRegion1Fields(SourceBuilder sb, IEnumerable<VariantInfo> variants, OverlapLayout layout)
    {
        bool emitted = false;
        foreach (var variant in variants)
        {
            var vl = layout.Variants[variant.Name];
            if (vl.R1Fields.Count == 0) continue;

            emitted = true;
            int offset = KindSize;

            if (vl.R1IsTuple)
            {
                // ValueTuple field
                var tupleType = "(" + string.Join(", ",
                    vl.R1Fields.Select(fp => $"{fp.Field.TypeFullName} {fp.Field.Name}")) + ")";
                sb.AppendLine($"[FieldOffset({offset})]");
                sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
                sb.AppendLine($"public readonly {tupleType} {vl.R1FieldName};");
                sb.AppendLine();
            }
            else
            {
                // Single typed field
                var fp = vl.R1Fields[0];
                sb.AppendLine($"[FieldOffset({offset})]");
                sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
                sb.AppendLine($"public readonly {fp.Field.TypeFullName} {vl.R1FieldName};");
                sb.AppendLine();
            }
        }

        if (!emitted) return;
    }

    private static void EmitRegion2Fields(SourceBuilder sb, IEnumerable<VariantInfo> variants, OverlapLayout layout)
    {
        if (layout.R2Slots == 0) return;

        foreach (var variant in variants)
        {
            var vl = layout.Variants[variant.Name];
            foreach (var fp in vl.R2Fields)
            {
                int offset = layout.R2Offset + fp.SlotIndex * 8;
                string fieldName = ToCamelCase(variant.Name) + "_" + fp.Field.Name;
                // Reference fields are nullable in the overlap
                sb.AppendLine($"[FieldOffset({offset})]");
                sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
                sb.AppendLine($"public readonly {fp.Field.TypeFullName}? {fieldName};");
                sb.AppendLine();
            }
        }
    }

    private static void EmitRegion3Fields(SourceBuilder sb, OverlapLayout layout)
    {
        if (layout.R3Slots == 0) return;

        for (int i = 0; i < layout.R3Slots; i++)
        {
            int offset = layout.R3Offset + i * 8;
            sb.AppendLine($"[FieldOffset({offset})]");
            sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
            sb.AppendLine($"readonly object? _obj_{i};");
            sb.AppendLine();
        }
    }

    #endregion

    #region Factory methods

    private static void EmitFactories(SourceBuilder sb, UnionDeclaration union, OverlapLayout layout)
    {
        foreach (var variant in union.Variants)
        {
            var vl = layout.Variants[variant.Name];

            var typedParams = string.Join(", ",
                variant.Fields.Select(f => $"{f.TypeFullName} {f.Name}"));

            sb.AppendLine($"public static partial {union.TypeName} {variant.Name}({typedParams})");
            sb.OpenBrace();
            sb.AppendLine($"var s = new {union.TypeName}(Kind.{variant.Name});");

            // R1 assignments
            if (vl.R1Fields.Count == 1)
            {
                sb.AppendLine($"Unsafe.AsRef(in s.{vl.R1FieldName}) = {vl.R1Fields[0].Field.Name};");
            }
            else if (vl.R1Fields.Count > 1)
            {
                var tupleArgs = string.Join(", ", vl.R1Fields.Select(fp => fp.Field.Name));
                sb.AppendLine($"Unsafe.AsRef(in s.{vl.R1FieldName}) = ({tupleArgs});");
            }

            // R2 assignments
            foreach (var fp in vl.R2Fields)
            {
                string fieldName = ToCamelCase(variant.Name) + "_" + fp.Field.Name;
                sb.AppendLine($"Unsafe.AsRef(in s.{fieldName}) = {fp.Field.Name};");
            }

            // R3 assignments
            foreach (var fp in vl.R3Fields)
            {
                sb.AppendLine($"Unsafe.AsRef(in s._obj_{fp.SlotIndex}) = {fp.Field.Name};");
            }

            sb.AppendLine("return s;");
            sb.CloseBrace();
        }
    }

    #endregion

    #region Deconstruct

    private static void EmitDeconstructs(SourceBuilder sb, IEnumerable<VariantInfo> variants, OverlapLayout layout)
    {
        var variantList = variants.ToList();
        if (variantList.Count == 0) return;

        var groups = GroupByFieldCount(variantList);
        var hasFieldlessVariants = groups.ContainsKey(0);

        // If all variants are fieldless, emit a single (out Kind, out object?) that returns null.
        if (groups.Count == 1 && hasFieldlessVariants)
        {
            sb.AppendLine();
            sb.AppendLine("public void Deconstruct(out Kind kind, out object? _f0)");
            sb.OpenBrace();
            sb.AppendLine("kind = this.tag;");
            sb.AppendLine("_f0 = null;");
            sb.CloseBrace();
            return;
        }

        var nonZeroGroups = groups
            .Where(g => g.Key > 0)
            .OrderBy(g => g.Key)
            .ToList();

        // Merge fieldless variants into smallest non-zero group to force shared arity
        if (hasFieldlessVariants && nonZeroGroups.Count > 0)
        {
            var smallest = nonZeroGroups[0];
            if (smallest.Value.Count == 1)
            {
                smallest.Value.AddRange(groups[0]);
            }
        }

        foreach (var group in nonZeroGroups)
        {
            int fieldCount = group.Key;
            var groupVariants = group.Value;

            sb.AppendLine();

            if (groupVariants.Count == 1)
            {
                EmitTypedDeconstruct(sb, groupVariants[0], layout);
            }
            else
            {
                EmitObjectDeconstruct(sb, fieldCount, groupVariants, layout);
            }
        }
    }

    private static void EmitTypedDeconstruct(SourceBuilder sb, VariantInfo variant, OverlapLayout layout)
    {
        var vl = layout.Variants[variant.Name];

        var paramList = "out Kind kind";
        foreach (var field in variant.Fields)
            paramList += $", out {field.TypeFullName} {field.Name}";

        sb.AppendLine($"public void Deconstruct({paramList})");
        sb.OpenBrace();
        sb.AppendLine("kind = this.tag;");

        // Read fields from their actual locations
        foreach (var field in variant.Fields)
        {
            var region = FieldClassifier.Classify(field);
            switch (region)
            {
                case FieldRegion.Unmanaged:
                    if (vl.R1IsTuple)
                    {
                        sb.AppendLine($"{field.Name} = this.{vl.R1FieldName}.{field.Name};");
                    }
                    else
                    {
                        sb.AppendLine($"{field.Name} = this.{vl.R1FieldName};");
                    }
                    break;
                case FieldRegion.Reference:
                    string refFieldName = ToCamelCase(variant.Name) + "_" + field.Name;
                    sb.AppendLine($"{field.Name} = this.{refFieldName}!;");
                    break;
                case FieldRegion.Boxed:
                    var fp = vl.R3Fields.First(p => p.Field.Name == field.Name);
                    sb.AppendLine($"{field.Name} = ({field.TypeFullName})this._obj_{fp.SlotIndex}!;");
                    break;
            }
        }

        sb.CloseBrace();
    }

    private static void EmitObjectDeconstruct(SourceBuilder sb, int fieldCount,
        List<VariantInfo> groupVariants, OverlapLayout layout)
    {
        var paramList = "out Kind kind";
        for (int i = 0; i < fieldCount; i++)
            paramList += $", out object? f{i}";

        sb.AppendLine($"public void Deconstruct({paramList})");
        sb.OpenBrace();
        sb.AppendLine("kind = this.tag;");

        sb.AppendLine("switch (this.tag)");
        sb.OpenBrace();

        // Only emit cases for variants that actually have fields (skip fieldless ones)
        foreach (var variant in groupVariants)
        {
            if (variant.Fields.Length == 0) continue;

            var vl = layout.Variants[variant.Name];
            sb.AppendLine($"case Kind.{variant.Name}:");
            sb.Indent();

            int fieldIdx = 0;
            foreach (var field in variant.Fields)
            {
                var region = FieldClassifier.Classify(field);
                switch (region)
                {
                    case FieldRegion.Unmanaged:
                        if (vl.R1IsTuple)
                            sb.AppendLine($"f{fieldIdx} = this.{vl.R1FieldName}.{field.Name};");
                        else
                            sb.AppendLine($"f{fieldIdx} = this.{vl.R1FieldName};");
                        break;
                    case FieldRegion.Reference:
                        string refFieldName = ToCamelCase(variant.Name) + "_" + field.Name;
                        sb.AppendLine($"f{fieldIdx} = this.{refFieldName};");
                        break;
                    case FieldRegion.Boxed:
                        var fp = vl.R3Fields.First(p => p.Field.Name == field.Name);
                        sb.AppendLine($"f{fieldIdx} = this._obj_{fp.SlotIndex};");
                        break;
                }
                fieldIdx++;
            }

            sb.AppendLine("break;");
            sb.Dedent();
        }

        sb.AppendLine("default:");
        sb.Indent();
        for (int i = 0; i < fieldCount; i++)
            sb.AppendLine($"f{i} = null;");
        sb.AppendLine("break;");
        sb.Dedent();

        sb.CloseBrace(); // switch

        sb.CloseBrace(); // method
    }

    private static Dictionary<int, List<VariantInfo>> GroupByFieldCount(List<VariantInfo> variants)
    {
        var groups = new Dictionary<int, List<VariantInfo>>();
        foreach (var v in variants)
        {
            int count = v.Fields.Length;
            if (!groups.TryGetValue(count, out var list))
            {
                list = new List<VariantInfo>();
                groups[count] = list;
            }
            list.Add(v);
        }
        return groups;
    }

    #endregion
}
