using System.Linq;
using Spire.SourceGenerators.Model;

namespace Spire.SourceGenerators.Emit;

/// Generates System.Text.Json JsonConverter for discriminated unions.
/// Produces a non-nested converter (and factory for generic types) as a sibling type.
internal static class SystemTextJsonEmitter
{
    public static string Emit(UnionDeclaration union)
    {
        var sb = new SourceBuilder();
        var isGeneric = union.TypeParameters.Length > 0;
        var typeParams = FormatTypeParams(union.TypeParameters);
        var unionType = union.TypeName + typeParams;
        var converterName = union.TypeName + "StjConverter";
        var factoryName = union.TypeName + "StjConverterFactory";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(union.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {union.Namespace}");
            sb.OpenBrace();
        }

        sb.OpenContainingTypes(union.ContainingTypes);

        // Factory (generic types only)
        if (isGeneric)
        {
            EmitFactory(sb, union, factoryName, converterName);
            sb.AppendLine();
        }

        // Converter class
        EmitConverter(sb, union, converterName, unionType, typeParams);
        sb.AppendLine();

        // Partial type declaration with [JsonConverter] attribute
        var attrTarget = isGeneric ? factoryName : converterName;
        var accessMod = string.IsNullOrEmpty(union.AccessibilityKeyword) ? "" : union.AccessibilityKeyword + " ";
        var readonlyMod = union.IsReadonly ? "readonly " : "";
        var refMod = union.IsRefStruct ? "ref " : "";
        var abstractMod = IsRecordOrClass(union) ? "abstract " : "";
        sb.AppendLine($"[global::System.Text.Json.Serialization.JsonConverter(typeof({attrTarget}))]");
        sb.AppendLine($"{accessMod}{abstractMod}{readonlyMod}{refMod}partial {union.DeclarationKeyword} {unionType} {{ }}");

        sb.CloseContainingTypes(union.ContainingTypes);

        if (hasNamespace)
            sb.CloseBrace();

        return sb.ToString();
    }

    private static void EmitFactory(
        SourceBuilder sb, UnionDeclaration union,
        string factoryName, string converterName)
    {
        var openUnion = OpenGenericType(union.TypeName, union.TypeParameters.Length);
        var openConverter = OpenGenericType(converterName, union.TypeParameters.Length);

        sb.AppendLine($"internal sealed class {factoryName} : JsonConverterFactory");
        sb.OpenBrace();

        // CanConvert
        sb.AppendLine("public override bool CanConvert(Type typeToConvert)");
        sb.AppendLine($"    => typeToConvert.IsGenericType && typeToConvert.GetGenericTypeDefinition() == typeof({openUnion});");
        sb.AppendLine();

        // CreateConverter
        sb.AppendLine("public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)");
        sb.OpenBrace();
        sb.AppendLine($"var converterType = typeof({openConverter}).MakeGenericType(typeToConvert.GetGenericArguments());");
        sb.AppendLine("return (JsonConverter)Activator.CreateInstance(converterType)!;");
        sb.CloseBrace();

        sb.CloseBrace(); // class
    }

    private static void EmitConverter(
        SourceBuilder sb, UnionDeclaration union,
        string converterName, string unionType, string typeParams)
    {
        sb.AppendLine($"internal sealed class {converterName}{typeParams} : JsonConverter<{unionType}>");
        sb.OpenBrace();

        // Read method
        EmitReadMethod(sb, union, unionType);
        sb.AppendLine();

        // Write method
        EmitWriteMethod(sb, union, unionType);

        sb.CloseBrace(); // class
    }

    #region Read

    private static void EmitReadMethod(SourceBuilder sb, UnionDeclaration union, string unionType)
    {
        sb.AppendLine($"public override {unionType} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
        sb.OpenBrace();

        sb.AppendLine("using var doc = JsonDocument.ParseValue(ref reader);");
        sb.AppendLine("var root = doc.RootElement;");
        sb.AppendLine($"if (!root.TryGetProperty(\"{union.JsonDiscriminator}\", out var kindProp))");
        sb.AppendLine($"    throw new JsonException(\"Missing discriminator property '{union.JsonDiscriminator}'\");");
        sb.AppendLine("var kindStr = kindProp.GetString();");
        sb.AppendLine("return kindStr switch");
        sb.OpenBrace();

        foreach (var variant in union.Variants)
        {
            var jsonName = variant.JsonName ?? variant.Name;

            if (variant.Fields.Length == 0)
            {
                var ctor = IsRecordOrClass(union)
                    ? $"new {unionType}.{variant.Name}()"
                    : $"{unionType}.{variant.Name}()";
                sb.AppendLine($"\"{jsonName}\" => {ctor},");
            }
            else
            {
                var args = string.Join(", ",
                    variant.Fields.Select(f =>
                    {
                        var propName = f.JsonName ?? f.Name;
                        return $"root.GetProperty(\"{propName}\").Deserialize<{f.TypeFullName}>(options)!";
                    }));

                var ctor = IsRecordOrClass(union)
                    ? $"new {unionType}.{variant.Name}({args})"
                    : $"{unionType}.{variant.Name}({args})";
                sb.AppendLine($"\"{jsonName}\" => {ctor},");
            }
        }

        sb.AppendLine($"_ => throw new JsonException($\"Unknown {union.TypeName} variant: {{kindStr}}\")");
        sb.CloseBrace(";"); // switch expression ends with };

        sb.CloseBrace(); // method
    }

    #endregion

    #region Write

    private static void EmitWriteMethod(SourceBuilder sb, UnionDeclaration union, string unionType)
    {
        sb.AppendLine($"public override void Write(Utf8JsonWriter writer, {unionType} value, JsonSerializerOptions options)");
        sb.OpenBrace();
        sb.AppendLine("writer.WriteStartObject();");

        if (IsRecordOrClass(union))
            EmitWriteRecordOrClass(sb, union, unionType);
        else
            EmitWriteStruct(sb, union, unionType);

        sb.AppendLine("writer.WriteEndObject();");
        sb.CloseBrace(); // method
    }

    private static void EmitWriteStruct(SourceBuilder sb, UnionDeclaration union, string unionType)
    {
        sb.AppendLine("switch (value.tag)");
        sb.OpenBrace();

        foreach (var variant in union.Variants)
        {
            var jsonVariantName = variant.JsonName ?? variant.Name;
            sb.AppendLine($"case {unionType}.Kind.{variant.Name}:");
            sb.Indent();
            sb.AppendLine($"writer.WriteString(\"{union.JsonDiscriminator}\", \"{jsonVariantName}\");");

            EmitWriteFieldsForStructVariant(sb, union, variant);

            sb.AppendLine("break;");
            sb.Dedent();
        }

        sb.AppendLine("default:");
        sb.Indent();
        sb.AppendLine($"throw new JsonException($\"Unknown {union.TypeName} variant: {{value.tag}}\");");
        sb.Dedent();

        sb.CloseBrace(); // switch
    }

    private static void EmitWriteFieldsForStructVariant(
        SourceBuilder sb, UnionDeclaration union, VariantInfo variant)
    {
        switch (union.Strategy)
        {
            case EmitStrategy.Overlap:
                EmitWriteOverlapFields(sb, union, variant);
                break;
            case EmitStrategy.BoxedFields:
                EmitWriteBoxedFieldsFields(sb, variant);
                break;
            case EmitStrategy.BoxedTuple:
                EmitWriteBoxedTupleFields(sb, variant);
                break;
        }
    }

    private static void EmitWriteOverlapFields(
        SourceBuilder sb, UnionDeclaration union, VariantInfo variant)
    {
        var kindSize = OverlapLayoutComputer.KindSize(union.Variants.Length);
        var layout = OverlapLayoutComputer.ComputeLayout(union.Variants, kindSize);
        var vl = layout.Variants[variant.Name];

        int r1Idx = 0;
        int r2Idx = 0;
        int r3Idx = 0;
        foreach (var field in variant.Fields)
        {
            var jsonFieldName = field.JsonName ?? field.Name;
            var region = FieldClassifier.Classify(field);
            string accessExpr;

            switch (region)
            {
                case FieldRegion.Unmanaged:
                    if (vl.R1IsTuple)
                        accessExpr = $"value.{vl.R1FieldName}.{field.Name}";
                    else
                        accessExpr = $"value.{vl.R1FieldName}";
                    r1Idx++;
                    break;
                case FieldRegion.Reference:
                    var refFieldName = OverlapLayoutComputer.ToCamelCase(variant.Name) + "_" + field.Name;
                    accessExpr = $"value.{refFieldName}!";
                    r2Idx++;
                    break;
                case FieldRegion.Boxed:
                    var fp = vl.R3Fields[r3Idx];
                    accessExpr = $"({field.TypeFullName})value._obj_{fp.SlotIndex}!";
                    r3Idx++;
                    break;
                default:
                    continue;
            }

            sb.AppendLine($"writer.WritePropertyName(\"{jsonFieldName}\");");
            sb.AppendLine($"JsonSerializer.Serialize(writer, {accessExpr}, options);");
        }
    }

    private static void EmitWriteBoxedFieldsFields(SourceBuilder sb, VariantInfo variant)
    {
        for (int i = 0; i < variant.Fields.Length; i++)
        {
            var field = variant.Fields[i];
            var jsonFieldName = field.JsonName ?? field.Name;
            sb.AppendLine($"writer.WritePropertyName(\"{jsonFieldName}\");");
            sb.AppendLine($"JsonSerializer.Serialize(writer, ({field.TypeFullName})value._f{i}!, options);");
        }
    }

    private static void EmitWriteBoxedTupleFields(SourceBuilder sb, VariantInfo variant)
    {
        if (variant.Fields.Length == 0)
            return;

        if (variant.Fields.Length == 1)
        {
            var field = variant.Fields[0];
            var jsonFieldName = field.JsonName ?? field.Name;
            sb.AppendLine($"writer.WritePropertyName(\"{jsonFieldName}\");");
            sb.AppendLine($"JsonSerializer.Serialize(writer, ({field.TypeFullName})value._payload!, options);");
            return;
        }

        // Multi-field: cast payload to ValueTuple
        var tupleType = "(" + string.Join(", ",
            variant.Fields.Select(f => f.TypeFullName)) + ")";
        sb.AppendLine($"var _tuple = ({tupleType})value._payload!;");
        for (int i = 0; i < variant.Fields.Length; i++)
        {
            var field = variant.Fields[i];
            var jsonFieldName = field.JsonName ?? field.Name;
            sb.AppendLine($"writer.WritePropertyName(\"{jsonFieldName}\");");
            sb.AppendLine($"JsonSerializer.Serialize(writer, _tuple.Item{i + 1}, options);");
        }
    }

    private static void EmitWriteRecordOrClass(
        SourceBuilder sb, UnionDeclaration union, string unionType)
    {
        sb.AppendLine("switch (value)");
        sb.OpenBrace();

        foreach (var variant in union.Variants)
        {
            var jsonVariantName = variant.JsonName ?? variant.Name;

            if (variant.Fields.Length == 0)
            {
                sb.AppendLine($"case {unionType}.{variant.Name}:");
                sb.Indent();
                sb.AppendLine($"writer.WriteString(\"{union.JsonDiscriminator}\", \"{jsonVariantName}\");");
                sb.AppendLine("break;");
                sb.Dedent();
            }
            else
            {
                sb.AppendLine($"case {unionType}.{variant.Name} _v:");
                sb.Indent();
                sb.AppendLine($"writer.WriteString(\"{union.JsonDiscriminator}\", \"{jsonVariantName}\");");

                foreach (var field in variant.Fields)
                {
                    var jsonFieldName = field.JsonName ?? field.Name;
                    sb.AppendLine($"writer.WritePropertyName(\"{jsonFieldName}\");");
                    sb.AppendLine($"JsonSerializer.Serialize(writer, _v.{field.Name}, options);");
                }

                sb.AppendLine("break;");
                sb.Dedent();
            }
        }

        sb.AppendLine("default:");
        sb.Indent();
        sb.AppendLine($"throw new JsonException($\"Unknown {union.TypeName} variant: {{value}}\");");
        sb.Dedent();

        sb.CloseBrace(); // switch
    }

    #endregion

    #region Utilities

    private static bool IsRecordOrClass(UnionDeclaration union)
        => union.Strategy == EmitStrategy.Record || union.Strategy == EmitStrategy.Class;

    private static string FormatTypeParams(EquatableArray<string> typeParameters)
    {
        if (typeParameters.Length == 0) return "";
        return "<" + string.Join(", ", typeParameters) + ">";
    }

    /// Produces open generic syntax: "Foo<>" for arity 1, "Foo<,>" for arity 2, etc.
    private static string OpenGenericType(string typeName, int arity)
    {
        if (arity == 0) return typeName;
        return typeName + "<" + new string(',', arity - 1) + ">";
    }

    #endregion
}
