using System.Linq;
using Spire.SourceGenerators.Model;

namespace Spire.SourceGenerators.Emit;

/// Generates ToString() overrides for discriminated unions.
/// For struct strategies: emits inline into the partial struct body.
/// For record/class strategies: emits a separate file with per-variant partial re-declarations.
internal static class ToStringEmitter
{
    /// Emits a ToString() override into the struct body (call before the final CloseBrace).
    public static void EmitStructToString(SourceBuilder sb, UnionDeclaration union)
    {
        sb.AppendLine();
        sb.AppendLine("public override string ToString()");
        sb.OpenBrace();
        sb.AppendLine("return this.kind switch");
        sb.OpenBrace();

        foreach (var variant in union.Variants)
        {
            if (variant.Fields.Length == 0)
            {
                sb.AppendLine($"Kind.{variant.Name} => \"{variant.Name}()\",");
            }
            else
            {
                var fieldList = string.Join(", ", variant.Fields.Select(f => $"{{this.{f.Name}}}"));
                sb.AppendLine($"Kind.{variant.Name} => $\"{variant.Name}({fieldList})\",");
            }
        }

        sb.AppendLine($"_ => \"{union.TypeName}(?)\",");
        sb.CloseBrace(";");
        sb.CloseBrace();
    }

    /// Returns a complete generated file containing per-variant ToString() overrides.
    /// Used for Record and Class strategies (emitted as a separate .ToString.g.cs file).
    public static string EmitRecordClassToString(UnionDeclaration union)
    {
        var sb = new SourceBuilder();
        var variantKeyword = union.Strategy == EmitStrategy.Record ? "record" : "class";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(union.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {union.Namespace}");
            sb.OpenBrace();
        }

        sb.OpenContainingTypes(union.ContainingTypes);

        var typeParams = FormatTypeParams(union.TypeParameters);
        var unionType = union.TypeName + typeParams;

        var accessMod = string.IsNullOrEmpty(union.AccessibilityKeyword) ? "" : union.AccessibilityKeyword + " ";
        var abstractMod = "abstract ";
        sb.AppendLine($"{accessMod}{abstractMod}partial {union.DeclarationKeyword} {unionType}");
        sb.OpenBrace();

        foreach (var variant in union.Variants)
        {
            var variantAccess = string.IsNullOrEmpty(variant.AccessibilityKeyword) ? "" : variant.AccessibilityKeyword + " ";
            sb.AppendLine($"{variantAccess}sealed partial {variantKeyword} {variant.Name}");
            sb.OpenBrace();

            if (variant.Fields.Length == 0)
            {
                sb.AppendLine($"public override string ToString() => \"{variant.Name}()\";");
            }
            else
            {
                var fieldList = string.Join(", ", variant.Fields.Select(f => $"{{this.{f.Name}}}"));
                sb.AppendLine($"public override string ToString() => $\"{variant.Name}({fieldList})\";");
            }

            sb.CloseBrace();
        }

        sb.CloseBrace(); // union type

        sb.CloseContainingTypes(union.ContainingTypes);

        if (hasNamespace)
            sb.CloseBrace(); // namespace

        return sb.ToString();
    }

    private static string FormatTypeParams(EquatableArray<string> typeParameters)
    {
        if (typeParameters.Length == 0) return "";
        return "<" + string.Join(", ", typeParameters) + ">";
    }
}
