using System.Collections.Generic;
using System.Linq;
using Spire.SourceGenerators.Model;

namespace Spire.SourceGenerators.Emit;

/// Generates struct unions using a byte buffer for unmanaged fields (true overlap)
/// and dedup slots for reference/generic fields. Requires AllowUnsafeBlocks.
internal static class UnsafeOverlapEmitter
{
    public static string Emit(UnionDeclaration union, bool hasInlineArray)
    {
        var sb = new SourceBuilder();
        var layout = ComputeLayout(union.Variants);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(union.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {union.Namespace}");
            sb.OpenBrace();
        }

        sb.OpenContainingTypes(union.ContainingTypes);

        var typeParams = FormatTypeParams(union.TypeParameters);
        var unionType = union.TypeName + typeParams;
        var accessMod = string.IsNullOrEmpty(union.AccessibilityKeyword) ? "" : union.AccessibilityKeyword + " ";
        var readonlyMod = union.IsReadonly ? "readonly " : "";
        var refMod = union.IsRefStruct ? "ref " : "";

        sb.AppendLine("[global::Spire.Analyzers.MustBeInit]");
        sb.AppendLine($"{accessMod}{readonlyMod}{refMod}partial {union.DeclarationKeyword} {unionType}");
        sb.OpenBrace();

        // Kind enum
        var kindType = OverlapLayoutComputer.KindTypeName(union.Variants.Length);
        sb.AppendLine($"public enum Kind : {kindType}");
        sb.OpenBrace();
        foreach (var variant in union.Variants)
            sb.AppendLine($"{variant.Name},");
        sb.CloseBrace();
        sb.AppendLine();

        // Kind field
        sb.AppendLine("public readonly Kind kind;");
        sb.AppendLine();

        // InlineArray buffer (if any unmanaged fields)
        if (layout.BufferSize > 0)
        {
            if (hasInlineArray)
            {
                sb.AppendLine($"[InlineArray({layout.BufferSize})]");
                sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
                sb.AppendLine("internal struct _Buffer { internal byte _element; }");
                sb.AppendLine();
                sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
                sb.AppendLine("internal _Buffer _data;");
            }
            else
            {
                int longCount = (layout.BufferSize + 7) / 8;
                for (int i = 0; i < longCount; i++)
                {
                    sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
                    sb.AppendLine($"internal long _data{i};");
                }
            }
            sb.AppendLine();
        }

        // Dedup slots for reference/generic fields
        foreach (var slot in layout.Slots)
        {
            sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
            var slotType = slot.IsRefSlot ? "object?" : slot.TypeFullName;
            sb.AppendLine($"internal {slotType} _s{slot.Index};");
        }
        if (layout.Slots.Count > 0)
            sb.AppendLine();

        // Constructor
        EmitConstructor(sb, union.TypeName, layout);
        sb.AppendLine();

        // Factory methods
        EmitFactories(sb, union, unionType, layout);

        // Deconstruct overloads
        if (union.GenerateDeconstruct)
            EmitDeconstructs(sb, union.Variants, layout);

        // Public properties for pattern matching
        if (layout.IsNamePinned)
            EmitProperties(sb, union.Variants, layout);

        sb.CloseBrace(); // type

        sb.CloseContainingTypes(union.ContainingTypes);

        if (hasNamespace)
            sb.CloseBrace();

        return sb.ToString();
    }

    #region Layout

    internal sealed class UnsafeLayout
    {
        public int BufferSize;
        public List<SlotInfo> Slots = new List<SlotInfo>();
        public Dictionary<string, VariantMapping> Variants = new Dictionary<string, VariantMapping>();
        /// Name-pinned buffer offsets
        public Dictionary<string, BufferFieldInfo> NamedBufferFields = new Dictionary<string, BufferFieldInfo>();
        /// Name-pinned slot mappings
        public Dictionary<string, int> NamedSlots = new Dictionary<string, int>();
        public bool IsNamePinned;
    }

    internal sealed class BufferFieldInfo
    {
        public string TypeFullName = "";
        public int Offset;
        public int Size;
    }

    internal sealed class SlotInfo
    {
        public int Index;
        public string TypeFullName = "";
        public bool IsRefSlot;
    }

    internal sealed class FieldMapping
    {
        /// True if field goes in the byte buffer, false if in a dedup slot.
        public bool IsBuffer;
        /// Byte offset within the buffer (if IsBuffer).
        public int BufferOffset;
        /// Slot index (if !IsBuffer).
        public int SlotIndex;
    }

    internal sealed class VariantMapping
    {
        public List<FieldMapping> Fields = new List<FieldMapping>();
        public bool HasBufferFields;
        public bool HasSlotFields;
    }

    private static bool IsBufferField(FieldInfo field)
    {
        return field.IsUnmanaged && field.KnownSize.HasValue;
    }

    internal static UnsafeLayout ComputeLayout(IEnumerable<VariantInfo> variants)
    {
        var variantList = variants.ToList();
        return HasFieldNameConflicts(variantList)
            ? ComputeLayoutSequential(variantList)
            : ComputeLayoutNamePinned(variantList);
    }

    private static bool HasFieldNameConflicts(List<VariantInfo> variantList)
    {
        var fieldTypes = new Dictionary<string, string>();
        foreach (var variant in variantList)
        {
            foreach (var field in variant.Fields)
            {
                if (fieldTypes.TryGetValue(field.Name, out var existing))
                {
                    if (existing != field.TypeFullName)
                        return true;
                }
                else
                {
                    fieldTypes[field.Name] = field.TypeFullName;
                }
            }
        }
        return false;
    }

    private static UnsafeLayout ComputeLayoutSequential(List<VariantInfo> variantList)
    {
        var layout = new UnsafeLayout();

        // Buffer size: max total unmanaged bytes per variant
        int maxBufferBytes = 0;
        foreach (var variant in variantList)
        {
            int bytes = 0;
            foreach (var field in variant.Fields)
            {
                if (IsBufferField(field))
                    bytes += field.KnownSize!.Value;
            }
            if (bytes > maxBufferBytes)
                maxBufferBytes = bytes;
        }
        layout.BufferSize = maxBufferBytes;

        // Dedup slots for non-buffer fields (same algorithm as Additive)
        var typeMaxCounts = new Dictionary<string, int>();
        foreach (var variant in variantList)
        {
            var typeCounts = new Dictionary<string, int>();
            foreach (var field in variant.Fields)
            {
                if (IsBufferField(field)) continue;
                var key = field.IsReferenceType ? "object?" : field.TypeFullName;
                if (!typeCounts.ContainsKey(key))
                    typeCounts[key] = 0;
                typeCounts[key]++;
            }

            foreach (var kv in typeCounts)
            {
                if (!typeMaxCounts.ContainsKey(kv.Key) || kv.Value > typeMaxCounts[kv.Key])
                    typeMaxCounts[kv.Key] = kv.Value;
            }
        }

        int slotIndex = 0;
        var typeSlotStarts = new Dictionary<string, int>();
        foreach (var kv in typeMaxCounts.OrderBy(x => x.Key))
        {
            typeSlotStarts[kv.Key] = slotIndex;
            bool isRef = kv.Key == "object?";

            for (int i = 0; i < kv.Value; i++)
            {
                layout.Slots.Add(new SlotInfo
                {
                    Index = slotIndex++,
                    TypeFullName = kv.Key,
                    IsRefSlot = isRef,
                });
            }
        }

        // Per-variant field mappings
        foreach (var variant in variantList)
        {
            var mapping = new VariantMapping();
            int bufferOffset = 0;
            var typeCounters = new Dictionary<string, int>();

            foreach (var field in variant.Fields)
            {
                if (IsBufferField(field))
                {
                    mapping.Fields.Add(new FieldMapping
                    {
                        IsBuffer = true,
                        BufferOffset = bufferOffset,
                    });
                    bufferOffset += field.KnownSize!.Value;
                    mapping.HasBufferFields = true;
                }
                else
                {
                    var key = field.IsReferenceType ? "object?" : field.TypeFullName;
                    if (!typeCounters.ContainsKey(key))
                        typeCounters[key] = 0;
                    int typeLocalIndex = typeCounters[key]++;
                    int slot = typeSlotStarts[key] + typeLocalIndex;

                    mapping.Fields.Add(new FieldMapping
                    {
                        IsBuffer = false,
                        SlotIndex = slot,
                    });
                    mapping.HasSlotFields = true;
                }
            }

            layout.Variants[variant.Name] = mapping;
        }

        return layout;
    }

    private static UnsafeLayout ComputeLayoutNamePinned(List<VariantInfo> variantList)
    {
        var layout = new UnsafeLayout { IsNamePinned = true };

        // Collect unique buffer fields and slot fields by name
        var bufferFields = new Dictionary<string, FieldInfo>();
        var slotFields = new Dictionary<string, FieldInfo>();

        foreach (var variant in variantList)
        {
            foreach (var field in variant.Fields)
            {
                if (IsBufferField(field))
                {
                    if (!bufferFields.ContainsKey(field.Name))
                        bufferFields[field.Name] = field;
                }
                else
                {
                    if (!slotFields.ContainsKey(field.Name))
                        slotFields[field.Name] = field;
                }
            }
        }

        // Assign global byte offsets for buffer fields (sorted by name)
        int bufferOffset = 0;
        foreach (var kv in bufferFields.OrderBy(x => x.Key))
        {
            layout.NamedBufferFields[kv.Key] = new BufferFieldInfo
            {
                TypeFullName = kv.Value.TypeFullName,
                Offset = bufferOffset,
                Size = kv.Value.KnownSize!.Value,
            };
            bufferOffset += kv.Value.KnownSize!.Value;
        }
        layout.BufferSize = bufferOffset;

        // Assign global slot indices for non-buffer fields (sorted by name)
        int slotIndex = 0;
        foreach (var kv in slotFields.OrderBy(x => x.Key))
        {
            var slotTypeKey = kv.Value.IsReferenceType ? "object?" : kv.Value.TypeFullName;
            bool isRef = kv.Value.IsReferenceType;

            layout.Slots.Add(new SlotInfo
            {
                Index = slotIndex,
                TypeFullName = slotTypeKey,
                IsRefSlot = isRef,
            });
            layout.NamedSlots[kv.Key] = slotIndex;
            slotIndex++;
        }

        // Per-variant field mappings using pinned offsets/slots
        foreach (var variant in variantList)
        {
            var mapping = new VariantMapping();

            foreach (var field in variant.Fields)
            {
                if (IsBufferField(field))
                {
                    var bf = layout.NamedBufferFields[field.Name];
                    mapping.Fields.Add(new FieldMapping
                    {
                        IsBuffer = true,
                        BufferOffset = bf.Offset,
                    });
                    mapping.HasBufferFields = true;
                }
                else
                {
                    mapping.Fields.Add(new FieldMapping
                    {
                        IsBuffer = false,
                        SlotIndex = layout.NamedSlots[field.Name],
                    });
                    mapping.HasSlotFields = true;
                }
            }

            layout.Variants[variant.Name] = mapping;
        }

        return layout;
    }

    #endregion

    #region Emit

    private static void EmitConstructor(SourceBuilder sb, string typeName, UnsafeLayout layout)
    {
        sb.AppendLine($"{typeName}(Kind kind)");
        sb.OpenBrace();
        sb.AppendLine("this.kind = kind;");
        if (layout.BufferSize > 0)
            sb.AppendLine("this._data = default;");
        foreach (var slot in layout.Slots)
            sb.AppendLine($"this._s{slot.Index} = default!;");
        sb.CloseBrace();
    }

    private static void EmitFactories(
        SourceBuilder sb, UnionDeclaration union, string unionType, UnsafeLayout layout)
    {
        foreach (var variant in union.Variants)
        {
            var mapping = layout.Variants[variant.Name];
            var typedParams = string.Join(", ",
                variant.Fields.Select(f => $"{f.TypeFullName} {f.Name}"));

            bool hasFields = variant.Fields.Length > 0;

            if (!hasFields)
            {
                sb.AppendLine($"public static partial {unionType} {variant.Name}()");
                sb.AppendLine($"    => new {unionType}(Kind.{variant.Name});");
                continue;
            }

            sb.AppendLine($"public static partial {unionType} {variant.Name}({typedParams})");
            sb.OpenBrace();
            sb.AppendLine($"var s = new {unionType}(Kind.{variant.Name});");

            for (int i = 0; i < variant.Fields.Length; i++)
            {
                var field = variant.Fields[i];
                var fm = mapping.Fields[i];

                if (fm.IsBuffer)
                {
                    if (fm.BufferOffset == 0)
                        sb.AppendLine($"Unsafe.WriteUnaligned(ref s._data[0], {field.Name});");
                    else
                        sb.AppendLine($"Unsafe.WriteUnaligned(ref Unsafe.Add(ref s._data[0], {fm.BufferOffset}), {field.Name});");
                }
                else
                {
                    sb.AppendLine($"s._s{fm.SlotIndex} = {field.Name};");
                }
            }

            sb.AppendLine("return s;");
            sb.CloseBrace();
        }
    }

    private static void EmitProperties(
        SourceBuilder sb, IEnumerable<VariantInfo> variants, UnsafeLayout layout)
    {
        var emitted = new HashSet<string>();
        foreach (var variant in variants)
        {
            var mapping = layout.Variants[variant.Name];
            for (int i = 0; i < variant.Fields.Length; i++)
            {
                var field = variant.Fields[i];
                if (!emitted.Add(field.Name)) continue;

                var fm = mapping.Fields[i];
                sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");

                if (fm.IsBuffer)
                {
                    if (fm.BufferOffset == 0)
                        sb.AppendLine($"public {field.TypeFullName} {field.Name} => Unsafe.ReadUnaligned<{field.TypeFullName}>(ref _data[0]);");
                    else
                        sb.AppendLine($"public {field.TypeFullName} {field.Name} => Unsafe.ReadUnaligned<{field.TypeFullName}>(ref Unsafe.Add(ref _data[0], {fm.BufferOffset}));");
                }
                else
                {
                    var slotInfo = layout.Slots[fm.SlotIndex];
                    if (slotInfo.IsRefSlot)
                        sb.AppendLine($"public {field.TypeFullName} {field.Name} => ({field.TypeFullName})this._s{fm.SlotIndex}!;");
                    else
                        sb.AppendLine($"public {field.TypeFullName} {field.Name} => this._s{fm.SlotIndex};");
                }
            }
        }
    }

    private static void EmitDeconstructs(
        SourceBuilder sb, IEnumerable<VariantInfo> variants, UnsafeLayout layout)
    {
        var variantList = variants.ToList();
        if (variantList.Count == 0) return;

        var groups = GroupByFieldCount(variantList);
        var hasFieldlessVariants = groups.ContainsKey(0);

        if (groups.Count == 1 && hasFieldlessVariants)
        {
            sb.AppendLine();
            sb.AppendLine("public void Deconstruct(out Kind kind, out object? _f0)");
            sb.OpenBrace();
            sb.AppendLine("kind = this.kind;");
            sb.AppendLine("_f0 = null;");
            sb.CloseBrace();
            return;
        }

        var nonZeroGroups = groups
            .Where(g => g.Key > 0)
            .OrderBy(g => g.Key)
            .ToList();

        if (hasFieldlessVariants && nonZeroGroups.Count > 0)
        {
            var smallest = nonZeroGroups[0];
            if (smallest.Value.Count == 1)
                smallest.Value.AddRange(groups[0]);
        }

        foreach (var group in nonZeroGroups)
        {
            var groupVariants = group.Value;
            sb.AppendLine();

            if (groupVariants.Count == 1)
                EmitTypedDeconstruct(sb, groupVariants[0], layout);
            else
                EmitObjectDeconstruct(sb, group.Key, groupVariants, layout);
        }
    }

    private static void EmitTypedDeconstruct(
        SourceBuilder sb, VariantInfo variant, UnsafeLayout layout)
    {
        var mapping = layout.Variants[variant.Name];

        var paramList = "out Kind kind";
        foreach (var field in variant.Fields)
            paramList += $", out {field.TypeFullName} {field.Name}";

        sb.AppendLine($"public void Deconstruct({paramList})");
        sb.OpenBrace();
        sb.AppendLine("kind = this.kind;");

        for (int i = 0; i < variant.Fields.Length; i++)
        {
            var field = variant.Fields[i];
            var fm = mapping.Fields[i];

            if (fm.IsBuffer)
            {
                if (fm.BufferOffset == 0)
                    sb.AppendLine($"{field.Name} = Unsafe.ReadUnaligned<{field.TypeFullName}>(ref _data[0]);");
                else
                    sb.AppendLine($"{field.Name} = Unsafe.ReadUnaligned<{field.TypeFullName}>(ref Unsafe.Add(ref _data[0], {fm.BufferOffset}));");
            }
            else
            {
                var slotInfo = layout.Slots[fm.SlotIndex];
                if (slotInfo.IsRefSlot)
                    sb.AppendLine($"{field.Name} = ({field.TypeFullName})this._s{fm.SlotIndex}!;");
                else
                    sb.AppendLine($"{field.Name} = this._s{fm.SlotIndex};");
            }
        }

        sb.CloseBrace();
    }

    private static void EmitObjectDeconstruct(
        SourceBuilder sb, int fieldCount, List<VariantInfo> groupVariants, UnsafeLayout layout)
    {
        var paramList = "out Kind kind";
        for (int i = 0; i < fieldCount; i++)
            paramList += $", out object? f{i}";

        sb.AppendLine($"public void Deconstruct({paramList})");
        sb.OpenBrace();
        sb.AppendLine("kind = this.kind;");

        var realVariants = groupVariants.Where(v => v.Fields.Length > 0).ToList();

        if (realVariants.Count > 0)
        {
            sb.AppendLine("switch (this.kind)");
            sb.OpenBrace();

            foreach (var variant in realVariants)
            {
                var mapping = layout.Variants[variant.Name];
                sb.AppendLine($"case Kind.{variant.Name}:");
                sb.Indent();

                for (int i = 0; i < variant.Fields.Length; i++)
                {
                    var field = variant.Fields[i];
                    var fm = mapping.Fields[i];

                    if (fm.IsBuffer)
                    {
                        if (fm.BufferOffset == 0)
                            sb.AppendLine($"f{i} = Unsafe.ReadUnaligned<{field.TypeFullName}>(ref _data[0]);");
                        else
                            sb.AppendLine($"f{i} = Unsafe.ReadUnaligned<{field.TypeFullName}>(ref Unsafe.Add(ref _data[0], {fm.BufferOffset}));");
                    }
                    else
                    {
                        sb.AppendLine($"f{i} = this._s{fm.SlotIndex};");
                    }
                }

                sb.AppendLine("break;");
                sb.Dedent();
            }

            sb.AppendLine("default:");
            sb.Indent();
            for (int i = 0; i < fieldCount; i++)
                sb.AppendLine($"f{i} = null;");
            sb.AppendLine("break;");
            sb.Dedent();

            sb.CloseBrace(); // switch
        }
        else
        {
            for (int i = 0; i < fieldCount; i++)
                sb.AppendLine($"f{i} = null;");
        }

        sb.CloseBrace(); // method
    }

    private static Dictionary<int, List<VariantInfo>> GroupByFieldCount(List<VariantInfo> variants)
    {
        var groups = new Dictionary<int, List<VariantInfo>>();
        foreach (var v in variants)
        {
            int count = v.Fields.Length;
            if (!groups.TryGetValue(count, out var list))
            {
                list = new List<VariantInfo>();
                groups[count] = list;
            }
            list.Add(v);
        }
        return groups;
    }

    private static string FormatTypeParams(EquatableArray<string> typeParameters)
    {
        if (typeParameters.Length == 0) return "";
        return "<" + string.Join(", ", typeParameters) + ">";
    }

    #endregion
}
