// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;

namespace TestNs
{
    [global::Houtamelo.Spire.Core.EnforceInitialization]
    [StructLayout(LayoutKind.Explicit)]
    partial struct Event : global::Houtamelo.Spire.Core.IDiscriminatedUnion<Event.Kind>
    {
        public enum Kind : byte
        {
            Click,
            Hover,
        }

        [FieldOffset(0)]
        readonly Kind _kind;
        public Kind kind => this._kind;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [FieldOffset(1)]
        internal readonly float _posX;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [FieldOffset(5)]
        internal readonly float _posY;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [FieldOffset(9)]
        internal readonly int _x;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [FieldOffset(13)]
        internal readonly int _y;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [FieldOffset(24)]
        internal readonly string? _target;

        Event(Kind kind) : this()
        {
            this._kind = kind;
        }

        public static partial Event Click(int x, int y, string target)
        {
            var s = new Event(Kind.Click);
            Unsafe.AsRef(in s._x) = x;
            Unsafe.AsRef(in s._y) = y;
            Unsafe.AsRef(in s._target) = target;
            return s;
        }
        public static partial Event Hover(float posX, float posY)
        {
            var s = new Event(Kind.Hover);
            Unsafe.AsRef(in s._posX) = posX;
            Unsafe.AsRef(in s._posY) = posY;
            return s;
        }

        public void Deconstruct(out Kind kind, out float posX, out float posY)
        {
            kind = this.kind;
            posX = this._posX;
            posY = this._posY;
        }

        public void Deconstruct(out Kind kind, out int x, out int y, out string target)
        {
            kind = this.kind;
            x = this._x;
            y = this._y;
            target = this._target!;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public float posX
        {
            get => this._posX;
            init => this._posX = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public float posY
        {
            get => this._posY;
            init => this._posY = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int x
        {
            get => this._x;
            init => this._x = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int y
        {
            get => this._y;
            init => this._y = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string target
        {
            get => this._target!;
            init => this._target = value;
        }
        public bool IsClick => this.kind == Kind.Click;
        public bool IsHover => this.kind == Kind.Hover;
        public override string ToString()
        {
            return this.kind switch
            {
                Kind.Click => $"Click({this.x}, {this.y}, {this.target})",
                Kind.Hover => $"Hover({this.posX}, {this.posY})",
                _ => "Event(?)",
            };
        }
    }
}
