// <auto-generated/>
#nullable enable

namespace TestNs
{
    public static partial class Samples
    {
        public readonly struct LogInliner : global::Houtamelo.Spire.IActionInliner<string>
        {
            public void Invoke(string a1) => Samples.Log(a1);
        }
    }
}
