// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.MustBeInit]
    partial struct Event : global::Spire.IDiscriminatedUnion<Event.Kind>
    {
        public enum Kind : byte
        {
            Click,
            Error,
            Ping,
        }

        readonly Kind _kind;
        public Kind kind => this._kind;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal int _s0 { get; init; }
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal int _s1 { get; init; }
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal object? _s2 { get; init; }
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal object? _s3 { get; init; }
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal object? _s4 { get; init; }

        Event(Kind kind, int s0, int s1, object? s2, object? s3, object? s4)
        {
            this._kind = kind;
            this._s0 = s0;
            this._s1 = s1;
            this._s2 = s2;
            this._s3 = s3;
            this._s4 = s4;
        }

        public static partial Event Click(int x, int y, string target)
            => new Event(Kind.Click, x, y, default!, default!, target);
        public static partial Event Error(string message, global::System.Exception ex)
            => new Event(Kind.Error, default, default, ex, message, default!);
        public static partial Event Ping()
            => new Event(Kind.Ping, default, default, default!, default!, default!);

        public void Deconstruct(out Kind kind, out object? f0, out object? f1)
        {
            kind = this.kind;
            switch (this.kind)
            {
                case Kind.Error:
                    f0 = this._s3;
                    f1 = this._s2;
                    break;
                default:
                    f0 = null;
                    f1 = null;
                    break;
            }
        }

        public void Deconstruct(out Kind kind, out int x, out int y, out string target)
        {
            kind = this.kind;
            x = this._s0;
            y = this._s1;
            target = (string)this._s4!;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int x
        {
            get => this._s0;
            init => this._s0 = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int y
        {
            get => this._s1;
            init => this._s1 = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string target
        {
            get => (string)this._s4!;
            init => this._s4 = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string message
        {
            get => (string)this._s3!;
            init => this._s3 = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public global::System.Exception ex
        {
            get => (global::System.Exception)this._s2!;
            init => this._s2 = value;
        }
        public bool IsClick => this.kind == Kind.Click;
        public bool IsError => this.kind == Kind.Error;
        public bool IsPing => this.kind == Kind.Ping;
        public override string ToString()
        {
            return this.kind switch
            {
                Kind.Click => $"Click({this.x}, {this.y}, {this.target})",
                Kind.Error => $"Error({this.message}, {this.ex})",
                Kind.Ping => "Ping()",
                _ => "Event(?)",
            };
        }
    }
}
