// <auto-generated/>
#nullable enable

using System;
using Houtamelo.Spire;

namespace TestNs
{
    public static partial class Runner
    {
        public static void Repeat<TCbInliner>(int n, TCbInliner cb)
            where TCbInliner : struct, global::Houtamelo.Spire.IActionInliner
        {
            for (int i = 0; i < n; i++)
                cb.Invoke();
        }
    }
}
