namespace Spire.SourceGenerators.Attributes;

internal static class AttributeSource
{
    public const string Hint_DiscriminatedUnion = "DiscriminatedUnionAttribute.g.cs";
    public const string Hint_Variant = "VariantAttribute.g.cs";
    public const string Hint_Layout = "Layout.g.cs";

    public const string DiscriminatedUnionAttribute = """
        // <auto-generated/>
        #nullable enable

        namespace Spire
        {
            [global::System.AttributeUsage(
                global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class,
                Inherited = false)]
            internal sealed class DiscriminatedUnionAttribute : global::System.Attribute
            {
                public Layout Layout { get; }
                public DiscriminatedUnionAttribute(Layout layout = Layout.Auto)
                    => Layout = layout;
            }
        }
        """;

    public const string VariantAttribute = """
        // <auto-generated/>
        #nullable enable

        namespace Spire
        {
            [global::System.AttributeUsage(
                global::System.AttributeTargets.Method,
                Inherited = false)]
            internal sealed class VariantAttribute : global::System.Attribute { }
        }
        """;

    public const string LayoutEnum = """
        // <auto-generated/>

        namespace Spire
        {
            internal enum Layout
            {
                Auto,
                Overlap,
                BoxedFields,
                BoxedTuple,
            }
        }
        """;
}
