// <auto-generated/>
#nullable enable

namespace MyApp
{
    public abstract partial class Option<T>
    {
        private Option() { }

        public sealed partial class Some;
        public sealed partial class None;
    }
}
