// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using Houtamelo.Spire;

namespace TestNs
{
    public static partial class ListExt
    {
        public static void ForEach<T, TActionInliner>(this global::System.Collections.Generic.List<T> list, TActionInliner action)
            where TActionInliner : struct, global::Houtamelo.Spire.IActionInliner<T>
        {
            foreach (var item in list)
                action.Invoke(item);
        }
    }
}
