// <auto-generated/>
#nullable enable
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

internal sealed class ShapeNsjConverter : JsonConverter<Shape>
{
    public override Shape ReadJson(JsonReader reader, Type objectType, Shape existingValue, bool hasExistingValue, JsonSerializer serializer)
    {
        var obj = JObject.Load(reader);
        var kindStr = obj["kind"]?.Value<string>()
            ?? throw new JsonSerializationException("Missing discriminator property 'kind'");
        return kindStr switch
        {
            "Circle" => Shape.Circle(obj["radius"]!.ToObject<double>(serializer)!),
            "Rectangle" => Shape.Rectangle(obj["width"]!.ToObject<float>(serializer)!, obj["height"]!.ToObject<float>(serializer)!),
            "Point" => Shape.Point(),
            _ => throw new JsonSerializationException($"Unknown Shape variant: {kindStr}")
        };
    }

    public override void WriteJson(JsonWriter writer, Shape value, JsonSerializer serializer)
    {
        writer.WriteStartObject();
        switch (value.tag)
        {
            case Shape.Kind.Circle:
                writer.WritePropertyName("kind");
                writer.WriteValue("Circle");
                writer.WritePropertyName("radius");
                serializer.Serialize(writer, value.radius);
                break;
            case Shape.Kind.Rectangle:
                writer.WritePropertyName("kind");
                writer.WriteValue("Rectangle");
                writer.WritePropertyName("width");
                serializer.Serialize(writer, value.width);
                writer.WritePropertyName("height");
                serializer.Serialize(writer, value.height);
                break;
            case Shape.Kind.Point:
                writer.WritePropertyName("kind");
                writer.WriteValue("Point");
                break;
            default:
                throw new JsonSerializationException($"Unknown Shape variant: {value.tag}");
        }
        writer.WriteEndObject();
    }
}

[Newtonsoft.Json.JsonConverter(typeof(ShapeNsjConverter))]
partial struct Shape { }
