using System.Collections.Generic;
using System.Linq;
using Houtamelo.Spire.Analyzers.SourceGenerators.Model;

namespace Houtamelo.Spire.Analyzers.SourceGenerators.Emit;

internal static class BoxedFieldsEmitter
{
    public static string Emit(UnionDeclaration union)
    {
        var sb = new SourceBuilder();
        var layout = ComputeLayout(union.Variants);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(union.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {union.Namespace}");
            sb.OpenBrace();
        }

        sb.OpenContainingTypes(union.ContainingTypes);

        var typeParams = FormatTypeParams(union.TypeParameters);
        var unionType = union.TypeName + typeParams;
        var accessMod = string.IsNullOrEmpty(union.AccessibilityKeyword) ? "" : union.AccessibilityKeyword + " ";
        var readonlyMod = union.IsReadonly ? "readonly " : "";
        var refMod = union.IsRefStruct ? "ref " : "";

        sb.AppendLine("[global::Houtamelo.Spire.EnforceInitialization]");
        sb.AppendLine($"{accessMod}{readonlyMod}{refMod}partial {union.DeclarationKeyword} {unionType} : global::Houtamelo.Spire.IDiscriminatedUnion<{unionType}.Kind>");
        sb.OpenBrace();

        // Kind enum
        EmitKindEnum(sb, union);
        sb.AppendLine();

        // Kind field (backing field + property)
        sb.AppendLine("readonly Kind _kind;");
        sb.AppendLine("public Kind kind => this._kind;");

        // Boxed slot fields
        for (int i = 0; i < layout.SlotCount; i++)
        {
            sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
            if (union.HasInitProperties)
                sb.AppendLine($"internal object? _f{i} {{ get; init; }}");
            else
                sb.AppendLine($"internal readonly object? _f{i};");
        }
        sb.AppendLine();

        // Private constructor
        EmitConstructor(sb, union.TypeName, layout.SlotCount);
        sb.AppendLine();

        // Factory methods
        EmitFactories(sb, union, unionType, layout);

        // Deconstruct overloads
        if (union.GenerateDeconstruct)
            EmitDeconstructs(sb, union.Variants, layout);

        // Public properties for pattern matching
        EmitProperties(sb, union.Variants, layout, union.HasInitProperties);

        // IsVariant properties
        foreach (var variant in union.Variants)
            sb.AppendLine($"public bool Is{variant.Name} => this.kind == Kind.{variant.Name};");

        ToStringEmitter.EmitStructToString(sb, union);

        sb.CloseBrace(); // type

        sb.CloseContainingTypes(union.ContainingTypes);

        if (hasNamespace)
            sb.CloseBrace(); // namespace

        return sb.ToString();
    }

    #region Layout

    internal sealed class BoxedFieldsLayout
    {
        public int SlotCount;
        public Dictionary<string, VariantMapping> Variants = new Dictionary<string, VariantMapping>();
    }

    internal sealed class VariantMapping
    {
        /// Maps field index (within the variant) to slot index.
        public List<int> FieldToSlot = new List<int>();
    }

    internal static BoxedFieldsLayout ComputeLayout(IEnumerable<VariantInfo> variants)
    {
        var variantList = variants.ToList();
        var layout = new BoxedFieldsLayout();

        // Collect unique field names (sorted for determinism)
        var nameToSlot = new Dictionary<string, int>();
        int slotIndex = 0;
        foreach (var name in variantList
            .SelectMany(v => v.Fields)
            .Select(f => f.Name)
            .Distinct()
            .OrderBy(n => n))
        {
            nameToSlot[name] = slotIndex++;
        }

        layout.SlotCount = slotIndex;

        foreach (var variant in variantList)
        {
            var mapping = new VariantMapping();
            foreach (var field in variant.Fields)
                mapping.FieldToSlot.Add(nameToSlot[field.Name]);
            layout.Variants[variant.Name] = mapping;
        }

        return layout;
    }

    #endregion

    #region Emit helpers

    private static void EmitKindEnum(SourceBuilder sb, UnionDeclaration union)
    {
        var kindType = OverlapLayoutComputer.KindTypeName(union.Variants.Length);
        sb.AppendLine($"public enum Kind : {kindType}");
        sb.OpenBrace();
        foreach (var variant in union.Variants)
            sb.AppendLine($"{variant.Name},");
        sb.CloseBrace();
    }

    private static void EmitConstructor(SourceBuilder sb, string typeName, int slotCount)
    {
        var paramList = "Kind kind";
        for (int i = 0; i < slotCount; i++)
            paramList += $", object? f{i}";

        sb.AppendLine($"{typeName}({paramList})");
        sb.OpenBrace();
        sb.AppendLine("this._kind = kind;");
        for (int i = 0; i < slotCount; i++)
            sb.AppendLine($"this._f{i} = f{i};");
        sb.CloseBrace();
    }

    private static void EmitFactories(
        SourceBuilder sb, UnionDeclaration union, string unionType, BoxedFieldsLayout layout)
    {
        foreach (var variant in union.Variants)
        {
            var mapping = layout.Variants[variant.Name];
            var typedParams = string.Join(", ",
                variant.Fields.Select(f => $"{f.TypeFullName} {f.Name}"));

            var args = new string[layout.SlotCount];
            for (int i = 0; i < layout.SlotCount; i++)
                args[i] = "null";

            for (int fi = 0; fi < variant.Fields.Length; fi++)
                args[mapping.FieldToSlot[fi]] = variant.Fields[fi].Name;

            var ctorArgs = "Kind." + variant.Name;
            if (layout.SlotCount > 0)
                ctorArgs += ", " + string.Join(", ", args);

            sb.AppendLine($"public static partial {unionType} {variant.Name}({typedParams})");
            sb.AppendLine($"    => new {unionType}({ctorArgs});");
        }
    }

    private static void EmitProperties(
        SourceBuilder sb, IEnumerable<VariantInfo> variants, BoxedFieldsLayout layout, bool hasInitProperties)
    {
        var emitted = new HashSet<string>();
        foreach (var variant in variants)
        {
            var mapping = layout.Variants[variant.Name];
            for (int i = 0; i < variant.Fields.Length; i++)
            {
                var field = variant.Fields[i];
                if (!emitted.Add(field.Name)) continue;

                int slot = mapping.FieldToSlot[i];
                sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
                if (hasInitProperties)
                {
                    sb.AppendLine($"public {field.TypeFullName} {field.Name}");
                    sb.OpenBrace();
                    sb.AppendLine($"get => ({field.TypeFullName})this._f{slot}!;");
                    sb.AppendLine($"init => this._f{slot} = value;");
                    sb.CloseBrace();
                }
                else
                {
                    sb.AppendLine($"public {field.TypeFullName} {field.Name} => ({field.TypeFullName})this._f{slot}!;");
                }
            }
        }
    }

    private static void EmitDeconstructs(
        SourceBuilder sb, IEnumerable<VariantInfo> variants, BoxedFieldsLayout layout)
    {
        var variantList = variants.ToList();
        if (variantList.Count == 0) return;

        var groups = GroupByFieldCount(variantList);
        var hasFieldlessVariants = groups.ContainsKey(0);

        if (groups.Count == 1 && hasFieldlessVariants)
        {
            sb.AppendLine();
            sb.AppendLine("public void Deconstruct(out Kind kind, out object? _f0)");
            sb.OpenBrace();
            sb.AppendLine("kind = this.kind;");
            sb.AppendLine("_f0 = null;");
            sb.CloseBrace();
            return;
        }

        var nonZeroGroups = groups
            .Where(g => g.Key > 0)
            .OrderBy(g => g.Key)
            .ToList();

        if (hasFieldlessVariants && nonZeroGroups.Count > 0)
        {
            var smallest = nonZeroGroups[0];
            if (smallest.Value.Count == 1)
                smallest.Value.AddRange(groups[0]);
        }

        foreach (var group in nonZeroGroups)
        {
            var groupVariants = group.Value;
            sb.AppendLine();

            if (groupVariants.Count == 1)
                EmitTypedDeconstruct(sb, groupVariants[0], layout);
            else
                EmitObjectDeconstruct(sb, group.Key, groupVariants, layout);
        }
    }

    private static void EmitTypedDeconstruct(
        SourceBuilder sb, VariantInfo variant, BoxedFieldsLayout layout)
    {
        var mapping = layout.Variants[variant.Name];

        var paramList = "out Kind kind";
        foreach (var field in variant.Fields)
            paramList += $", out {field.TypeFullName} {field.Name}";

        sb.AppendLine($"public void Deconstruct({paramList})");
        sb.OpenBrace();
        sb.AppendLine("kind = this.kind;");
        for (int i = 0; i < variant.Fields.Length; i++)
        {
            var field = variant.Fields[i];
            int slot = mapping.FieldToSlot[i];
            sb.AppendLine($"{field.Name} = ({field.TypeFullName})this._f{slot}!;");
        }
        sb.CloseBrace();
    }

    private static void EmitObjectDeconstruct(
        SourceBuilder sb, int fieldCount, List<VariantInfo> groupVariants, BoxedFieldsLayout layout)
    {
        var paramList = "out Kind kind";
        for (int i = 0; i < fieldCount; i++)
            paramList += $", out object? f{i}";

        sb.AppendLine($"public void Deconstruct({paramList})");
        sb.OpenBrace();
        sb.AppendLine("kind = this.kind;");

        // Need switch because different variants map fields to different slots
        var realVariants = groupVariants.Where(v => v.Fields.Length > 0).ToList();

        if (realVariants.Count > 0)
        {
            sb.AppendLine("switch (this.kind)");
            sb.OpenBrace();

            foreach (var variant in realVariants)
            {
                var mapping = layout.Variants[variant.Name];
                sb.AppendLine($"case Kind.{variant.Name}:");
                sb.Indent();
                for (int i = 0; i < variant.Fields.Length; i++)
                {
                    int slot = mapping.FieldToSlot[i];
                    sb.AppendLine($"f{i} = this._f{slot};");
                }
                sb.AppendLine("break;");
                sb.Dedent();
            }

            sb.AppendLine("default:");
            sb.Indent();
            for (int i = 0; i < fieldCount; i++)
                sb.AppendLine($"f{i} = null;");
            sb.AppendLine("break;");
            sb.Dedent();

            sb.CloseBrace(); // switch
        }
        else
        {
            for (int i = 0; i < fieldCount; i++)
                sb.AppendLine($"f{i} = null;");
        }

        sb.CloseBrace(); // method
    }

    private static Dictionary<int, List<VariantInfo>> GroupByFieldCount(List<VariantInfo> variants)
    {
        var groups = new Dictionary<int, List<VariantInfo>>();
        foreach (var v in variants)
        {
            int count = v.Fields.Length;
            if (!groups.TryGetValue(count, out var list))
            {
                list = new List<VariantInfo>();
                groups[count] = list;
            }
            list.Add(v);
        }
        return groups;
    }

    #endregion

    private static string FormatTypeParams(EquatableArray<string> typeParameters)
    {
        if (typeParameters.Length == 0) return "";
        return "<" + string.Join(", ", typeParameters) + ">";
    }
}
