// <auto-generated/>
#nullable enable

namespace TestNs
{
    public partial class Widget
    {
        public readonly struct SetInliner : global::Houtamelo.Spire.IActionInliner<global::TestNs.Widget, int>
        {
            public void Invoke(global::TestNs.Widget instance, int a1) => instance.Set(a1);
        }
    }
}
