// <auto-generated/>
#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

internal sealed class ShapeStjConverter : JsonConverter<Shape>
{
    public override Shape Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var doc = JsonDocument.ParseValue(ref reader);
        var root = doc.RootElement;
        if (!root.TryGetProperty("kind", out var kindProp))
            throw new JsonException("Missing discriminator property 'kind'");
        var kindStr = kindProp.GetString();
        return kindStr switch
        {
            "Circle" => Shape.Circle(root.GetProperty("radius").Deserialize<double>(options)!),
            "Rectangle" => Shape.Rectangle(root.GetProperty("width").Deserialize<float>(options)!, root.GetProperty("height").Deserialize<float>(options)!),
            "Point" => Shape.Point(),
            _ => throw new JsonException($"Unknown Shape variant: {kindStr}")
        };
    }

    public override void Write(Utf8JsonWriter writer, Shape value, JsonSerializerOptions options)
    {
        writer.WriteStartObject();
        switch (value.tag)
        {
            case Shape.Kind.Circle:
                writer.WriteString("kind", "Circle");
                writer.WritePropertyName("radius");
                JsonSerializer.Serialize(writer, value.circle_radius, options);
                break;
            case Shape.Kind.Rectangle:
                writer.WriteString("kind", "Rectangle");
                writer.WritePropertyName("width");
                JsonSerializer.Serialize(writer, value.rectangle.width, options);
                writer.WritePropertyName("height");
                JsonSerializer.Serialize(writer, value.rectangle.height, options);
                break;
            case Shape.Kind.Point:
                writer.WriteString("kind", "Point");
                break;
            default:
                throw new JsonException($"Unknown Shape variant: {value.tag}");
        }
        writer.WriteEndObject();
    }
}

[global::System.Text.Json.Serialization.JsonConverter(typeof(ShapeStjConverter))]
partial struct Shape { }
