// <auto-generated/>
#nullable enable
using System.ComponentModel;

[global::Spire.Analyzers.MustBeInit]
partial struct Option<T>
{
    public enum Kind : byte
    {
        Some,
        None,
    }

    public readonly Kind tag;
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal readonly T _s0;

    Option(Kind tag, T s0)
    {
        this.tag = tag;
        this._s0 = s0;
    }

    public static partial Option<T> Some(T value)
        => new Option<T>(Kind.Some, value);
    public static partial Option<T> None()
        => new Option<T>(Kind.None, default);

    public void Deconstruct(out Kind kind, out object? f0)
    {
        kind = this.tag;
        switch (this.tag)
        {
            case Kind.Some:
                f0 = this._s0;
                break;
            default:
                f0 = null;
                break;
        }
    }
    [EditorBrowsable(EditorBrowsableState.Never)]
    public T value => this._s0;
}
