// <auto-generated/>
#nullable enable
using System.ComponentModel;

[global::Spire.MustBeInit]
partial struct Option<T> : global::Spire.IDiscriminatedUnion<Option<T>.Kind>
{
    public enum Kind : byte
    {
        Some,
        None,
    }

    readonly Kind _kind;
    public Kind kind => this._kind;
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal T _s0 { get; init; }

    Option(Kind kind, T s0)
    {
        this._kind = kind;
        this._s0 = s0;
    }

    public static partial Option<T> Some(T value)
        => new Option<T>(Kind.Some, value);
    public static partial Option<T> None()
        => new Option<T>(Kind.None, default);

    public void Deconstruct(out Kind kind, out object? f0)
    {
        kind = this.kind;
        switch (this.kind)
        {
            case Kind.Some:
                f0 = this._s0;
                break;
            default:
                f0 = null;
                break;
        }
    }
    [EditorBrowsable(EditorBrowsableState.Never)]
    public T value
    {
        get => this._s0;
        init => this._s0 = value;
    }
    public bool IsSome => this.kind == Kind.Some;
    public bool IsNone => this.kind == Kind.None;
}
