// <auto-generated/>
#nullable enable

namespace TestNs
{
    public static partial class Samples
    {
        public readonly struct DoubleInliner : global::Houtamelo.Spire.IFuncInliner<int, int>
        {
            public int Invoke(int a1) => Samples.Double(a1);
        }
    }
}
