// <auto-generated/>
#nullable enable

namespace Traffic
{
    public abstract partial record Light
    {
        private Light() { }

        public sealed partial record Red;
        public sealed partial record Yellow;
        public sealed partial record Green;

        public bool IsRed => this is Red;
        public bool IsYellow => this is Yellow;
        public bool IsGreen => this is Green;
    }
}
