// <auto-generated/>
#nullable enable
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[global::Spire.Analyzers.MustBeInit]
partial struct Result<T>
{
    public enum Kind : byte
    {
        Ok,
        Err,
    }

    public readonly Kind tag;

    [InlineArray(4)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal struct _Buffer { internal byte _element; }

    [EditorBrowsable(EditorBrowsableState.Never)]
    internal _Buffer _data;

    [EditorBrowsable(EditorBrowsableState.Never)]
    internal T _s0;

    Result(Kind tag)
    {
        this.tag = tag;
        this._data = default;
        this._s0 = default!;
    }

    public static partial Result<T> Ok(T value, int code)
    {
        var s = new Result<T>(Kind.Ok);
        s._s0 = value;
        Unsafe.WriteUnaligned(ref s._data[0], code);
        return s;
    }
    public static partial Result<T> Err(int code)
    {
        var s = new Result<T>(Kind.Err);
        Unsafe.WriteUnaligned(ref s._data[0], code);
        return s;
    }

    public void Deconstruct(out Kind kind, out int code)
    {
        kind = this.tag;
        code = Unsafe.ReadUnaligned<int>(ref _data[0]);
    }

    public void Deconstruct(out Kind kind, out T value, out int code)
    {
        kind = this.tag;
        value = this._s0;
        code = Unsafe.ReadUnaligned<int>(ref _data[0]);
    }
}
