// <auto-generated/>
#nullable enable
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TestNs
{
    internal sealed class ShapeNsjConverter : JsonConverter<Shape>
    {
        public override Shape ReadJson(JsonReader reader, Type objectType, Shape? existingValue, bool hasExistingValue, JsonSerializer serializer)
        {
            var obj = JObject.Load(reader);
            var kindStr = obj["kind"]?.Value<string>()
                ?? throw new JsonSerializationException("Missing discriminator property 'kind'");
            return kindStr switch
            {
                "Circle" => new Shape.Circle(obj["Radius"]!.ToObject<double>(serializer)!),
                "Rectangle" => new Shape.Rectangle(obj["Width"]!.ToObject<float>(serializer)!, obj["Height"]!.ToObject<float>(serializer)!),
                "Point" => new Shape.Point(),
                _ => throw new JsonSerializationException($"Unknown Shape variant: {kindStr}")
            };
        }

        public override void WriteJson(JsonWriter writer, Shape? value, JsonSerializer serializer)
        {
            if (value is null) { writer.WriteNull(); return; }
            writer.WriteStartObject();
            switch (value)
            {
                case Shape.Circle _v:
                    writer.WritePropertyName("kind");
                    writer.WriteValue("Circle");
                    writer.WritePropertyName("Radius");
                    serializer.Serialize(writer, _v.Radius);
                    break;
                case Shape.Rectangle _v:
                    writer.WritePropertyName("kind");
                    writer.WriteValue("Rectangle");
                    writer.WritePropertyName("Width");
                    serializer.Serialize(writer, _v.Width);
                    writer.WritePropertyName("Height");
                    serializer.Serialize(writer, _v.Height);
                    break;
                case Shape.Point:
                    writer.WritePropertyName("kind");
                    writer.WriteValue("Point");
                    break;
                default:
                    throw new JsonSerializationException($"Unknown Shape variant: {value}");
            }
            writer.WriteEndObject();
        }
    }

    [Newtonsoft.Json.JsonConverter(typeof(ShapeNsjConverter))]
    public abstract partial record Shape { }
}
