// <auto-generated/>
#nullable enable

namespace TestNs
{
    public partial class Container
    {
        public abstract partial record Option<T>
        {
            private Option() { }

            public sealed partial record Some;
            public sealed partial record None;
        }
    }
}
