// <auto-generated/>
#nullable enable

namespace TestNs
{
    [global::Spire.Analyzers.MustBeInit]
    internal partial struct Option<T>
    {
        public enum Kind
        {
            Some,
            None,
        }

        public readonly Kind tag;
        readonly object? _payload;

        Option(Kind tag, object? payload)
        {
            this.tag = tag;
            this._payload = payload;
        }

        public static Option<T> NewSome(T value)
            => new Option<T>(Kind.Some, value);
        public static Option<T> NewNone()
            => new Option<T>(Kind.None, null);

        public void Deconstruct(out Kind kind, out object? payload)
        {
            kind = this.tag;
            payload = this._payload;
        }
    }
}
