// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.MustBeInit]
    partial struct Option<T>
    {
        public enum Kind : byte
        {
            Some,
            None,
        }

        public readonly Kind kind;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly object? _payload;

        Option(Kind kind, object? payload)
        {
            this.kind = kind;
            this._payload = payload;
        }

        public static partial Option<T> Some(T value)
            => new Option<T>(Kind.Some, value);
        public static partial Option<T> None()
            => new Option<T>(Kind.None, null);

        public void Deconstruct(out Kind kind, out object? payload)
        {
            kind = this.kind;
            payload = this._payload;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public T value => (T)this._payload!;
    }
}
