// <auto-generated/>
#nullable enable

using System;
using Houtamelo.Spire;

namespace TestNs
{
    public static partial class Lazy
    {
        public static R Get<R, TFactoryInliner>(TFactoryInliner factory)
            where TFactoryInliner : struct, global::Houtamelo.Spire.IFuncInliner<R>
        {
            return factory.Invoke();
        }
    }
}
