// <auto-generated/>
#nullable enable

partial struct Shape
{
    public static global::System.Lazy<string> JsonSchema { get; } = new(BuildJsonSchema);

    private static string BuildJsonSchema()
    {
        return @"{""oneOf"":[{""type"":""object"",""properties"":{""kind"":{""const"":""Circle""},""radius"":{""type"":""number""}},""required"":[""kind"",""radius""]},{""type"":""object"",""properties"":{""kind"":{""const"":""Square""},""sideLength"":{""type"":""integer""}},""required"":[""kind"",""sideLength""]},{""type"":""object"",""properties"":{""kind"":{""const"":""Point""}},""required"":[""kind""]}],""discriminator"":{""propertyName"":""kind""}}";
    }
}
