// <auto-generated/>
#nullable enable

namespace TestNs
{
    public static partial class Samples
    {
        public readonly struct OpInliner : global::Houtamelo.Spire.IActionInliner<int, int, int>
        {
            public void Invoke(int a1, int a2, int a3) => Samples.Op(a1, a2, a3);
        }
    }
}
