// <auto-generated/>
#nullable enable
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

internal sealed class TokenNsjConverter : JsonConverter<Token>
{
    public override Token ReadJson(JsonReader reader, Type objectType, Token existingValue, bool hasExistingValue, JsonSerializer serializer)
    {
        var obj = JObject.Load(reader);
        var kindStr = obj["kind"]?.Value<string>()
            ?? throw new JsonSerializationException("Missing discriminator property 'kind'");
        return kindStr switch
        {
            "Ident" => Token.Ident(),
            "Number" => Token.Number(),
            "Eof" => Token.Eof(),
            _ => throw new JsonSerializationException($"Unknown Token variant: {kindStr}")
        };
    }

    public override void WriteJson(JsonWriter writer, Token value, JsonSerializer serializer)
    {
        writer.WriteStartObject();
        switch (value)
        {
            case { kind: Token.Kind.Ident }:
            {
                writer.WritePropertyName("kind");
                writer.WriteValue("Ident");
                break;
            }
            case { kind: Token.Kind.Number }:
            {
                writer.WritePropertyName("kind");
                writer.WriteValue("Number");
                break;
            }
            case { kind: Token.Kind.Eof }:
            {
                writer.WritePropertyName("kind");
                writer.WriteValue("Eof");
                break;
            }
            default:
                throw new JsonSerializationException($"Unknown Token variant: {value.kind}");
        }
        writer.WriteEndObject();
    }
}

[Newtonsoft.Json.JsonConverter(typeof(TokenNsjConverter))]
partial struct Token { }
