// <auto-generated/>
#nullable enable
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[global::Spire.MustBeInit]
partial struct Shape : global::Spire.IDiscriminatedUnion<Shape.Kind>
{
    public enum Kind : byte
    {
        Circle,
        Rect,
        Point,
    }

    readonly Kind _kind;
    public Kind kind => this._kind;

    [InlineArray(16)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal struct _Buffer { internal byte _element; }

    [EditorBrowsable(EditorBrowsableState.Never)]
    internal _Buffer _data;

    Shape(Kind kind)
    {
        this._kind = kind;
        this._data = default;
    }

    public static partial Shape Circle(double radius)
    {
        var s = new Shape(Kind.Circle);
        Unsafe.WriteUnaligned(ref Unsafe.Add(ref s._data[0], 4), radius);
        return s;
    }
    public static partial Shape Rect(float width, float height)
    {
        var s = new Shape(Kind.Rect);
        Unsafe.WriteUnaligned(ref Unsafe.Add(ref s._data[0], 12), width);
        Unsafe.WriteUnaligned(ref s._data[0], height);
        return s;
    }
    public static partial Shape Point()
        => new Shape(Kind.Point);

    public void Deconstruct(out Kind kind, out object? f0)
    {
        kind = this.kind;
        switch (this.kind)
        {
            case Kind.Circle:
                f0 = Unsafe.ReadUnaligned<double>(ref Unsafe.Add(ref _data[0], 4));
                break;
            default:
                f0 = null;
                break;
        }
    }

    public void Deconstruct(out Kind kind, out float width, out float height)
    {
        kind = this.kind;
        width = Unsafe.ReadUnaligned<float>(ref Unsafe.Add(ref _data[0], 12));
        height = Unsafe.ReadUnaligned<float>(ref _data[0]);
    }
    [EditorBrowsable(EditorBrowsableState.Never)]
    public double radius
    {
        get => Unsafe.ReadUnaligned<double>(ref Unsafe.Add(ref _data[0], 4));
        init => Unsafe.WriteUnaligned(ref Unsafe.Add(ref _data[0], 4), value);
    }
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float width
    {
        get => Unsafe.ReadUnaligned<float>(ref Unsafe.Add(ref _data[0], 12));
        init => Unsafe.WriteUnaligned(ref Unsafe.Add(ref _data[0], 12), value);
    }
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float height
    {
        get => Unsafe.ReadUnaligned<float>(ref _data[0]);
        init => Unsafe.WriteUnaligned(ref _data[0], value);
    }
    public bool IsCircle => this.kind == Kind.Circle;
    public bool IsRect => this.kind == Kind.Rect;
    public bool IsPoint => this.kind == Kind.Point;
    public override string ToString()
    {
        return this.kind switch
        {
            Kind.Circle => $"Circle({this.radius})",
            Kind.Rect => $"Rect({this.width}, {this.height})",
            Kind.Point => "Point()",
            _ => "Shape(?)",
        };
    }
}
