// <auto-generated/>
#nullable enable
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[global::Spire.Analyzers.MustBeInit]
partial struct Shape
{
    public enum Kind : byte
    {
        Circle,
        Rect,
        Point,
    }

    public readonly Kind tag;

    [InlineArray(8)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal struct _Buffer { internal byte _element; }

    [EditorBrowsable(EditorBrowsableState.Never)]
    internal _Buffer _data;

    Shape(Kind tag)
    {
        this.tag = tag;
        this._data = default;
    }

    public static partial Shape Circle(double radius)
    {
        var s = new Shape(Kind.Circle);
        Unsafe.WriteUnaligned(ref s._data[0], radius);
        return s;
    }
    public static partial Shape Rect(float width, float height)
    {
        var s = new Shape(Kind.Rect);
        Unsafe.WriteUnaligned(ref s._data[0], width);
        Unsafe.WriteUnaligned(ref Unsafe.Add(ref s._data[0], 4), height);
        return s;
    }
    public static partial Shape Point()
        => new Shape(Kind.Point);

    public void Deconstruct(out Kind kind, out object? f0)
    {
        kind = this.tag;
        switch (this.tag)
        {
            case Kind.Circle:
                f0 = Unsafe.ReadUnaligned<double>(ref _data[0]);
                break;
            default:
                f0 = null;
                break;
        }
    }

    public void Deconstruct(out Kind kind, out float width, out float height)
    {
        kind = this.tag;
        width = Unsafe.ReadUnaligned<float>(ref _data[0]);
        height = Unsafe.ReadUnaligned<float>(ref Unsafe.Add(ref _data[0], 4));
    }
}
