// <auto-generated/>
#nullable enable

namespace TestNs
{
    [global::Spire.Analyzers.MustBeInit]
    internal readonly partial struct Immutable
    {
        public enum Kind
        {
            A,
            B,
        }

        public readonly Kind tag;
        readonly object? _payload;

        Immutable(Kind tag, object? payload)
        {
            this.tag = tag;
            this._payload = payload;
        }

        public static Immutable NewA(int x)
            => new Immutable(Kind.A, x);
        public static Immutable NewB(string y)
            => new Immutable(Kind.B, y);

        public void Deconstruct(out Kind kind, out object? payload)
        {
            kind = this.tag;
            payload = this._payload;
        }
    }
}
