// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.Analyzers.MustBeInit]
    readonly partial struct Immutable
    {
        public enum Kind : byte
        {
            A,
            B,
        }

        public readonly Kind kind;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly object? _payload;

        Immutable(Kind kind, object? payload)
        {
            this.kind = kind;
            this._payload = payload;
        }

        public static partial Immutable A(int x)
            => new Immutable(Kind.A, x);
        public static partial Immutable B(string y)
            => new Immutable(Kind.B, y);

        public void Deconstruct(out Kind kind, out object? payload)
        {
            kind = this.kind;
            payload = this._payload;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int x => (int)this._payload!;
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string y => (string)this._payload!;
    }
}
