// <auto-generated/>
#nullable enable
using System.ComponentModel;

[global::Houtamelo.Spire.Core.EnforceInitializationAttribute]
partial struct Shape : global::Houtamelo.Spire.Core.IDiscriminatedUnion<Shape.Kind>
{
    public enum Kind : byte
    {
        Circle,
        Rect,
        Square,
        Point,
    }

    readonly Kind _kind;
    public Kind kind => this._kind;
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal double _s0 { get; init; }
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal double _s1 { get; init; }
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal double _s2 { get; init; }
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal double _s3 { get; init; }

    Shape(Kind kind, double s0, double s1, double s2, double s3)
    {
        this._kind = kind;
        this._s0 = s0;
        this._s1 = s1;
        this._s2 = s2;
        this._s3 = s3;
    }

    public static partial Shape Circle(double radius)
        => new Shape(Kind.Circle, default, radius, default, default);
    public static partial Shape Rect(double width, double height)
        => new Shape(Kind.Rect, height, default, default, width);
    public static partial Shape Square(double side)
        => new Shape(Kind.Square, default, default, side, default);
    public static partial Shape Point()
        => new Shape(Kind.Point, default, default, default, default);

    public void Deconstruct(out Kind kind, out object? f0)
    {
        kind = this.kind;
        switch (this.kind)
        {
            case Kind.Circle:
                f0 = this._s1;
                break;
            case Kind.Square:
                f0 = this._s2;
                break;
            default:
                f0 = null;
                break;
        }
    }

    public void Deconstruct(out Kind kind, out double width, out double height)
    {
        kind = this.kind;
        width = this._s3;
        height = this._s0;
    }
    [EditorBrowsable(EditorBrowsableState.Never)]
    public double radius
    {
        get => this._s1;
        init => this._s1 = value;
    }
    [EditorBrowsable(EditorBrowsableState.Never)]
    public double width
    {
        get => this._s3;
        init => this._s3 = value;
    }
    [EditorBrowsable(EditorBrowsableState.Never)]
    public double height
    {
        get => this._s0;
        init => this._s0 = value;
    }
    [EditorBrowsable(EditorBrowsableState.Never)]
    public double side
    {
        get => this._s2;
        init => this._s2 = value;
    }
    public bool IsCircle => this.kind == Kind.Circle;
    public bool IsRect => this.kind == Kind.Rect;
    public bool IsSquare => this.kind == Kind.Square;
    public bool IsPoint => this.kind == Kind.Point;
    public override string ToString()
    {
        return this.kind switch
        {
            Kind.Circle => $"Circle({this.radius})",
            Kind.Rect => $"Rect({this.width}, {this.height})",
            Kind.Square => $"Square({this.side})",
            Kind.Point => "Point()",
            _ => "Shape(?)",
        };
    }
}
