// <auto-generated/>
#nullable enable

namespace TestNs
{
    public partial class Calc
    {
        public readonly struct MulInliner : global::Houtamelo.Spire.IFuncInliner<global::TestNs.Calc, int, int, int>
        {
            public int Invoke(global::TestNs.Calc instance, int a1, int a2) => instance.Mul(a1, a2);
        }
    }
}
