// <auto-generated/>
#nullable enable

namespace MyApp
{
    public abstract partial class Shape
    {
        private Shape() { }

        public sealed partial class Circle;
        public sealed partial class Rect;

        public bool IsCircle => this is Circle;
        public bool IsRect => this is Rect;
    }
}
