// <auto-generated/>
#nullable enable
using System.ComponentModel;

[global::Houtamelo.Spire.EnforceInitialization]
partial struct Shape : global::Houtamelo.Spire.IDiscriminatedUnion<Shape.Kind>
{
    public enum Kind : byte
    {
        Circle,
        Square,
        Point,
    }

    readonly Kind _kind;
    public Kind kind => this._kind;
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal double _s0 { get; init; }
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal int _s1 { get; init; }

    Shape(Kind kind, double s0, int s1)
    {
        this._kind = kind;
        this._s0 = s0;
        this._s1 = s1;
    }

    public static partial Shape Circle(double radius)
        => new Shape(Kind.Circle, radius, default);
    public static partial Shape Square(int sideLength)
        => new Shape(Kind.Square, default, sideLength);
    public static partial Shape Point()
        => new Shape(Kind.Point, default, default);

    public void Deconstruct(out Kind kind, out object? f0)
    {
        kind = this.kind;
        switch (this.kind)
        {
            case Kind.Circle:
                f0 = this._s0;
                break;
            case Kind.Square:
                f0 = this._s1;
                break;
            default:
                f0 = null;
                break;
        }
    }
    [EditorBrowsable(EditorBrowsableState.Never)]
    public double radius
    {
        get => this._s0;
        init => this._s0 = value;
    }
    [EditorBrowsable(EditorBrowsableState.Never)]
    public int sideLength
    {
        get => this._s1;
        init => this._s1 = value;
    }
    public bool IsCircle => this.kind == Kind.Circle;
    public bool IsSquare => this.kind == Kind.Square;
    public bool IsPoint => this.kind == Kind.Point;
    public override string ToString()
    {
        return this.kind switch
        {
            Kind.Circle => $"Circle({this.radius})",
            Kind.Square => $"Square({this.sideLength})",
            Kind.Point => "Point()",
            _ => "Shape(?)",
        };
    }
}
