// <auto-generated/>
#nullable enable

namespace MyApp
{
    internal abstract partial class Status
    {
        private Status() { }

        public sealed partial class Active;
        public sealed partial class Inactive;

        public bool IsActive => this is Active;
        public bool IsInactive => this is Inactive;
    }
}
