// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    [global::Houtamelo.Spire.Core.EnforceInitialization]
    readonly partial struct Immutable : global::Houtamelo.Spire.Core.IDiscriminatedUnion<Immutable.Kind>
    {
        public enum Kind : byte
        {
            A,
            B,
        }

        readonly Kind _kind;
        public Kind kind => this._kind;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal object? _payload { get; init; }

        Immutable(Kind kind, object? payload)
        {
            this._kind = kind;
            this._payload = payload;
        }

        public static partial Immutable A(int x)
            => new Immutable(Kind.A, x);
        public static partial Immutable B(string y)
            => new Immutable(Kind.B, y);

        public void Deconstruct(out Kind kind, out object? payload)
        {
            kind = this.kind;
            payload = this._payload;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int x
        {
            get => (int)this._payload!;
            init => this._payload = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string y
        {
            get => (string)this._payload!;
            init => this._payload = value;
        }
        public bool IsA => this.kind == Kind.A;
        public bool IsB => this.kind == Kind.B;
        public override string ToString()
        {
            return this.kind switch
            {
                Kind.A => $"A({this.x})",
                Kind.B => $"B({this.y})",
                _ => "Immutable(?)",
            };
        }
    }
}
