namespace Houtamelo.Spire.Analyzers.SourceGenerators.Attributes;

internal static class AttributeSource
{
    public const string Hint_DiscriminatedUnion = "DiscriminatedUnionAttribute.g.cs";
    public const string Hint_Variant = "VariantAttribute.g.cs";
    public const string Hint_Layout = "Layout.g.cs";
    public const string Hint_JsonLibrary = "JsonLibrary.g.cs";
    public const string Hint_JsonName = "JsonNameAttribute.g.cs";

    public const string DiscriminatedUnionAttribute = """
        // <auto-generated/>
        #nullable enable

        namespace Houtamelo.Spire
        {
            [global::System.AttributeUsage(
                global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class,
                Inherited = false)]
            internal sealed class DiscriminatedUnionAttribute : global::System.Attribute
            {
                public Layout Layout { get; }
                public bool GenerateDeconstruct { get; set; } = true;
                public JsonLibrary Json { get; set; } = JsonLibrary.None;
                public string JsonDiscriminator { get; set; } = "kind";
                public DiscriminatedUnionAttribute(Layout layout = Layout.Auto)
                    => Layout = layout;
            }
        }
        """;

    public const string VariantAttribute = """
        // <auto-generated/>
        #nullable enable

        namespace Houtamelo.Spire
        {
            [global::System.AttributeUsage(
                global::System.AttributeTargets.Method,
                Inherited = false)]
            internal sealed class VariantAttribute : global::System.Attribute { }
        }
        """;

    public const string LayoutEnum = """
        // <auto-generated/>

        namespace Houtamelo.Spire
        {
            internal enum Layout
            {
                Auto,
                Overlap,
                BoxedFields,
                BoxedTuple,
                Additive,
                UnsafeOverlap,
            }
        }
        """;

    public const string JsonLibraryEnum = """
        // <auto-generated/>

        namespace Houtamelo.Spire
        {
            [global::System.Flags]
            internal enum JsonLibrary
            {
                None = 0,
                SystemTextJson = 1,
                NewtonsoftJson = 2,
            }
        }
        """;

    public const string JsonNameAttribute = """
        // <auto-generated/>
        #nullable enable

        namespace Houtamelo.Spire
        {
            [global::System.AttributeUsage(
                global::System.AttributeTargets.Method
                | global::System.AttributeTargets.Class
                | global::System.AttributeTargets.Struct
                | global::System.AttributeTargets.Parameter,
                Inherited = false)]
            internal sealed class JsonNameAttribute : global::System.Attribute
            {
                public string Name { get; }
                public JsonNameAttribute(string name) => Name = name;
            }
        }
        """;
}
