// <auto-generated/>
#nullable enable

namespace Deep.Nested.Namespace
{
    public abstract partial class Token
    {
        private Token() { }

        public sealed partial class Ident;
        public sealed partial class Number;
    }
}
