// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    [global::Houtamelo.Spire.Core.EnforceInitializationAttribute]
    partial struct Option<T> : global::Houtamelo.Spire.Core.IDiscriminatedUnion<Option<T>.Kind>
    {
        public enum Kind : byte
        {
            Some,
            None,
        }

        readonly Kind _kind;
        public Kind kind => this._kind;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal object? _f0 { get; init; }

        Option(Kind kind, object? f0)
        {
            this._kind = kind;
            this._f0 = f0;
        }

        public static partial Option<T> Some(T value)
            => new Option<T>(Kind.Some, value);
        public static partial Option<T> None()
            => new Option<T>(Kind.None, null);

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.kind;
            switch (this.kind)
            {
                case Kind.Some:
                    f0 = this._f0;
                    break;
                default:
                    f0 = null;
                    break;
            }
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public T value
        {
            get => (T)this._f0!;
            init => this._f0 = value;
        }
        public bool IsSome => this.kind == Kind.Some;
        public bool IsNone => this.kind == Kind.None;
        public override string ToString()
        {
            return this.kind switch
            {
                Kind.Some => $"Some({this.value})",
                Kind.None => "None()",
                _ => "Option(?)",
            };
        }
    }
}
