// <auto-generated/>
#nullable enable

namespace TestNs
{
    [global::Spire.Analyzers.MustBeInit]
    internal partial struct Option<T>
    {
        public enum Kind
        {
            Some,
            None,
        }

        public readonly Kind tag;
        readonly object? _f0;

        Option(Kind tag, object? f0)
        {
            this.tag = tag;
            this._f0 = f0;
        }

        public static partial Option<T> Some(T value)
            => new Option<T>(Kind.Some, value);
        public static partial Option<T> None()
            => new Option<T>(Kind.None, null);

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.tag;
            f0 = this._f0;
        }
    }
}
