// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.MustBeInit]
    partial struct Option<T>
    {
        public enum Kind : byte
        {
            Some,
            None,
        }

        public readonly Kind kind;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly object? _f0;

        Option(Kind kind, object? f0)
        {
            this.kind = kind;
            this._f0 = f0;
        }

        public static partial Option<T> Some(T value)
            => new Option<T>(Kind.Some, value);
        public static partial Option<T> None()
            => new Option<T>(Kind.None, null);

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.kind;
            switch (this.kind)
            {
                case Kind.Some:
                    f0 = this._f0;
                    break;
                default:
                    f0 = null;
                    break;
            }
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public T value => (T)this._f0!;
    }
}
