// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    [global::Houtamelo.Spire.EnforceInitialization]
    partial struct Token : global::Houtamelo.Spire.IDiscriminatedUnion<Token.Kind>
    {
        public enum Kind : byte
        {
            Ident,
            Number,
            Eof,
        }

        readonly Kind _kind;
        public Kind kind => this._kind;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal object? _payload { get; init; }

        Token(Kind kind, object? payload)
        {
            this._kind = kind;
            this._payload = payload;
        }

        public static partial Token Ident(string name)
            => new Token(Kind.Ident, name);
        public static partial Token Number(int value)
            => new Token(Kind.Number, value);
        public static partial Token Eof()
            => new Token(Kind.Eof, null);

        public void Deconstruct(out Kind kind, out object? payload)
        {
            kind = this.kind;
            payload = this._payload;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string name
        {
            get => (string)this._payload!;
            init => this._payload = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int value
        {
            get => (int)this._payload!;
            init => this._payload = value;
        }
        public bool IsIdent => this.kind == Kind.Ident;
        public bool IsNumber => this.kind == Kind.Number;
        public bool IsEof => this.kind == Kind.Eof;
        public override string ToString()
        {
            return this.kind switch
            {
                Kind.Ident => $"Ident({this.name})",
                Kind.Number => $"Number({this.value})",
                Kind.Eof => "Eof()",
                _ => "Token(?)",
            };
        }
    }
}
