// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.Analyzers.MustBeInit]
    [StructLayout(LayoutKind.Explicit)]
    internal partial struct Event
    {
        public enum Kind
        {
            Click,
            Hover,
        }

        [FieldOffset(0)]
        public readonly Kind tag;

        [FieldOffset(4)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public readonly (int x, int y) click;

        [FieldOffset(4)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public readonly (float posX, float posY) hover;

        [FieldOffset(16)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public readonly string? click_target;

        Event(Kind tag) : this()
        {
            this.tag = tag;
        }

        public static partial Event Click(int x, int y, string target)
        {
            var s = new Event(Kind.Click);
            Unsafe.AsRef(in s.click) = (x, y);
            Unsafe.AsRef(in s.click_target) = target;
            return s;
        }
        public static partial Event Hover(float posX, float posY)
        {
            var s = new Event(Kind.Hover);
            Unsafe.AsRef(in s.hover) = (posX, posY);
            return s;
        }

        public void Deconstruct(out Kind kind, out float posX, out float posY)
        {
            kind = this.tag;
            posX = this.hover.posX;
            posY = this.hover.posY;
        }

        public void Deconstruct(out Kind kind, out int x, out int y, out string target)
        {
            kind = this.tag;
            x = this.click.x;
            y = this.click.y;
            target = this.click_target!;
        }
    }
}
