// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.MustBeInit]
    [StructLayout(LayoutKind.Explicit)]
    partial struct Shape
    {
        public enum Kind : byte
        {
            Circle,
            Rectangle,
            Square,
        }

        [FieldOffset(0)]
        public readonly Kind kind;

        [FieldOffset(1)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly float _height;

        [FieldOffset(5)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly double _radius;

        [FieldOffset(13)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly int _sideLength;

        [FieldOffset(17)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly float _width;

        Shape(Kind kind) : this()
        {
            this.kind = kind;
        }

        public static partial Shape Circle(double radius)
        {
            var s = new Shape(Kind.Circle);
            Unsafe.AsRef(in s._radius) = radius;
            return s;
        }
        public static partial Shape Rectangle(float width, float height)
        {
            var s = new Shape(Kind.Rectangle);
            Unsafe.AsRef(in s._width) = width;
            Unsafe.AsRef(in s._height) = height;
            return s;
        }
        public static partial Shape Square(int sideLength)
        {
            var s = new Shape(Kind.Square);
            Unsafe.AsRef(in s._sideLength) = sideLength;
            return s;
        }

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.kind;
            switch (this.kind)
            {
                case Kind.Circle:
                    f0 = this._radius;
                    break;
                case Kind.Square:
                    f0 = this._sideLength;
                    break;
                default:
                    f0 = null;
                    break;
            }
        }

        public void Deconstruct(out Kind kind, out float width, out float height)
        {
            kind = this.kind;
            width = this._width;
            height = this._height;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public float height => this._height;
        [EditorBrowsable(EditorBrowsableState.Never)]
        public double radius => this._radius;
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int sideLength => this._sideLength;
        [EditorBrowsable(EditorBrowsableState.Never)]
        public float width => this._width;
    }
}
