// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.Analyzers.MustBeInit]
    [StructLayout(LayoutKind.Explicit)]
    internal partial struct Shape
    {
        public enum Kind
        {
            Circle,
            Rectangle,
            Square,
        }

        [FieldOffset(0)]
        public readonly Kind tag;

        [FieldOffset(4)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public readonly double circle_radius;

        [FieldOffset(4)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public readonly (float width, float height) rectangle;

        [FieldOffset(4)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public readonly int square_sideLength;

        Shape(Kind tag) : this()
        {
            this.tag = tag;
        }

        public static Shape NewCircle(double radius)
        {
            var s = new Shape(Kind.Circle);
            Unsafe.AsRef(in s.circle_radius) = radius;
            return s;
        }
        public static Shape NewRectangle(float width, float height)
        {
            var s = new Shape(Kind.Rectangle);
            Unsafe.AsRef(in s.rectangle) = (width, height);
            return s;
        }
        public static Shape NewSquare(int sideLength)
        {
            var s = new Shape(Kind.Square);
            Unsafe.AsRef(in s.square_sideLength) = sideLength;
            return s;
        }

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.tag;
            switch (this.tag)
            {
                case Kind.Circle:
                    f0 = this.circle_radius;
                    break;
                case Kind.Square:
                    f0 = this.square_sideLength;
                    break;
                default:
                    f0 = null;
                    break;
            }
        }

        public void Deconstruct(out Kind kind, out float width, out float height)
        {
            kind = this.tag;
            width = this.rectangle.width;
            height = this.rectangle.height;
        }
    }
}
