// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.Analyzers.MustBeInit]
    partial struct Light
    {
        public enum Kind : byte
        {
            Red,
            Yellow,
            Green,
        }

        public readonly Kind kind;

        Light(Kind kind)
        {
            this.kind = kind;
        }

        public static partial Light Red()
            => new Light(Kind.Red);
        public static partial Light Yellow()
            => new Light(Kind.Yellow);
        public static partial Light Green()
            => new Light(Kind.Green);

        public void Deconstruct(out Kind kind, out object? _f0)
        {
            kind = this.kind;
            _f0 = null;
        }
    }
}
