// <auto-generated/>
#nullable enable

namespace TestNs
{
    internal partial struct Light
    {
        public enum Kind
        {
            Red,
            Yellow,
            Green,
        }

        public readonly Kind tag;

        Light(Kind tag)
        {
            this.tag = tag;
        }

        public static Light NewRed()
            => new Light(Kind.Red);
        public static Light NewYellow()
            => new Light(Kind.Yellow);
        public static Light NewGreen()
            => new Light(Kind.Green);

        public void Deconstruct(out Kind kind, out object? _f0)
        {
            kind = this.tag;
            _f0 = null;
        }
    }
}
