// <auto-generated/>
#nullable enable

namespace TestNs
{
    public static partial class Samples
    {
        public readonly struct LogInliner<T> : global::Houtamelo.Spire.IActionInliner<T>
        {
            public void Invoke(T a1) => Samples.Log<T>(a1);
        }
    }
}
