// <auto-generated/>
#nullable enable

namespace MyApp
{
    public abstract partial class Result<T, E>
    {
        private Result() { }

        public sealed partial class Ok;
        public sealed partial class Err;
    }
}
