// <auto-generated/>
#nullable enable

namespace TestNs
{
    internal readonly partial struct Immutable
    {
        public enum Kind
        {
            A,
            B,
        }

        public readonly Kind tag;
        readonly object? _f0;

        Immutable(Kind tag, object? f0)
        {
            this.tag = tag;
            this._f0 = f0;
        }

        public static Immutable NewA(int x)
            => new Immutable(Kind.A, x);
        public static Immutable NewB(string y)
            => new Immutable(Kind.B, y);

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.tag;
            f0 = this._f0;
        }
    }
}
