// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.Analyzers.MustBeInit]
    readonly partial struct Immutable
    {
        public enum Kind : byte
        {
            A,
            B,
        }

        public readonly Kind kind;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly object? _f0;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly object? _f1;

        Immutable(Kind kind, object? f0, object? f1)
        {
            this.kind = kind;
            this._f0 = f0;
            this._f1 = f1;
        }

        public static partial Immutable A(int x)
            => new Immutable(Kind.A, x, null);
        public static partial Immutable B(string y)
            => new Immutable(Kind.B, null, y);

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.kind;
            switch (this.kind)
            {
                case Kind.A:
                    f0 = this._f0;
                    break;
                case Kind.B:
                    f0 = this._f1;
                    break;
                default:
                    f0 = null;
                    break;
            }
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int x => (int)this._f0!;
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string y => (string)this._f1!;
    }
}
