// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace My.Deep.Namespace
{
    [global::Spire.MustBeInit]
    partial struct Result
    {
        public enum Kind : byte
        {
            Ok,
            Err,
        }

        public readonly Kind kind;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly object? _payload;

        Result(Kind kind, object? payload)
        {
            this.kind = kind;
            this._payload = payload;
        }

        public static partial Result Ok(int value)
            => new Result(Kind.Ok, value);
        public static partial Result Err(string message)
            => new Result(Kind.Err, message);

        public void Deconstruct(out Kind kind, out object? payload)
        {
            kind = this.kind;
            payload = this._payload;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int value => (int)this._payload!;
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string message => (string)this._payload!;
    }
}
