// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace My.Deep.Namespace
{
    [global::Spire.Analyzers.MustBeInit]
    partial struct Result
    {
        public enum Kind : byte
        {
            Ok,
            Err,
        }

        public readonly Kind tag;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly object? _payload;

        Result(Kind tag, object? payload)
        {
            this.tag = tag;
            this._payload = payload;
        }

        public static partial Result Ok(int value)
            => new Result(Kind.Ok, value);
        public static partial Result Err(string message)
            => new Result(Kind.Err, message);

        public void Deconstruct(out Kind kind, out object? payload)
        {
            kind = this.tag;
            payload = this._payload;
        }
    }
}
