// <auto-generated/>
#nullable enable

namespace My.Deep.Namespace
{
    internal partial struct Result
    {
        public enum Kind
        {
            Ok,
            Err,
        }

        public readonly Kind tag;
        readonly object? _payload;

        Result(Kind tag, object? payload)
        {
            this.tag = tag;
            this._payload = payload;
        }

        public static Result NewOk(int value)
            => new Result(Kind.Ok, value);
        public static Result NewErr(string message)
            => new Result(Kind.Err, message);

        public void Deconstruct(out Kind kind, out object? payload)
        {
            kind = this.tag;
            payload = this._payload;
        }
    }
}
