// <auto-generated/>
#nullable enable

namespace TestNs
{
    [global::Spire.Analyzers.MustBeInit]
    internal partial struct Token
    {
        public enum Kind
        {
            Ident,
            Number,
            Eof,
        }

        public readonly Kind tag;
        readonly object? _payload;

        Token(Kind tag, object? payload)
        {
            this.tag = tag;
            this._payload = payload;
        }

        public static Token NewIdent(string name)
            => new Token(Kind.Ident, name);
        public static Token NewNumber(int value)
            => new Token(Kind.Number, value);
        public static Token NewEof()
            => new Token(Kind.Eof, null);

        public void Deconstruct(out Kind kind, out object? payload)
        {
            kind = this.tag;
            payload = this._payload;
        }
    }
}
