// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.Analyzers.MustBeInit]
    partial struct Token
    {
        public enum Kind : byte
        {
            Ident,
            Number,
            Eof,
        }

        public readonly Kind kind;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly object? _payload;

        Token(Kind kind, object? payload)
        {
            this.kind = kind;
            this._payload = payload;
        }

        public static partial Token Ident(string name)
            => new Token(Kind.Ident, name);
        public static partial Token Number(int value)
            => new Token(Kind.Number, value);
        public static partial Token Eof()
            => new Token(Kind.Eof, null);

        public void Deconstruct(out Kind kind, out object? payload)
        {
            kind = this.kind;
            payload = this._payload;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string name => (string)this._payload!;
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int value => (int)this._payload!;
    }
}
