// <auto-generated/>
#nullable enable

namespace TestNs
{
    public static partial class Samples
    {
        public readonly struct RunInliner : global::Houtamelo.Spire.IActionInliner
        {
            public void Invoke() => Samples.Run();
        }
    }
}
