// <auto-generated/>
#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

internal sealed class TokenStjConverter : JsonConverter<Token>
{
    public override Token Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var doc = JsonDocument.ParseValue(ref reader);
        var root = doc.RootElement;
        if (!root.TryGetProperty("type", out var kindProp))
            throw new JsonException("Missing discriminator property 'type'");
        var kindStr = kindProp.GetString();
        return kindStr switch
        {
            "Number" => Token.Number(root.GetProperty("value").Deserialize<double>(options)!),
            "Eof" => Token.Eof(),
            _ => throw new JsonException($"Unknown Token variant: {kindStr}")
        };
    }

    public override void Write(Utf8JsonWriter writer, Token value, JsonSerializerOptions options)
    {
        writer.WriteStartObject();
        switch (value.tag)
        {
            case Token.Kind.Number:
                writer.WriteString("type", "Number");
                writer.WritePropertyName("value");
                JsonSerializer.Serialize(writer, value.value, options);
                break;
            case Token.Kind.Eof:
                writer.WriteString("type", "Eof");
                break;
            default:
                throw new JsonException($"Unknown Token variant: {value.tag}");
        }
        writer.WriteEndObject();
    }
}

[global::System.Text.Json.Serialization.JsonConverter(typeof(TokenStjConverter))]
partial struct Token { }
