// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace My.Deep.Namespace
{
    [global::Houtamelo.Spire.Core.EnforceInitialization]
    partial struct Result : global::Houtamelo.Spire.Core.IDiscriminatedUnion<Result.Kind>
    {
        public enum Kind : byte
        {
            Ok,
            Err,
        }

        readonly Kind _kind;
        public Kind kind => this._kind;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal object? _payload { get; init; }

        Result(Kind kind, object? payload)
        {
            this._kind = kind;
            this._payload = payload;
        }

        public static partial Result Ok(int value)
            => new Result(Kind.Ok, value);
        public static partial Result Err(string message)
            => new Result(Kind.Err, message);

        public void Deconstruct(out Kind kind, out object? payload)
        {
            kind = this.kind;
            payload = this._payload;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int value
        {
            get => (int)this._payload!;
            init => this._payload = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string message
        {
            get => (string)this._payload!;
            init => this._payload = value;
        }
        public bool IsOk => this.kind == Kind.Ok;
        public bool IsErr => this.kind == Kind.Err;
        public override string ToString()
        {
            return this.kind switch
            {
                Kind.Ok => $"Ok({this.value})",
                Kind.Err => $"Err({this.message})",
                _ => "Result(?)",
            };
        }
    }
}
