// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    public static partial class Unions
    {
        [global::Spire.Analyzers.MustBeInit]
        internal partial struct Token
        {
            public enum Kind : byte
            {
                Ident,
                Number,
            }

            public readonly Kind tag;
            [EditorBrowsable(EditorBrowsableState.Never)]
            internal readonly object? _f0;

            Token(Kind tag, object? f0)
            {
                this.tag = tag;
                this._f0 = f0;
            }

            public static partial Token Ident(string name)
                => new Token(Kind.Ident, name);
            public static partial Token Number(int value)
                => new Token(Kind.Number, value);

            public void Deconstruct(out Kind kind, out object? f0)
            {
                kind = this.tag;
                f0 = this._f0;
            }
        }
    }
}
