// <auto-generated/>
#nullable enable

namespace Geo
{
    public abstract partial record Shape
    {
        private Shape() { }

        public sealed partial record Rectangle;
        public sealed partial record Circle;

        public bool IsRectangle => this is Rectangle;
        public bool IsCircle => this is Circle;
    }
}
