// <auto-generated/>
#nullable enable
using System.ComponentModel;

namespace TestNs
{
    [global::Houtamelo.Spire.Core.EnforceInitialization]
    partial struct Option<T> : global::Houtamelo.Spire.Core.IDiscriminatedUnion<Option<T>.Kind>
    {
        public enum Kind : byte
        {
            Some,
            None,
        }

        readonly Kind _kind;
        public Kind kind => this._kind;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal object? _payload { get; init; }

        Option(Kind kind, object? payload)
        {
            this._kind = kind;
            this._payload = payload;
        }

        public static partial Option<T> Some(T value)
            => new Option<T>(Kind.Some, value);
        public static partial Option<T> None()
            => new Option<T>(Kind.None, null);

        public void Deconstruct(out Kind kind, out object? payload)
        {
            kind = this.kind;
            payload = this._payload;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public T value
        {
            get => (T)this._payload!;
            init => this._payload = value;
        }
        public bool IsSome => this.kind == Kind.Some;
        public bool IsNone => this.kind == Kind.None;
        public override string ToString()
        {
            return this.kind switch
            {
                Kind.Some => $"Some({this.value})",
                Kind.None => "None()",
                _ => "Option(?)",
            };
        }
    }
}
