// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.Analyzers.MustBeInit]
    [StructLayout(LayoutKind.Explicit)]
    internal partial struct Token
    {
        public enum Kind
        {
            Ident,
            Number,
            Eof,
        }

        [FieldOffset(0)]
        public readonly Kind tag;

        [FieldOffset(4)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public readonly int number_value;

        [FieldOffset(8)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public readonly string? ident_name;

        Token(Kind tag) : this()
        {
            this.tag = tag;
        }

        public static partial Token Ident(string name)
        {
            var s = new Token(Kind.Ident);
            Unsafe.AsRef(in s.ident_name) = name;
            return s;
        }
        public static partial Token Number(int value)
        {
            var s = new Token(Kind.Number);
            Unsafe.AsRef(in s.number_value) = value;
            return s;
        }
        public static partial Token Eof()
        {
            var s = new Token(Kind.Eof);
            return s;
        }

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.tag;
            switch (this.tag)
            {
                case Kind.Ident:
                    f0 = this.ident_name;
                    break;
                case Kind.Number:
                    f0 = this.number_value;
                    break;
                default:
                    f0 = null;
                    break;
            }
        }
    }
}
