// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.MustBeInit]
    [StructLayout(LayoutKind.Explicit)]
    partial struct Token : global::Spire.IDiscriminatedUnion<Token.Kind>
    {
        public enum Kind : byte
        {
            Ident,
            Number,
            Eof,
        }

        [FieldOffset(0)]
        readonly Kind _kind;
        public Kind kind => this._kind;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [FieldOffset(1)]
        internal readonly int _value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [FieldOffset(8)]
        internal readonly string? _name;

        Token(Kind kind) : this()
        {
            this._kind = kind;
        }

        public static partial Token Ident(string name)
        {
            var s = new Token(Kind.Ident);
            Unsafe.AsRef(in s._name) = name;
            return s;
        }
        public static partial Token Number(int value)
        {
            var s = new Token(Kind.Number);
            Unsafe.AsRef(in s._value) = value;
            return s;
        }
        public static partial Token Eof()
            => new Token(Kind.Eof);

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.kind;
            switch (this.kind)
            {
                case Kind.Ident:
                    f0 = this._name;
                    break;
                case Kind.Number:
                    f0 = this._value;
                    break;
                default:
                    f0 = null;
                    break;
            }
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int value
        {
            get => this._value;
            init => this._value = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string name
        {
            get => this._name!;
            init => this._name = value;
        }
        public bool IsIdent => this.kind == Kind.Ident;
        public bool IsNumber => this.kind == Kind.Number;
        public bool IsEof => this.kind == Kind.Eof;
        public override string ToString()
        {
            return this.kind switch
            {
                Kind.Ident => $"Ident({this.name})",
                Kind.Number => $"Number({this.value})",
                Kind.Eof => "Eof()",
                _ => "Token(?)",
            };
        }
    }
}
