// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.MustBeInit]
    [StructLayout(LayoutKind.Explicit)]
    partial struct Token
    {
        public enum Kind : byte
        {
            Ident,
            Number,
            Eof,
        }

        [FieldOffset(0)]
        public readonly Kind kind;

        [FieldOffset(1)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly int _value;

        [FieldOffset(8)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly string? _name;

        Token(Kind kind) : this()
        {
            this.kind = kind;
        }

        public static partial Token Ident(string name)
        {
            var s = new Token(Kind.Ident);
            Unsafe.AsRef(in s._name) = name;
            return s;
        }
        public static partial Token Number(int value)
        {
            var s = new Token(Kind.Number);
            Unsafe.AsRef(in s._value) = value;
            return s;
        }
        public static partial Token Eof()
            => new Token(Kind.Eof);

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.kind;
            switch (this.kind)
            {
                case Kind.Ident:
                    f0 = this._name;
                    break;
                case Kind.Number:
                    f0 = this._value;
                    break;
                default:
                    f0 = null;
                    break;
            }
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int value => this._value;
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string name => this._name!;
    }
}
