// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.MustBeInit]
    [StructLayout(LayoutKind.Explicit)]
    readonly partial struct Immutable : global::Spire.IDiscriminatedUnion<Immutable.Kind>
    {
        public enum Kind : byte
        {
            A,
            B,
        }

        [FieldOffset(0)]
        readonly Kind _kind;
        public Kind kind => this._kind;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [FieldOffset(1)]
        internal readonly int _x;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [FieldOffset(8)]
        internal readonly string? _y;

        Immutable(Kind kind) : this()
        {
            this._kind = kind;
        }

        public static partial Immutable A(int x)
        {
            var s = new Immutable(Kind.A);
            Unsafe.AsRef(in s._x) = x;
            return s;
        }
        public static partial Immutable B(string y)
        {
            var s = new Immutable(Kind.B);
            Unsafe.AsRef(in s._y) = y;
            return s;
        }

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.kind;
            switch (this.kind)
            {
                case Kind.A:
                    f0 = this._x;
                    break;
                case Kind.B:
                    f0 = this._y;
                    break;
                default:
                    f0 = null;
                    break;
            }
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int x
        {
            get => this._x;
            init => this._x = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string y
        {
            get => this._y!;
            init => this._y = value;
        }
        public bool IsA => this.kind == Kind.A;
        public bool IsB => this.kind == Kind.B;
    }
}
