// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;

namespace TestNs
{
    [global::Spire.Analyzers.MustBeInit]
    [StructLayout(LayoutKind.Explicit)]
    readonly partial struct Immutable
    {
        public enum Kind : byte
        {
            A,
            B,
        }

        [FieldOffset(0)]
        public readonly Kind tag;

        [FieldOffset(1)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly int _x;

        [FieldOffset(8)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal readonly string? _y;

        Immutable(Kind tag) : this()
        {
            this.tag = tag;
        }

        public static partial Immutable A(int x)
        {
            var s = new Immutable(Kind.A);
            Unsafe.AsRef(in s._x) = x;
            return s;
        }
        public static partial Immutable B(string y)
        {
            var s = new Immutable(Kind.B);
            Unsafe.AsRef(in s._y) = y;
            return s;
        }

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.tag;
            switch (this.tag)
            {
                case Kind.A:
                    f0 = this._x;
                    break;
                case Kind.B:
                    f0 = this._y;
                    break;
                default:
                    f0 = null;
                    break;
            }
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int x => this._x;
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string y => this._y!;
    }
}
