// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;

namespace TestNs
{
    [StructLayout(LayoutKind.Explicit)]
    internal readonly partial struct Immutable
    {
        public enum Kind
        {
            A,
            B,
        }

        [FieldOffset(0)]
        public readonly Kind tag;

        [FieldOffset(4)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public readonly int a_x;

        [FieldOffset(8)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public readonly string? b_y;

        Immutable(Kind tag) : this()
        {
            this.tag = tag;
        }

        public static Immutable NewA(int x)
        {
            var s = new Immutable(Kind.A);
            Unsafe.AsRef(in s.a_x) = x;
            return s;
        }
        public static Immutable NewB(string y)
        {
            var s = new Immutable(Kind.B);
            Unsafe.AsRef(in s.b_y) = y;
            return s;
        }

        public void Deconstruct(out Kind kind, out object? f0)
        {
            kind = this.tag;
            switch (this.tag)
            {
                case Kind.A:
                    f0 = this.a_x;
                    break;
                case Kind.B:
                    f0 = this.b_y;
                    break;
                default:
                    f0 = null;
                    break;
            }
        }
    }
}
