using System.Collections.Generic;
using System.Linq;
using Spire.SourceGenerators.Model;

namespace Spire.SourceGenerators.Emit;

/// Generates struct unions using typed fields with type-based deduplication.
/// Value types: deduplicated by concrete type. Reference types: shared as object?.
/// No boxing for value types, no StructLayout.Explicit — works with generics.
internal static class AdditiveEmitter
{
    public static string Emit(UnionDeclaration union)
    {
        var sb = new SourceBuilder();
        var layout = ComputeLayout(union.Variants);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(union.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {union.Namespace}");
            sb.OpenBrace();
        }

        sb.OpenContainingTypes(union.ContainingTypes);

        var typeParams = FormatTypeParams(union.TypeParameters);
        var unionType = union.TypeName + typeParams;
        var accessMod = string.IsNullOrEmpty(union.AccessibilityKeyword) ? "" : union.AccessibilityKeyword + " ";
        var readonlyMod = union.IsReadonly ? "readonly " : "";
        var refMod = union.IsRefStruct ? "ref " : "";

        sb.AppendLine("[global::Spire.MustBeInit]");
        sb.AppendLine($"{accessMod}{readonlyMod}{refMod}partial {union.DeclarationKeyword} {unionType} : global::Spire.IDiscriminatedUnion<{unionType}.Kind>");
        sb.OpenBrace();

        // Kind enum
        var kindType = OverlapLayoutComputer.KindTypeName(union.Variants.Length);
        sb.AppendLine($"public enum Kind : {kindType}");
        sb.OpenBrace();
        foreach (var variant in union.Variants)
            sb.AppendLine($"{variant.Name},");
        sb.CloseBrace();
        sb.AppendLine();

        // Kind field (backing field + property)
        sb.AppendLine("readonly Kind _kind;");
        sb.AppendLine("public Kind kind => this._kind;");

        // Slot fields
        foreach (var slot in layout.Slots)
        {
            sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
            var slotType = slot.IsRefSlot ? "object?" : slot.TypeFullName;
            if (union.HasInitProperties)
                sb.AppendLine($"internal {slotType} _s{slot.Index} {{ get; init; }}");
            else
                sb.AppendLine($"internal readonly {slotType} _s{slot.Index};");
        }
        sb.AppendLine();

        // Constructor
        EmitConstructor(sb, union.TypeName, layout.Slots);
        sb.AppendLine();

        // Factory methods
        EmitFactories(sb, union, unionType, layout);

        // Deconstruct overloads
        if (union.GenerateDeconstruct)
            EmitDeconstructs(sb, union.Variants, layout);

        // Public properties for pattern matching
        EmitProperties(sb, union.Variants, layout, union.HasInitProperties);

        // IsVariant properties
        foreach (var variant in union.Variants)
            sb.AppendLine($"public bool Is{variant.Name} => this.kind == Kind.{variant.Name};");

        ToStringEmitter.EmitStructToString(sb, union);

        sb.CloseBrace(); // type

        sb.CloseContainingTypes(union.ContainingTypes);

        if (hasNamespace)
            sb.CloseBrace();

        return sb.ToString();
    }

    #region Layout computation

    internal sealed class AdditiveLayout
    {
        public List<SlotInfo> Slots = new List<SlotInfo>();
        public Dictionary<string, VariantMapping> Variants = new Dictionary<string, VariantMapping>();
    }

    internal sealed class SlotInfo
    {
        public int Index;
        public string TypeFullName = "";
        /// True if this slot stores reference types as object?.
        public bool IsRefSlot;
    }

    internal sealed class VariantMapping
    {
        /// Maps field index (within the variant) to slot index.
        public List<int> FieldToSlot = new List<int>();
    }

    /// Slot type key: known reference types collapse to "object?", everything else by concrete type.
    private static string SlotTypeKey(FieldInfo field)
    {
        return field.IsReferenceType ? "object?" : field.TypeFullName;
    }

    internal static AdditiveLayout ComputeLayout(IEnumerable<VariantInfo> variants)
    {
        return ComputeLayoutNamePinned(variants.ToList());
    }

    /// Name-pinned slot assignment. Each unique field name gets a dedicated slot.
    /// Same-name-same-type fields across variants share the same slot.
    private static AdditiveLayout ComputeLayoutNamePinned(List<VariantInfo> variantList)
    {
        var layout = new AdditiveLayout();

        // Collect unique (fieldName → typeKey). Name conflicts (same name, different type)
        // are rejected by the generator diagnostic — not expected here.
        var fieldTypeKeys = new Dictionary<string, string>();
        foreach (var variant in variantList)
        {
            foreach (var field in variant.Fields)
            {
                var key = SlotTypeKey(field);
                if (!fieldTypeKeys.ContainsKey(field.Name))
                    fieldTypeKeys[field.Name] = key;
            }
        }

        // Create one slot per unique field name, sorted by (typeKey, fieldName)
        int slotIndex = 0;
        var nameToSlot = new Dictionary<string, int>();
        foreach (var kv in fieldTypeKeys.OrderBy(x => x.Value).ThenBy(x => x.Key))
        {
            bool isRef = kv.Value == "object?";
            layout.Slots.Add(new SlotInfo
            {
                Index = slotIndex,
                TypeFullName = kv.Value,
                IsRefSlot = isRef,
            });
            nameToSlot[kv.Key] = slotIndex;
            slotIndex++;
        }

        // Map each variant's fields to their pinned slots by name
        foreach (var variant in variantList)
        {
            var mapping = new VariantMapping();
            foreach (var field in variant.Fields)
                mapping.FieldToSlot.Add(nameToSlot[field.Name]);

            layout.Variants[variant.Name] = mapping;
        }

        return layout;
    }

    #endregion

    #region Emit helpers

    private static void EmitConstructor(SourceBuilder sb, string typeName, List<SlotInfo> slots)
    {
        var paramList = "Kind kind";
        foreach (var slot in slots)
        {
            var slotType = slot.IsRefSlot ? "object?" : slot.TypeFullName;
            paramList += $", {slotType} s{slot.Index}";
        }

        sb.AppendLine($"{typeName}({paramList})");
        sb.OpenBrace();
        sb.AppendLine("this._kind = kind;");
        foreach (var slot in slots)
            sb.AppendLine($"this._s{slot.Index} = s{slot.Index};");
        sb.CloseBrace();
    }

    private static void EmitFactories(
        SourceBuilder sb, UnionDeclaration union, string unionType, AdditiveLayout layout)
    {
        foreach (var variant in union.Variants)
        {
            var mapping = layout.Variants[variant.Name];
            var typedParams = string.Join(", ",
                variant.Fields.Select(f => $"{f.TypeFullName} {f.Name}"));

            // Build constructor args: kind + one arg per slot
            var args = new string[layout.Slots.Count];
            for (int i = 0; i < args.Length; i++)
            {
                var slot = layout.Slots[i];
                args[i] = slot.IsRefSlot ? "default!" : "default";
            }

            // Fill in the variant's fields
            for (int fi = 0; fi < variant.Fields.Length; fi++)
            {
                int slotIdx = mapping.FieldToSlot[fi];
                args[slotIdx] = variant.Fields[fi].Name;
            }

            var ctorArgs = "Kind." + variant.Name;
            if (args.Length > 0)
                ctorArgs += ", " + string.Join(", ", args);

            sb.AppendLine($"public static partial {unionType} {variant.Name}({typedParams})");
            sb.AppendLine($"    => new {unionType}({ctorArgs});");
        }
    }

    private static void EmitProperties(
        SourceBuilder sb, IEnumerable<VariantInfo> variants, AdditiveLayout layout, bool hasInitProperties)
    {
        var emitted = new HashSet<string>();
        foreach (var variant in variants)
        {
            var mapping = layout.Variants[variant.Name];
            for (int i = 0; i < variant.Fields.Length; i++)
            {
                var field = variant.Fields[i];
                if (!emitted.Add(field.Name)) continue;

                int slot = mapping.FieldToSlot[i];
                var slotInfo = layout.Slots[slot];

                sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
                if (hasInitProperties)
                {
                    sb.AppendLine($"public {field.TypeFullName} {field.Name}");
                    sb.OpenBrace();
                    if (slotInfo.IsRefSlot)
                        sb.AppendLine($"get => ({field.TypeFullName})this._s{slot}!;");
                    else
                        sb.AppendLine($"get => this._s{slot};");
                    sb.AppendLine($"init => this._s{slot} = value;");
                    sb.CloseBrace();
                }
                else
                {
                    if (slotInfo.IsRefSlot)
                        sb.AppendLine($"public {field.TypeFullName} {field.Name} => ({field.TypeFullName})this._s{slot}!;");
                    else
                        sb.AppendLine($"public {field.TypeFullName} {field.Name} => this._s{slot};");
                }
            }
        }
    }

    private static void EmitDeconstructs(
        SourceBuilder sb, IEnumerable<VariantInfo> variants, AdditiveLayout layout)
    {
        var variantList = variants.ToList();
        if (variantList.Count == 0) return;

        var groups = GroupByFieldCount(variantList);
        var hasFieldlessVariants = groups.ContainsKey(0);

        if (groups.Count == 1 && hasFieldlessVariants)
        {
            sb.AppendLine();
            sb.AppendLine("public void Deconstruct(out Kind kind, out object? _f0)");
            sb.OpenBrace();
            sb.AppendLine("kind = this.kind;");
            sb.AppendLine("_f0 = null;");
            sb.CloseBrace();
            return;
        }

        var nonZeroGroups = groups
            .Where(g => g.Key > 0)
            .OrderBy(g => g.Key)
            .ToList();

        if (hasFieldlessVariants && nonZeroGroups.Count > 0)
        {
            var smallest = nonZeroGroups[0];
            if (smallest.Value.Count == 1)
                smallest.Value.AddRange(groups[0]);
        }

        foreach (var group in nonZeroGroups)
        {
            var groupVariants = group.Value;
            sb.AppendLine();

            if (groupVariants.Count == 1)
                EmitTypedDeconstruct(sb, groupVariants[0], layout);
            else
                EmitObjectDeconstruct(sb, group.Key, groupVariants, layout);
        }
    }

    private static void EmitTypedDeconstruct(
        SourceBuilder sb, VariantInfo variant, AdditiveLayout layout)
    {
        var mapping = layout.Variants[variant.Name];

        var paramList = "out Kind kind";
        foreach (var field in variant.Fields)
            paramList += $", out {field.TypeFullName} {field.Name}";

        sb.AppendLine($"public void Deconstruct({paramList})");
        sb.OpenBrace();
        sb.AppendLine("kind = this.kind;");

        for (int i = 0; i < variant.Fields.Length; i++)
        {
            var field = variant.Fields[i];
            int slot = mapping.FieldToSlot[i];
            var slotInfo = layout.Slots[slot];

            if (slotInfo.IsRefSlot)
                sb.AppendLine($"{field.Name} = ({field.TypeFullName})this._s{slot}!;");
            else
                sb.AppendLine($"{field.Name} = this._s{slot};");
        }

        sb.CloseBrace();
    }

    private static void EmitObjectDeconstruct(
        SourceBuilder sb, int fieldCount, List<VariantInfo> variants, AdditiveLayout layout)
    {
        var paramList = "out Kind kind";
        for (int i = 0; i < fieldCount; i++)
            paramList += $", out object? f{i}";

        sb.AppendLine($"public void Deconstruct({paramList})");
        sb.OpenBrace();
        sb.AppendLine("kind = this.kind;");
        sb.AppendLine("switch (this.kind)");
        sb.OpenBrace();

        foreach (var variant in variants)
        {
            if (variant.Fields.Length == 0)
                continue;

            var mapping = layout.Variants[variant.Name];
            sb.AppendLine($"case Kind.{variant.Name}:");
            sb.Indent();
            for (int i = 0; i < variant.Fields.Length; i++)
            {
                var field = variant.Fields[i];
                int slot = mapping.FieldToSlot[i];
                var slotInfo = layout.Slots[slot];

                if (slotInfo.IsRefSlot)
                    sb.AppendLine($"f{i} = this._s{slot};");
                else
                    sb.AppendLine($"f{i} = this._s{slot};");
            }
            sb.AppendLine("break;");
            sb.Dedent();
        }

        sb.AppendLine("default:");
        sb.Indent();
        for (int i = 0; i < fieldCount; i++)
            sb.AppendLine($"f{i} = null;");
        sb.AppendLine("break;");
        sb.Dedent();

        sb.CloseBrace(); // switch
        sb.CloseBrace(); // method
    }

    private static Dictionary<int, List<VariantInfo>> GroupByFieldCount(List<VariantInfo> variants)
    {
        var groups = new Dictionary<int, List<VariantInfo>>();
        foreach (var v in variants)
        {
            int count = v.Fields.Length;
            if (!groups.TryGetValue(count, out var list))
            {
                list = new List<VariantInfo>();
                groups[count] = list;
            }
            list.Add(v);
        }
        return groups;
    }

    private static string FormatTypeParams(EquatableArray<string> typeParameters)
    {
        if (typeParameters.Length == 0) return "";
        return "<" + string.Join(", ", typeParameters) + ">";
    }

    #endregion
}
