// <auto-generated/>
#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TestNs
{
    internal sealed class ShapeStjConverter : JsonConverter<Shape>
    {
        public override Shape Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            using var doc = JsonDocument.ParseValue(ref reader);
            var root = doc.RootElement;
            if (!root.TryGetProperty("kind", out var kindProp))
                throw new JsonException("Missing discriminator property 'kind'");
            var kindStr = kindProp.GetString();
            return kindStr switch
            {
                "Circle" => new Shape.Circle(root.GetProperty("Radius").Deserialize<double>(options)!),
                "Rectangle" => new Shape.Rectangle(root.GetProperty("Width").Deserialize<float>(options)!, root.GetProperty("Height").Deserialize<float>(options)!),
                "Point" => new Shape.Point(),
                _ => throw new JsonException($"Unknown Shape variant: {kindStr}")
            };
        }

        public override void Write(Utf8JsonWriter writer, Shape value, JsonSerializerOptions options)
        {
            writer.WriteStartObject();
            switch (value)
            {
                case Shape.Circle _v:
                    writer.WriteString("kind", "Circle");
                    writer.WritePropertyName("Radius");
                    JsonSerializer.Serialize(writer, _v.Radius, options);
                    break;
                case Shape.Rectangle _v:
                    writer.WriteString("kind", "Rectangle");
                    writer.WritePropertyName("Width");
                    JsonSerializer.Serialize(writer, _v.Width, options);
                    writer.WritePropertyName("Height");
                    JsonSerializer.Serialize(writer, _v.Height, options);
                    break;
                case Shape.Point:
                    writer.WriteString("kind", "Point");
                    break;
                default:
                    throw new JsonException($"Unknown Shape variant: {value}");
            }
            writer.WriteEndObject();
        }
    }

    [global::System.Text.Json.Serialization.JsonConverter(typeof(ShapeStjConverter))]
    public abstract partial record Shape { }
}
