// <auto-generated/>
#nullable enable

using System;
using Houtamelo.Spire;

namespace TestNs
{
    public static partial class Aliases
    {
        public static void Run<TActionInliner>(int x, TActionInliner action)
            where TActionInliner : struct, global::Houtamelo.Spire.IActionInliner<int>
        {
            var a = action;
            a.Invoke(x);
        }
    }
}
