// <auto-generated/>
#nullable enable
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace TestNs
{
    [global::Houtamelo.Spire.Core.EnforceInitializationAttribute]
    partial struct Event : global::Houtamelo.Spire.Core.IDiscriminatedUnion<Event.Kind>
    {
        public enum Kind : byte
        {
            Click,
            Error,
            Ping,
        }

        readonly Kind _kind;
        public Kind kind => this._kind;

        [InlineArray(8)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal struct _Buffer { internal byte _element; }

        [EditorBrowsable(EditorBrowsableState.Never)]
        internal _Buffer _data;

        [EditorBrowsable(EditorBrowsableState.Never)]
        internal object? _s0;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal object? _s1;
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal object? _s2;

        Event(Kind kind)
        {
            this._kind = kind;
            this._data = default;
            this._s0 = default!;
            this._s1 = default!;
            this._s2 = default!;
        }

        public static partial Event Click(int x, int y, string target)
        {
            var s = new Event(Kind.Click);
            Unsafe.WriteUnaligned(ref s._data[0], x);
            Unsafe.WriteUnaligned(ref Unsafe.Add(ref s._data[0], 4), y);
            s._s2 = target;
            return s;
        }
        public static partial Event Error(string message, global::System.Exception ex)
        {
            var s = new Event(Kind.Error);
            s._s1 = message;
            s._s0 = ex;
            return s;
        }
        public static partial Event Ping()
            => new Event(Kind.Ping);

        public void Deconstruct(out Kind kind, out object? f0, out object? f1)
        {
            kind = this.kind;
            switch (this.kind)
            {
                case Kind.Error:
                    f0 = this._s1;
                    f1 = this._s0;
                    break;
                default:
                    f0 = null;
                    f1 = null;
                    break;
            }
        }

        public void Deconstruct(out Kind kind, out int x, out int y, out string target)
        {
            kind = this.kind;
            x = Unsafe.ReadUnaligned<int>(ref _data[0]);
            y = Unsafe.ReadUnaligned<int>(ref Unsafe.Add(ref _data[0], 4));
            target = (string)this._s2!;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int x
        {
            get => Unsafe.ReadUnaligned<int>(ref _data[0]);
            init => Unsafe.WriteUnaligned(ref _data[0], value);
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public int y
        {
            get => Unsafe.ReadUnaligned<int>(ref Unsafe.Add(ref _data[0], 4));
            init => Unsafe.WriteUnaligned(ref Unsafe.Add(ref _data[0], 4), value);
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string target
        {
            get => (string)this._s2!;
            init => this._s2 = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string message
        {
            get => (string)this._s1!;
            init => this._s1 = value;
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public global::System.Exception ex
        {
            get => (global::System.Exception)this._s0!;
            init => this._s0 = value;
        }
        public bool IsClick => this.kind == Kind.Click;
        public bool IsError => this.kind == Kind.Error;
        public bool IsPing => this.kind == Kind.Ping;
        public override string ToString()
        {
            return this.kind switch
            {
                Kind.Click => $"Click({this.x}, {this.y}, {this.target})",
                Kind.Error => $"Error({this.message}, {this.ex})",
                Kind.Ping => "Ping()",
                _ => "Event(?)",
            };
        }
    }
}
