// <auto-generated/>
#nullable enable

using System;
using Houtamelo.Spire;

namespace TestNs
{
    public static partial class Pipeline
    {
        public static R Run<T, R, TPreInliner, TPostInliner>(T seed, TPreInliner pre, TPostInliner post)
            where TPreInliner : struct, global::Houtamelo.Spire.IFuncInliner<T, T>
            where TPostInliner : struct, global::Houtamelo.Spire.IFuncInliner<T, R>
            => post.Invoke(pre.Invoke(seed));
    }
}
