// <auto-generated/>
#nullable enable
using System;
using System.Collections.Concurrent;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TestNs
{
    internal sealed class OptionNsjConverterFactory : JsonConverter
    {
        private static readonly ConcurrentDictionary<Type, JsonConverter> _cache = new();

        public override bool CanConvert(Type objectType)
            => objectType.IsGenericType && objectType.GetGenericTypeDefinition() == typeof(Option<>);

        public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)
        {
            return GetOrCreate(objectType).ReadJson(reader, objectType, existingValue, serializer);
        }

        public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
        {
            if (value is null) { writer.WriteNull(); return; }
            GetOrCreate(value.GetType()).WriteJson(writer, value, serializer);
        }

        private JsonConverter GetOrCreate(Type objectType)
        {
            return _cache.GetOrAdd(objectType, t =>
            {
                var converterType = typeof(OptionNsjConverter<>).MakeGenericType(t.GetGenericArguments());
                return (JsonConverter)Activator.CreateInstance(converterType)!;
            });
        }
    }

    internal sealed class OptionNsjConverter<T> : JsonConverter<Option<T>>
    {
        public override Option<T> ReadJson(JsonReader reader, Type objectType, Option<T>? existingValue, bool hasExistingValue, JsonSerializer serializer)
        {
            var obj = JObject.Load(reader);
            var kindStr = obj["kind"]?.Value<string>()
                ?? throw new JsonSerializationException("Missing discriminator property 'kind'");
            return kindStr switch
            {
                "Some" => new Option<T>.Some(obj["Value"]!.ToObject<T>(serializer)!),
                "None" => new Option<T>.None(),
                _ => throw new JsonSerializationException($"Unknown Option variant: {kindStr}")
            };
        }

        public override void WriteJson(JsonWriter writer, Option<T>? value, JsonSerializer serializer)
        {
            if (value is null) { writer.WriteNull(); return; }
            writer.WriteStartObject();
            switch (value)
            {
                case Option<T>.Some _v:
                    writer.WritePropertyName("kind");
                    writer.WriteValue("Some");
                    writer.WritePropertyName("Value");
                    serializer.Serialize(writer, _v.Value);
                    break;
                case Option<T>.None:
                    writer.WritePropertyName("kind");
                    writer.WriteValue("None");
                    break;
                default:
                    throw new JsonSerializationException($"Unknown Option variant: {value}");
            }
            writer.WriteEndObject();
        }
    }

    [Newtonsoft.Json.JsonConverter(typeof(OptionNsjConverterFactory))]
    public abstract partial record Option<T> { }
}
