// <auto-generated/>
#nullable enable

namespace MyApp
{
    abstract partial class Command
    {
        private Command() { }

        sealed partial class Start;
        sealed partial class Stop;

        public bool IsStart => this is Start;
        public bool IsStop => this is Stop;
    }
}
